### ISSUE TITLE
Snapshot is Read-Only?

### ISSUE THREAD

**Issue by fullmoonguru** [teejee2008/timeshift#103]
Hey, I made a snapshot of a Mint 18.3 build I did in Virtualbox.  I'm trying to copy to a usb drive but getting read-only errors.  I even tried to chmod -R 755 the folder but still the same thing.  How do I gain the ability to move this folder to another drive?

**Comment by teejee2008** [comment]
Snapshots should not be moved to another drive. It will break hard links between the files.
