### ISSUE TITLE
Show how much space a snaphsot uses

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#105]
It would be great to have a column, which shows how big (GB) a snapshot is.
Trying to look at the size with nemo or baobab takes ages to load.

**Comment by teejee2008** [comment]
It's not possible to estimate actual snapshot size since files are shared between snapshots. I could show the total size but that wilk be misleading.

**Comment by teejee2008** [comment]
For BTRFS snapshots, the size will be displayed in the list.

**Comment by teejee2008** [comment]
(For BTRFS snapshots)
![image](https://user-images.githubusercontent.com/12488854/34906292-ba8bc1ee-f890-11e7-92ac-6f54863e3507.png)
