### ISSUE TITLE
Disc not detected

### ISSUE THREAD

**Issue by leolivier** [teejee2008/timeshift#107]
Hi,
When I ran timeshift for the first time, it did not detect one of my disks (or more precisely, it did not detect the partitions on this disk) although they exist:
```
$ df
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
cgmfs              100K       0  100K   0% /run/cgmanager/fs
tmpfs              5,0M    8,0K  5,0M   1% /run/lock
tmpfs              789M    9,7M  780M   2% /run
/dev/sdb5          976M    125M  785M  14% /boot
tmpfs              789M     48K  789M   1% /run/user/1000
tmpfs              3,9G    1,7G  2,2G  44% /dev/shm
tmpfs              3,9G    433M  3,5G  11% /tmp
tmpfs              3,9G       0  3,9G   0% /sys/fs/cgroup
tmpfs              3,9G    880K  3,9G   1% /var/log
udev               3,9G       0  3,9G   0% /dev
/dev/sdb7           40G     22G   16G  59% /
/dev/sdb8          229G    149G   69G  69% /data
/dev/sdb2          191G     59G  124G  33% /data2
/dev/sda4          932G    191G  741G  21% /hdd
/dev/sde1          917G     17G  854G   2% /media/olivier/exthdd

```
As you can see, there is a partition /dev/sda4 mounted on /hdd 
Timeshift says: (sorry in French)
![image](https://user-images.githubusercontent.com/4014752/34409884-ea559bb4-ebcc-11e7-9e69-3b5217fdee74.png)

This is precisely where I want to put my timeshift backup. How can I restart the detection?

EDIT: BTW, "refresh" does nothing...

**Comment by teejee2008** [comment]
What's the filesystem on it?
Only partitions with Linux filesystems are shown.

**Comment by leolivier** [comment]
```
$ mount -l | grep /dev/sda4
/dev/sda4 on /hdd type fuseblk (rw,nosuid,nodev,noatime,user_id=0,group_id=0,allow_other,blksize=4096) [HDD]
/dev/sda4 on /backup type fuseblk (rw,nosuid,nodev,noatime,user_id=0,group_id=0,allow_other,blksize=4096) [HDD]

```
So not supported?

**Comment by teejee2008** [comment]
your output doesn't show the filesystem.
post the output of `lsblk --fs`

**Comment by leolivier** [comment]
It's ntfs:
`sda4                     ntfs   HDD   7F2EA38D6746F7AB                     /hdd
`

**Comment by teejee2008** [comment]
ntfs is not supported

**Comment by leolivier** [comment]
Ok.
