### ISSUE TITLE
First run in cli mode: 515% complete

### ISSUE THREAD

**Issue by zaszlo** [teejee2008/timeshift#109]
```
sudo timeshift --create --comments "clean install with basic config"
First run mode (config file not found)
Selected default snapshot type: RSYNC

(process:3690): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(process:3690): Gtk-CRITICAL **: gtk_icon_theme_append_search_path: assertion 'GTK_IS_ICON_THEME (icon_theme)' failed
Selected default snapshot device: /dev/mmcblk0p1
------------------------------------------------------------------------------
Estimating system size...
Creating new snapshot...(RSYNC)
Saving to device: /dev/mmcblk0p1, mounted at path: /var/log.hdd
Synching files with rsync...
512.12% complete (00:00:00 remaining)
```

It goes on forever...

**Comment by teejee2008** [comment]
Do you have a display server installed? The console version requires a display.

**Comment by zaszlo** [comment]
My ubuntu xenial is actually optimized for the arm processor (armbian) maybe this causes it. I left it for about 10 hours to create this snapshot and it did finish it with reporting that an error occured, but doesn't say more:

1212.23% complete (00:00:00 remaining)
(process:3690): GLib-GIO-CRITICAL **: g_output_stream_clear_pending: assertion 'G_IS_OUTPUT_STREAM (stream)' failed

(process:3690): GLib-GIO-CRITICAL **: g_output_stream_clear_pending: assertion 'G_IS_OUTPUT_STREAM (stream)' failed
E: rsync returned an error                                                      
E: Failed to create new snapshot
Failed to create snapshot
------------------------------------------------------------------------------
Removing snapshots (incomplete):
------------------------------------------------------------------------------
Removing '2017-12-30_13-12-15'...
Removed '2017-12-30_13-12-15'                                                   
------------------------------------------------------------------------------

**Comment by zaszlo** [comment]
​I issued the commands via ssh but it has a display server, only that I was running it from terminal​ without gui.

**Comment by zaszlo** [comment]
Have answered it now on the github issue, but for some reason I do not see
this question of yours Tony George there.

**Comment by zaszlo** [comment]
It was my fault, I didn't add the --snapshot-device parameter and had only ntfs external drive attached. With an external ext4 partition and explicitly setting the snapshot device it works. 
I thought that it automagically selected a suitable partition as it didn't asked for it. Maybe if no external suitable partitions are found or specified there could be just a notification message about this without starting the creation of a restore point.

Thank you for following up with me though!

**Comment by zaszlo** [comment]
The issue is solved, but here is the /proc/mounts . I have an external
drive attached via usb. has an ntfs partition.

sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs
rw,nosuid,relatime,size=439456k,nr_inodes=109864,mode=755 0 0
devpts /dev/pts devpts
rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=101660k,mode=755 0 0
/dev/mmcblk0p1 / ext4 rw,noatime,nodiratime,errors=remount-ro,commit=600 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime
0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup
rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup
rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset
0 0
cgroup /sys/fs/cgroup/devices cgroup
rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/perf_event cgroup
rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup
rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/freezer cgroup
rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory
0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs
rw,relatime,fd=24,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13540
0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
tmpfs /tmp tmpfs rw,nosuid,relatime 0 0
/dev/mmcblk0p1 /var/log.hdd ext4
rw,noatime,nodiratime,errors=remount-ro,commit=600 0 0
log2ram /var/log tmpfs rw,nosuid,nodev,noexec,relatime,size=51200k,mode=755
0 0
/dev/sda1 /var/www/html/data fuseblk
rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096
0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/sda2 /media/externalBackup ext4 rw,noatime,data=ordered 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
tmpfs /run/user/1000 tmpfs
rw,nosuid,nodev,relatime,size=101660k,mode=700,uid=1000,gid=1000 0 0
