### ISSUE TITLE
x64 File missing from dropbox

### ISSUE THREAD

**Issue by igrlas** [teejee2008/timeshift#11]
Hi, I didn't know where to put this, it is not a bug report but there is no 64-bit file on Dropbox, the link is broken. If you don't mind, can you please re-upload or re-link to the 64-bit file. Thanks!

**Comment by teejee2008** [comment]
Dropbox download are no longer available.
You can download from releases page
[https://github.com/teejee2008/timeshift/releases](https://github.com/teejee2008/timeshift/releases)
