### ISSUE TITLE
Wrong translation for "Tags"

### ISSUE THREAD

**Issue by sgse** [teejee2008/timeshift#110]
At 1st, thanks for that very helpful application :-)
On linuxmint german translation is very good but for "Schlagwörter" = tags? it is not correct.
![13](https://user-images.githubusercontent.com/17575778/34589384-a13d5324-f1b0-11e7-8d71-784fcc70f4c2.png)
"M" is for Manuell and Monatlich, I think Manuell must be "O" ?.
"A" = Systemstart could be "B" for "Boot" ?
"D" means "Daily" in tags it was "T" = Täglich
My english is very bad, sorry for that :-)

**Ahhhh ;-)**

#: Gtk/SnapshotListBox.vala:274
msgid ""
"<b>Backup Levels</b>\n"
"\n"
"O\tOn demand (manual)\n"
"B\tBoot\n"
"H\tHourly\n"
"D\tDaily\n"
"W\tWeekly\n"
"M\tMonthly"
msgstr ""
"<b>Sicherungsebenen</b>\n"
"\n"
"M\tManuell\n"
"A\tSystemstart\n"
"S\tStündlich\n"
"T\tTäglich\n"
"W\tWöchentlich\n"
"M\tMonatlich"

**Comment by teejee2008** [comment]
Thanks for reporting this. Translation will be updated.
