### ISSUE TITLE
Move snapshots or select another location

### ISSUE THREAD

**Issue by ovisergiu** [teejee2008/timeshift#111]
Hi!
I have a question, not a bug.

It seems I do not have enough space to make new snapshots, and I really do not want to delete any of the snapshots I already have. 
I am using Linux Mint 18.3 XFCE in a Virtual Box machine (50 GB drive assigned for this machine).

Can I move the snapshots to another drive or there is a possibility to set Timeshift to put the new snapshots in another partition? Or do I have to create another virtual machine with more space?
Thank you!

**Comment by teejee2008** [comment]
Rsync snapshots cannot be moved easily. If you try to move them manually, the shared files will get duplicated and use up a lot of space on the destination.

You can move them manually with following command, but its not recommended:
`sudo rsync -avhL snapshots/ newlocation/`

**Comment by ovisergiu** [comment]
Thank you for your answer!
My linux usage level ”does not allow me” to do that.
You can close this topic.
