### ISSUE TITLE
/timeshift as a mountpoint

### ISSUE THREAD

**Issue by ombbln** [teejee2008/timeshift#113]
For my needs, it would be nice if /timeshift could be a mountpoint (can it be, it works) and Timeshift would measure the space available on the mountpoint instead of the space available on the device with the mountpoint.

Thank you for the valuable tool!

**Comment by teejee2008** [comment]
/timeshift on the backup device should not be a mounted folder. It should be a folder on the same backup device. You will may run into issues with your current setup.
