### ISSUE TITLE
download timeshift-latest-i386.run & timeshift-latest-amd64.run: dropbox file not found

### ISSUE THREAD

**Issue by ombbln** [teejee2008/timeshift#114]
is there a working way to download timeshift for other distributions?

**Comment by teejee2008** [comment]
https://github.com/teejee2008/timeshift/releases

Where did you come across the Dropbox link?

**Comment by ombbln** [comment]
http://www.teejeetech.in/p/timeshift.html

and thanks for the right link. saved my day!
