### ISSUE TITLE
/var/log/timeshift/ - folder nearly folder flooded with hourly backup.logs

### ISSUE THREAD

**Issue by nostromo123** [teejee2008/timeshift#115]
Linux Mint 18.2 Xfce.

Have timeshift active with weekly and monthly backups. But having a look at /var/log/timeshift/ there is a flood of hourly log files. Every hour, the computer is on, a new log is generated.

Is that supposed to be so? Can this be stopped?

/etc/timeshift.json lokks like this here
`{
  "backup_device_uuid" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "parent_device_uuid" : "",
  "do_first_run" : "false",
  "btrfs_mode" : "false",
  "include_btrfs_home" : "false",
  "stop_cron_emails" : "false",
  "schedule_monthly" : "true",
  "schedule_weekly" : "true",
  "schedule_daily" : "false",
  "schedule_hourly" : "false",
  "schedule_boot" : "false",
  "count_monthly" : "2",
  "count_weekly" : "3",
  "count_daily" : "5",
  "count_hourly" : "6",
  "count_boot" : "5",
  "snapshot_size" : "9292056173",
  "snapshot_count" : "317574",
  "exclude" : [
    "+ /root/**",
    "+ /root/.**"
  ],
  "exclude-apps" : [
  ]
}`

br

**Comment by teejee2008** [comment]
There's a maintenance job that runs every hour for creating new snapshots and deleting old ones.

500 log files are kept at maximum, so that log files will be available for last 20 days (24 x 30). Log files are roughly 10 KB in size, so 500 files will take up about 5 MB of space. Let me know if you have more than 500 files in this location or if anything else is unusual.

**Comment by nostromo123** [comment]
Thank you for clarifying. It is not the size of the log files, but the number, which makes things a bit confusing.
Reconfigured timeshift in the mean time to "on demand", which stopped those hourly logs, but shall revert to weekly/monthly and watch the situation and report back ....
br

**Comment by nostromo123** [comment]
Perfect! At noon today I saw 501 objects and now that

![bildschirmfoto_2018-02-22_18-53-16](https://user-images.githubusercontent.com/17964433/36555255-51954632-17f9-11e8-8fb7-ceec686e9d5e.png)
