### ISSUE TITLE
Issue with schroot

### ISSUE THREAD

**Issue by clefebvre** [teejee2008/timeshift#116]
Hi @teejee2008 

I found an issue in a nice use case.

- I have /dev/sdb1 mounted at /mnt/data (it's an additional HDD to give me more space.. for virtualbox, chroots etc..).
- I have schroot configured with chroots in /mnt/data/chroot.
- /mnt/data is exluded from my timeshift configuration.
- At boot time, schroot automatically mounts a few things into /var/lib/schroot/mount

Timeshift is configured to save snapshots on /dev/sdb1, which at the time was /mnt/data (and still is)... but when you run Timeshift, it deduces from the mounts, that /dev/sdb1 is in /var/lib/schroot/mount/*.

This results in the snapshot never finishing.

I'll have to dig down further to fully understand why and what exactly is going on... but I would recommend adding /var/lib/schroot to the list of excluded paths by default.

**Comment by teejee2008** [comment]
I'll check and let you know. 
There was a similar issue with Docker which is why /var/lib/docker is excluded.

**Comment by teejee2008** [comment]
I'll check and let you know. 
There was a similar issue with Docker which is why /var/lib/docker is excluded.

**Comment by teejee2008** [comment]
/var/lib/schroot will be excluded by default in v18.1
