### ISSUE TITLE
Broken Dropbox links in README.md

### ISSUE THREAD

**Issue by calinb7** [teejee2008/timeshift#12]
Other Linux Distributions

Download the installer from following links:
timeshift-latest-i386.run (32-bit, 170 KB)
timeshift-latest-amd64.run (64-bit, 180 KB)

**Comment by drbree82** [comment]
I too have this problem and am unable to install in debian as a result. (PPA doesn't work in debian)

**Comment by drbree82** [comment]
Installers for other distros can be found at https://github.com/teejee2008/timeshift/releases

Thanks TeeGee

**Comment by teejee2008** [comment]
I'll update the readme. Downloads are available on the Releases page.
[https://github.com/teejee2008/timeshift/releases](https://github.com/teejee2008/timeshift/releases)

**Comment by teejee2008** [comment]
README is updated
