### ISSUE TITLE
backup on resuming?

### ISSUE THREAD

**Issue by amithiel** [teejee2008/timeshift#120]
Hey, just start using timeshift, i set it up and forgot about it, 2 days later i realized its not backing up. 
After reading the documentation, you meant it backups up after system boot (10 minutes). Turns out, i never turn off my laptop, i just close the lid and suspend. Is there a way to make timeshift activate without having to do it manually? thanks
i'm using linuxmint 18.3, on a macbook pro 11,2.

**Comment by teejee2008** [comment]
Select the hourly backup level. It will take backup every hour.
