### ISSUE TITLE
where is the default backup  directory  ? 

### ISSUE THREAD

**Issue by videni** [teejee2008/timeshift#123]
I removed all files in /usr/bin, I can't open timeshift with command , I have to copy all files back manually, where is the default  backup directory please?

**Comment by teejee2008** [comment]
Its under **/timeshift/snapshots** on the root of the backup device

**Comment by teejee2008** [comment]
Path is **/timeshift-btrfs/snapshots** for btrfs snapshots

**Comment by MJimitater** [comment]
Timeshift has saved me so much hassle, thank you for this great software!
Will it actually suffice if I backup these snapshot folders in `/timeshift/snapshots`, in order to install a different OS, and then reinstall my OS and return to my current system state? Thank you

**Comment by GabrielDeml** [comment]
For me it is: /home/timeshift
