### ISSUE TITLE
How to boot Live CD/USB in EFI mode?

### ISSUE THREAD

**Issue by Ferryfolk** [teejee2008/timeshift#126]
Quote from Known Issues:
"If you are restoring from Live CD/USB, and your installed system uses EFI mode, then you must boot from Live CD/USB in EFI mode." How do you do this in Linux Mint?

**Comment by teejee2008** [comment]
You have to go into the UEFI boot menu when your PC starts by pressing F12 or Delete key. Under the boot devices menu, it will have options for booting in both BIOS and UEFI mode.
