### ISSUE TITLE
Quota support should be optional

### ISSUE THREAD

**Issue by KillWolfVlad** [teejee2008/timeshift#127]
Quota system have slightly unpleasant [known issues](https://btrfs.wiki.kernel.org/index.php/Quota_support#Known_issues), so will be useful to disable it.

`timeshift` forcibly execute this commands (without any questions):

- `# btrfs quota enable <path>`
- `# btrfs quota rescan <path>`

But without quota will not be possible to know snapshots size (or execute this command`# btrfs qgroup show`)

I think in settings (and first launch wizard) should be a check box (enabled by default)

![image](https://user-images.githubusercontent.com/18448635/35196886-f58ce100-fef9-11e7-8766-f3cb37606000.png)

**Comment by teejee2008** [comment]
I have never noticed any performance issues with quotas, but I'll add an option to disable it.

**Comment by teejee2008** [comment]
Added option in v18.4
