### ISSUE TITLE
Snapshot in command line showing more than 100% completed

### ISSUE THREAD

**Issue by Mithrandir7** [teejee2008/timeshift#13]
When creating a snapshot using command line it goes beyond 100%. It is just a graphical issue since the snapshot completed eventually.

![image](https://user-images.githubusercontent.com/5897324/27933615-8ac22f7e-6278-11e7-8436-ba0645e4400a.png)

**Comment by teejee2008** [comment]
It will go above 100% if there are more files to backup than what it counted before starting the backup. Its harmless.
