### ISSUE TITLE
localization - where is upstream?

### ISSUE THREAD

**Issue by p-bo** [teejee2008/timeshift#131]
Installed version 18.1.1 recently and noticed, that there are untranslated strings - and in https://github.com/teejee2008/timeshift/tree/master/po are newer .po data than on https://translations.launchpad.net/linuxmint/latest/+pots/timeshift
From result of https://github.com/teejee2008/timeshift/issues/23 it seemed, that upstream translation is now in Linux Mint project.
So, where to translate new strings now?
Thanks :)

**Comment by teejee2008** [comment]
Upstream translations are indeed in 
https://translations.launchpad.net/linuxmint/latest/+pots/timeshift

I sometimes get pull requests for PO file changes and I merge them directly. So the PO files in GitHub can sometimes have translations that are newer than upstream.

**Comment by p-bo** [comment]
Thanks for explanation, so would it be possible to initiate update of po data on launchpad for translators to be able to work on them there too, please?
Thanks :)

**Comment by teejee2008** [comment]
translations are merged for v18.2

**Comment by p-bo** [comment]
Thanks for that, but even so, in .po files on https://github.com/teejee2008/timeshift/tree/master/po are strings, that aren't present (thus translatable) on https://translations.launchpad.net/linuxmint/latest/+pots/timeshift
It seemed (https://github.com/teejee2008/timeshift/issues/23) that Linux Mint translation project was chosen as upstream of translations for Timeshift, but now lacks behind. Now what - where we, translators are supposed to translate?
