### ISSUE TITLE
Timeshift confusing my docker images directory with system root

### ISSUE THREAD

**Issue by nikhilw** [teejee2008/timeshift#133]
Issue:
I have moved my docker images to a directory under my /home (which is a partition). When  I select the /home drive for timeshift, it is moving all the snapshots to the docker-images home. From the documentation I understand that timeshift is supposed to create a /timeshift directory, this gets created under the /home/myuser/docker-images/aufs/timeshift instead.

Steps to reproduce:
1. install docker and move the images directory (docker_home) to a different partition. Ex: /home/yourname/docker-images
2. Enable timeshift backups and select the /home drive.
3. Check the location where the backups are being kept.

Expected behaviour:
Timeshift should correctly identify root of a file system or partition when creating /timeshift directory. Please fix this issue to allow for identifying correct root of a partition. Alternatively, would it be possible to allow for selecting a backup directory?

**Comment by teejee2008** [comment]
Docker is not supported
https://github.com/teejee2008/timeshift/wiki/Supported-System-Configurations

**Comment by nikhilw** [comment]
Thanks for your reply. I did not intend to imply that timeshift should support docker, rather the opposite, that it should not support docker nor incorrectly use docker's image directory to store backups. But I see that this behaviour comes under _unpredictable_ result, so makes sense.

Regarding the other question, would it be possible to allow selecting a directory (instead of a drive) as  backup location?

**Comment by rnsc** [comment]
I encountered the same issue.
Although I understand there's no support for Docker itself, I don't understand why TimeShift would choose to locate itself in the docker folder when that folder is placed in /home.
