### ISSUE TITLE
Non-standard home directory not excluded

### ISSUE THREAD

**Issue by b4ndit** [teejee2008/timeshift#138]
Timeshift correctly lists root (/root), my user (/home/myuser), and libvirt-qemu (/var/lib/libvirt) as user home directories under the "Users" tab. "Include hidden items" and "Include everything" are not checked for any user.

Relevant /etc/passwd entry:
`libvirt-qemu:x:64055:137:Libvirt Qemu,,,:/var/lib/libvirt:/bin/false`

Timeshift seems to properly exclude /root and /home, but does not exclude /var/lib/libvirt. This causes timeshift to backup virtual machine disks and run the computer out of all available disk space. Adding the directory (/var/lib/libvirt/***) as a filter seems to exclude it properly, but it's my understanding that it should have been excluded since it's listed as a user home directory and the GUI explicitly says that it should be excluded.

Is this a bug?

I'm using Linux Mint 18.3 Sylvia

**Comment by teejee2008** [comment]
Timeshift only excludes normal ("human") users. It does not exclude system users created by applications. You need to exclude this manually.
