### ISSUE TITLE
Could you create a snap package for timeshift?

### ISSUE THREAD

**Issue by altntowin** [teejee2008/timeshift#139]
Hi, I really appreciate your work , is a good application

could you make a snap package for timeshift?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by teejee2008** [comment]
I'm not a supporter of Snap and Flatpack. These packaging formats have unfinished design and create more problems than the formats they intend to replace.

Since this is an open-source project if someone wants to create a snap package they can do so, but I won't be providing support for it.

**Comment by teejee2008** [comment]
You can use the installers provided on the release page on any distribution based on Debian, Ubuntu, Arch or Fedora.
