### ISSUE TITLE
Publish to AppCenter

### ISSUE THREAD

**Issue by png2378** [teejee2008/timeshift#14]
Since you moved to GitHub, it would be cool to [publish](https://medium.com/elementaryos/so-you-wanna-publish-on-appcenter-12c675b56e1c) TimeShift in AppCenter (elementary OS software center).

This will increase the popularity of TimeShift and will allow you to monetize it.

**Comment by teejee2008** [comment]
Elementary takes a cut of 30% of the amount donated. This is not something I wish to support.
