### ISSUE TITLE
Request for advice: how to programmatically determine that a job is running?

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/timeshift#140]
I'd like to be able to detect programmatically whether a (any) TimeShift backup is running. I have a script that used to be able to do this, I think; but it no longer works.

It seems Timeshift runs `rysnc`, with a path that marks the `rsync` job as owing to Timeshift, in that the path of the rsyncincludes the word 'timeshift'. Detecting such a process may be beyond my Bash skills (though ultimately I'd like to do it in, er, Lua). Is there some Bash one-liner, or perhaps a few lines of Bash, that would do it, please?

**Comment by teejee2008** [comment]
The GUI runs rsync directly but the background jobs run the command "timeshift --check". You can check if this command is running.

**Comment by CottonEaster** [comment]
Thank you.
