### ISSUE TITLE
Partially critical bugs in the German locale

### ISSUE THREAD

**Issue by Cos-mo** [teejee2008/timeshift#147]
System Linux Mint 18.3 Cinnamon 64 bit

TimeShift 18.2

TS had been installed with Mint 18.3 (version 17.11), and by adding the PPA teejee2008 ben upgraded to the latest version.

The German translation is partly not only misleading, but simply far away from the original meaning.

Problem are the preferences.

Section Users:
There are at the right side 3 columns. In English language the headers say:
`Exclude All
Include Hidden
Include All
`
In German language they say
`Anwendungen ausschließen (exclude applications)
Versteckte Einträge einschließen (include hidden entries)
Anwendungen ausschließen (exclude applications)`
The re-translations in brackets are done by me.
Even without German language knowledge you see, that the first and the last columns have an identical header. This makes them totally useless, as nobody can see, what they really mean. Besides that the word "Anwendungen (applications)" is in this context totally wrong (and nowhere to be found in the English wording).

Another problem is on the Schedule side:
There are 3 notes at the bottom. I leave here out the second note, which is not translated in the German locale and is not my concern here. (At least it is correct in the meaning.)
The first note in English:
`Snapshots are not scheduled at fixed times`
The third note in English:
`Boot snapshots are created with a delay of 10 minutes after system startup`

Now the German text (again retranslated by me to show the problems):
`Schnappschussgerät nicht ausgewählt
(snapshot device not selected)`
and
`Schnappschüsse werden durch die enthaltene Funktion des BTRFS Dateisystems erstellt
(snapshots get created by the included function of the BTRFS file system)`

Regarding the first note:: A snapshot device is actually selected as to be seen on the Location page; besides that: TS works here without issues. So the content of the German localle is not only obviously quite different to the English original, it is purely wrong.
Regarding the third note: Heaven knows, how the German text came into this place: It has not the least to do with the English text.

The problem with the German translation is, that the German locale gets automatically selected, if the user account is set to German language (at least in Mint). So the user has no choice to select the language specifically for TS. I had created another user account with English language to read the original text, but I know, that numerous German users have not the least knowledge about English language, so that this is for them not a usable option.

**Comment by Tanarri** [comment]
Hi made a pull request #143 which corrected many issues, but is not merged yet. Because this ist my first pull request ever I hope I did it right.
Today I read at https://github.com/teejee2008/timeshift there is a portal from Mint at https://translations.launchpad.net/linuxmint/latest/+pots/timeshift where the translations are located.

So I hope my pull request is right, and Linux Mint will get the translations somehow.

Does anybody know better?

**Comment by teejee2008** [comment]
Translations are being maintained by the Linux Mint team. Its better to update there directly instead of sending me a pull request. Any changes I merge may get lost when I sync again from the Launchpad translations.
https://translations.launchpad.net/linuxmint/latest/+pots/timeshift/de/+translate

The updated translation is included in v18.4.

**Comment by Tanarri** [comment]
Thanks
I will do the work on launchpad one again.

Today I installed the V18.4 and the german translation is missing. Following directory is empty:
/usr/share/locale/de/LC_MESSAGES

**Comment by Cos-mo** [comment]
I confirm, that in 18.4 there is no translation for German. And actually this is - as long, as no usable translation exists - the best available solution at all. At least TS display now the information and text, which it should display, and not the disaster, which I reported above.

**Comment by Cos-mo** [comment]
I just noticed, that removing / disabling the translation has created a new problem: The tool tip to show the meaning of the tags in the list of snapshots does no longer appear.

@teejee2008 : Please reopen the issue or advise, if a new issue should get opened.
