### ISSUE TITLE
Problem with starting

### ISSUE THREAD

**Issue by snusmoomrick** [teejee2008/timeshift#149]
I have installed timeshift from AUR repository on my Arch Linux with Xfce DE. When I trying to start the program from menu, it requires root password and then nothing happened. The command line in menu item is "timeshift-launcher" by default. When I trying to execute this command via terminal, the window with authentication request also appears, I enter the root password and then the program fails with an error: **(timeshift-gtk:6536): Gtk-WARNING **: cannot open display:**. When I trying **sudo timeshift-launcher** the program starts normally. But it's not working via Xfce menu.
So, what's wrong with it?

**Comment by teejee2008** [comment]
Log in to an Xwindow session. Wayland session is not supported.
