### ISSUE TITLE
"Snapshots cannot be created in Live CD mode" issue

### ISSUE THREAD

**Issue by DareDevil73** [teejee2008/timeshift#154]
Hi, I installed my Linux Mint 18.3 on a loopback file booting from a USB drive (where I put Grub and boot partition).

Timeshift says me "Snapshots cannot be created in Live CD mode" so I cannot create backups.

Could you explain me how to bypass this?

Thank you so much!

**Comment by teejee2008** [comment]
There's no way to bypass. This setup is not supported.
