### ISSUE TITLE
Publish in elementary AppCenter

### ISSUE THREAD

**Issue by michaelkanis** [teejee2008/timeshift#157]
I'd like to kindly propose you put timeshift on elementary OS' AppCenter.

- You already have deb packaging in place, so I guess this would be straight forward
- elementary OS is sorely missing a decent backup app
- PPAs are a pain for "normal users", especially when upgrading to a new release
- AppCenter allows putting a price tag on the app with their "humble button" and makes the process of "donating" straight forward and simple

Thanks very much for your work.

**Comment by teejee2008** [comment]
Elementary takes a cut of 30% of the amount donated. This is not something I wish to support.
For $1 payments, 50 cents are taken by elementary and another 30 cents are taken by PayPal, leaving 20 cents for the developer.
