### ISSUE TITLE
timeshift: error while loading shared libraries: libvte2_90.so.9

### ISSUE THREAD

**Issue by Futureknows** [teejee2008/timeshift#16]
I get this error in Fedora 26. I've installed all dependencies. Works fine in Mint.

` [user@localhost ~]$ timeshift
timeshift: error while loading shared libraries: libvte2_90.so.9: cannot open shared object file: No such file or directory`

**Comment by srakitnican** [comment]
Try following builds: https://copr.fedorainfracloud.org/coprs/srakitnican/default/build/599481/

**Comment by Futureknows** [comment]
Worked! Thanks!
