### ISSUE TITLE
Installed Docker and now Timeshift backup dir changed to a docker one

### ISSUE THREAD

**Issue by fullofcaffeine** [teejee2008/timeshift#161]
I've seen it reported before. Please note that *I'm not using Timeshift inside Docker*, I merely installed Docker in the system that runs on metal (Mint 18.3) because I use it for development purposes. Now timeshift switched to another dir

I don't understand why installing Docker-CE in a system backup'ed by Timeshift would wreak havoc. Could someone enlighten-me? 

I can understand that timeshift can't backup systems that are containerized by Docker, but in my case, Mint 18.3 is running on the metal (a XPS 15 Laptop) and not inside Docker.

**Comment by fullofcaffeine** [comment]
Any hints to work around that? I don't mind not backup'ing docker-related files. Should I just exlcude them?

**Comment by teejee2008** [comment]
I have no idea what suggestion to give you. I don't know much about Docker and I have no interest in it.

Avoid using Timeshift with Docker. It doesn't matter if system is containerized or if Docker is installed separately. It is not supported by me.

You can go through the code and investigate the issue if you are interested. Submit a pull request if you are able to fix the issue.
