### ISSUE TITLE
btrfs: can I disable quota in timeshift ?

### ISSUE THREAD

**Issue by 3cola** [teejee2008/timeshift#164]
First of all, I want to say that I love timeshift, it is a really nice tool leveraging on btrfs snapshot functionnality !

But... It gets a little bit too crazy and ressource concumming with btrfs quota enabled. Is it possible disable the btrfs quota int timeshift ?

If not, would it be possible for timeshift to work without quota, and could we have this wonderful feature ?

thanx a lot, your work is really appreciated here !

**Comment by 3cola** [comment]
sorry,

I did not see that it was duplicate of https://github.com/teejee2008/timeshift/issues/127

**Comment by teejee2008** [comment]
Added an option to the "Users" tab in v18.4
