### ISSUE TITLE
vala 0.36: Gtk/ExcludeBox.vala:301.17-301.20: error: Argument 1: Cannot pass value to reference or output

### ISSUE THREAD

**Issue by srakitnican** [teejee2008/timeshift#17]
Fatal build error with GCC7 on Fedora 26 and newer.

```
Gtk/ExcludeBox.vala:301.17-301.20: error: Argument 1: Cannot pass value to reference or output parameter
			store.remove(item);
			             ^^^^
```

https://copr-be.cloud.fedoraproject.org/results/srakitnican/default/fedora-26-x86_64/00599481-timeshift/build.log.gz

**Comment by srakitnican** [comment]
Ok that error is because of newer vala version (0.36) and not GCC. Replacing `item` with `ref item` fixes build error but I have no idea how it affects the code.

**Comment by teejee2008** [comment]
Fix committed. Latest code will build with valac-0.36
