### ISSUE TITLE
Feature Request or How to select destination backup folder and or filename suffix or prefix?

### ISSUE THREAD

**Issue by phd21** [teejee2008/timeshift#172]
Hello Timeshift developer(s),

First, thank you for this excellent application!

Secondly, I cannot find a way to tell TimeShift where to put the backup snapshots other than selecting a particular drive partition and or to be able to select a snapshot filename suffix or prefix? 

I would like to be able to select a folder or create one to store the snapshots and or be able to specify a snapshot filename. For example: If I have an external USB drive(s) to store the snapshots, and I have more than one operating system installed, or want to take snapshots of more than one computer, and use the same USB backup drive, how does TimeShift know which snapshots belong to which computer or which operating system on a computer with more than one OS installed without being able to choose the filename or destination folder? If could select the snapshot filename (filename suffix or prefix),  I could use "Date_Time_Dell_OptiPlex780-1_LinuxMint_KDE_v183", or "Date_Time_IBM_NetVista1_LM_Cinnamon_v183", etc... And or using folder names, in the same manner, would work as long as TimeShift would store the snapshots for that computer and operating system in that specific folder. 

TimeShift could read the system information to automatically create a more unique system specific snapshot filename and or directory tree structure as a default for whichever computer and operating system it is run on, which might work well too and would reduce user errors. But, what if you have someone using 2 identical computers with the same operating system, I guess if they used a different username, or if the serial # was accessible, then that could be used for unique snapshot identification, "Date_Time_Dell_OptiPlex780__Serial#_LinuxMint_KDE_v183_User1".

Best regards,
Phil (phd21)

**Comment by teejee2008** [comment]
One device can be used for storing snapshots for one system only. You will face issues if you use the same device for multiple systems.

**Comment by LorenzoBettini** [comment]
Just for curiosity, which kind of issues one would face if using the same device for multiple systems?

**Comment by teejee2008** [comment]
All snapshots are saved under the same location and each snapshot is hard-linked with previous one. If the previous snapshot is from another system then all files will be treated as new files and copied again. This wastes a lot of space.

**Comment by LorenzoBettini** [comment]
That's why it would be useful to specify a directory in the destination device. So that the same device could be used with multiple systems, each one with a specific destination directory...

**Comment by thegitfather** [comment]
First: thanks for your effort - I love the simplicity of the tool!

I'm also using timeshift for two linux systems and I think this feature (at least in /etc/timeshift.json) would be helpful for some users. Alternative: create a subfolder with the `sys-uuid`.
