### ISSUE TITLE
Question: will deleting old snapshots cause me to lose data?

### ISSUE THREAD

**Issue by christophra** [teejee2008/timeshift#175]
I have a bunch of manual snapshots, which don't get cleaned up like the daily ones do. Can I delete the old ones (via timeshift, of course, not deleting the directory) without losing data that was last changed during one of these snapshots?
I would assume this is something Timeshift takes care of. However I didn't see it explained in the documentation either, so I thought it would be good to ask.

**Comment by teejee2008** [comment]
You can delete any snapshot with affecting other snapshots. Each snapshot is a complete copy.

**Comment by Wikinaut** [comment]
@teejee2008 wrote
> You can delete any snapshot with affecting other snapshots. Each snapshot is a complete copy.

Did you mean ***without*** *affecting* or ***with*** *affecting* other snapshots?

Nevertheless, this should be written in the wiki pages and in the Timeshift help/documentation.

**Comment by teejee2008** [comment]
without affecting
