### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by dnagel53** [teejee2008/timeshift#176]
Timeshift:
Utility/Gtk/TerminalWindow.vala:172.19-172.50: error: Argument 1: Cannot convert from `char[]' to `unowned string?'
		term.feed_child("%s\n".printf(command).to_utf8());
		                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compilation failed: 1 error(s), 80 warning(s)
make[1]: *** [makefile:37: all] Error 1
make: *** [makefile:2: all] Error 2
/usr/bin/makepkg: line 740: logpipe: unbound variable

**Comment by anonymous352** [comment]
Same error here too when trying to Make via Arch AUR.

**Comment by Ste74** [comment]
Maybe duplicate of this 
https://github.com/teejee2008/timeshift/issues/169

**Comment by teejee2008** [comment]
feed_child() function has changed in libvte

earlier: `term.feed_child("%s\n".printf(command), -1); `
now: `term.feed_child("%s\n".printf(command).to_utf8());`

The earlier line will work on Xenial which still has the older libvte in its repos.

**Comment by teejee2008** [comment]
Fixed in v18.6.1
