### ISSUE TITLE
Ubuntu 18.04 to 17.10 Restore Compatibility

### ISSUE THREAD

**Issue by juan11perez** [teejee2008/timeshift#183]
Good day. Apologies if the subject is unclear. 
Currently running Ubuntu 17.10. Thinking on migrating to 18.04; is restoring from a 17.10 snapshot possible? thank you

**Comment by teejee2008** [comment]
Yes, this is possible. After upgrading, if you restore the 17.10 snapshot , you will get the old system back.
There is a small chance that the restored system will fail to boot. Some manual fixes may be required after restore.

**Comment by juan11perez** [comment]
thank you
