### ISSUE TITLE
Does Timeshift run at startup

### ISSUE THREAD

**Issue by rickstaa** [teejee2008/timeshift#188]
Dear Developer,

I, unfortunately, couldn't find out from the documentation if I needed to add "timeshift-launcher" to my startup applications or that it opens itself to take the snapshot.

Thanks a lot in advance,
Greetings,

**Comment by teejee2008** [comment]
There's a background job that runs once an hour and creates snapshots. It does not have a visible GUI.

timeshift-launcher starts the main application window where you can view or create snapshots manually.

**Comment by rickstaa** [comment]
Thanks a lot!
