### ISSUE TITLE
folder /var/spool

### ISSUE THREAD

**Issue by pepe12311** [teejee2008/timeshift#191]
Hi, sorry for my English.
I need to include the folder and subfolders /var/spool, but there is no way.

Is in the list of exclusions by default. I guess the problem is that by default it filters it.
I have searched the generic list to modify it but I have not found it.

Is there any way to modify the filters that come by default to delete the entry that excludes this folder?
cheers

**Comment by divanvisagie** [comment]
It looks like there is a hard coded list https://github.com/teejee2008/timeshift/blob/89be3f52572340dd55166fba1b6a7c5de6f49dc5/src/Core/Main.vala#L543

**Comment by teejee2008** [comment]
I'm sure I had a good reason for excluding /var/spool but I don't remember what that was. This will be fixed in next update.

**Comment by teejee2008** [comment]
Fix committed
