### ISSUE TITLE
Timeshift fails to work on a fresh fedora install

### ISSUE THREAD

**Issue by Overc1ocker** [teejee2008/timeshift#194]
When i try to select my root partition for fedora (/dev/sda6), it tells me it is not a system disk. How do i fix this? It is a btrfs file-system 23 GB partition

**Comment by Overc1ocker** [comment]
Update: I dont have a @ or @ home partition (anaconda does not create them automatically) I dont know how to create them.

**Comment by teejee2008** [comment]
@ and @home subvolumes are required to use Timeshift. I don't think the Fedora Installer supports this, so you will not be able to use it on Fedora.
