### ISSUE TITLE
Typing errror: "BRTFS" instead of "BTRFS"

### ISSUE THREAD

**Issue by Tanarri** [teejee2008/timeshift#196]
Hi,

in all language files (*.po) there is a typing error:

Wrong:
`msgid "BRTFS snapshots are saved on system partition. Other partitions are not supported."
`
Right:
`msgid "BTRFS snapshots are saved on system partition. Other partitions are not supported."
`

Please correct this - thanks!

Greetings
TanarRi

**Comment by Tanarri** [comment]
Same error on the wiki https://github.com/teejee2008/timeshift/wiki/Timeshift-v18.1 

I cannot edit the wiki, because I can't find a "edit" button. Is this correct?

**Comment by candrapersada** [comment]
why timeshift not opening? use Manjaro Btrfs
