### ISSUE TITLE
Missing translation in policykit

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#207]
This line is not in the translation template timeshift.pot and therefore untranslated:
https://github.com/teejee2008/timeshift/blob/master/src/share/polkit-1/actions/in.teejeetech.pkexec.timeshift.policy#L9

![Timeshift pt_BR](https://user-images.githubusercontent.com/8754997/41191531-591622e2-6bc7-11e8-84e3-36a1d5744ea6.png)

**Comment by GabrielMGitHub** [comment]
@teejee2008 
@NikoKrause 

Got corrected?

**Comment by NikoKrause** [comment]
@GabrielMGitHub 
The string is in the translation template `timeshift.pot`. 
You'll have to update your translation file against the template, finish the translation and create a PR with the updated translations here.
