### ISSUE TITLE
Non-system, non-hiDPI notifications

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/timeshift#212]
I would prefer a standard notification, rather that ones of the following - and on my hi-DPI system - tiny type.

![image](https://user-images.githubusercontent.com/9998846/41360546-e87b8f16-6f24-11e8-9cc8-cf5ed7b47522.png)

Still, might a theme be to blame?

Linux Mint 18.3
Timeshift 18.4

**Comment by teejee2008** [comment]
It's a theme issue. Timeshift calls the "notify-send" command to show the notification.

**Comment by CottonEaster** [comment]
A [Mint developer says this really does not look like a theme issue](https://github.com/linuxmint/mint-y-theme/issues/87#issuecomment-403226802).

**Comment by teejee2008** [comment]
I don't have this issue on my system and I don't have a hi-dpi display to test it. 

In any case, I'm making a normal call to notify-send. How notify-send displays the notification is not under my control. I'm closing this one.
