### ISSUE TITLE
'Users' pane: double 'exclude apps' option

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/timeshift#213]
Either by design there should be only one 'exclude apps' option, in which case the fact that I see two indicates a bug, or, if by design there are two 'exclude apps' options, then that is confusing.

![image](https://user-images.githubusercontent.com/9998846/41360628-20d5ecb2-6f25-11e8-8dd3-8d548a68f233.png)

Linux Mint 18.3
Timeshift 18.4

**Comment by clefebvre** [comment]
Fixed by https://github.com/teejee2008/timeshift/commit/f90d2427d3c5ff106062278a9b54a75be29538a5
