### ISSUE TITLE
Filters: 'Cancel' button when adding a folder does not work.

### ISSUE THREAD

**Issue by ehoffman2** [teejee2008/timeshift#225]
Minor issue...

When you configure the filters, and you click the 'Add Folders' button, you are presented with a folder selection dialog box.  At this point, the 'Cancel' button is enabled, and the 'Open' button is disabled (since no folders are selected).

If you then click one of the folder (in the folder selection dialog window), or you add a new location, and select one of the folder, the 'Open' button become enabled.

The issue is that at that point (after you clicked a folder), if you click the 'Cancel' button, the folder appear in the list, as an exclude filter.  So, effectively, the 'Cancel' button work exactly like the 'Open' button.

Expected behavior is that the folders list shall not be altered if you cancel the operation.

Regards,
Eric

**Comment by teejee2008** [comment]
Fixed in v18.6.1

**Comment by ehoffman2** [comment]
Verified, 18.6.1.

Regards,
Eric
