### ISSUE TITLE
Please merge curent translations from Launchpad

### ISSUE THREAD

**Issue by p-bo** [teejee2008/timeshift#23]
According dates of change, there on Github are older versions of some translations (eg. Czech, Brazilian Portuguese, etc.) than on launchpad translation page (https://translations.launchpad.net/timeshift/trunk/+pots/timeshift). So for example recent Linux Mint fork (at last of translations - see https://translations.launchpad.net/linuxmint/latest/+pots/timeshift/ ) is out of date.
Please merge them (also in future ;) )

Thanks :)

**Comment by teejee2008** [comment]
Translations are already merged. I have removed the translation page at https://translations.launchpad.net/timeshift/trunk/+pots/timeshift to avoid duplication of effort.
