### ISSUE TITLE
version 18.6 Home directory selected but not showing as backedup

### ISSUE THREAD

**Issue by travis5491811** [teejee2008/timeshift#259]
This is the first time i've tried to use timeshift with a luks vol (external disk) and encrypted my home directory. 

Linux Mint 19 fresh install
Timeshift 18.6
RSYNC

Problem: 
If i select include all for user directory and then start a backup. When i go to browse the directory, the user folder is there but it's empty. There are no excluded folders specified in settings 

Is this a bug or am i missing something about how the browse feature works? Is this a limitation of encrypted home directory?

**Comment by travis5491811** [comment]
man timeshift 
"No manual entry for timeshift"

**Comment by travis5491811** [comment]
Is there a way to list all directories and sub-directories being backed up?

**Comment by teejee2008** [comment]
There's a summary button in Settings > Filters that shows what is excluded. Any fike that doesn't match the filters in the Summary list will be included.

**Comment by travis5491811** [comment]
I wasn't able to resolve the issue and removed timeshift from my machine. Mainly because I also use docker containers and there are a number of people reporting issues with timeshift in machines that run docker applications. i'm going back to the dependable rsync.

I read the following:

> Docker & Containers - Docker and containerized systems are not supported. Running Timeshift on such systems will have unpredictable results. 

I didn't think that also applied to bare metal host that were using docker to run other containerized applications. Seems strange that would affect timeshift.
