### ISSUE TITLE
Sparse files

### ISSUE THREAD

**Issue by tarkah** [teejee2008/timeshift#268]
It appears sparse files are backed up in their entirety, not by how much they are actually using. I noticed this with LXDs default.img, which shows 15gb, but in reality is only using up 2gb. Everytime I did a backup, it'd be 16gb+ due to this file. I've blacklisted it for now, but doesn't rsync have support for handling sparse files?

**Comment by teejee2008** [comment]
Not sure. Need to check on this.

**Comment by glebfrank** [comment]
I'd like to sponsor this (would have saved me a couple of hours last week.) Who do I pay?

**Comment by token47** [comment]
What is the status of this? I'm using ubuntu Disco Dingo with Timeshift 19.01+ds-2 and it is still copying the files in non-sparse form. My windows qemu image is using about 20GB but it expands to more than 50GB when backing up.

**Comment by teejee2008** [comment]
Fix commited

**Comment by token47** [comment]
Thank you!
