### ISSUE TITLE
Can not install timeshift in Debian Stretch Mate

### ISSUE THREAD

**Issue by mexsudo** [teejee2008/timeshift#27]
just a FYI: both timeshift-latest dropbox links are dead
thanks

**Comment by mexsudo** [comment]
https://www.dropbox.com/s/sbadakjqnd02r6i/timeshift%202017-09-18%2007-03-03.png?dl=0

**Comment by teejee2008** [comment]
Updated links in README.md

**Comment by teejee2008** [comment]
Install libvte-2.91. It should be available on Debian 9.1

**Comment by mexsudo** [comment]
libvte-2.91 is installed, gdebi gives the error shown above

**Comment by mexsudo** [comment]
installed with timeshift-v17.2-amd64.run ... no errors reported
===
peter@debian9:~$ timeshift-launcher
timeshift-gtk: error while loading shared libraries: libvte2_90.so.9: cannot open shared object file: No such file or directory
peter@debian9:~$ su
Password: 
root@debian9:/home/peter# timeshift
timeshift: error while loading shared libraries: libvte2_90.so.9: cannot open shared object file: No such file or directory
root@debian9:/home/peter# timeshift-launcher
timeshift-gtk: error while loading shared libraries: libvte2_90.so.9: cannot open shared object file: No such file or directory
root@debian9:/home/peter#

**Comment by teejee2008** [comment]
Fixed in v17.10

**Comment by mexsudo** [comment]
Thanks. the .deb installs correctly now.
