### ISSUE TITLE
GUI Issue: Explanatory text does not fit into the window

### ISSUE THREAD

**Issue by dmitry-kabanov** [teejee2008/timeshift#278]
In the dialog "Select Snapshot Location" there is explanatory text to explain what kind of disks are supported. However, it cannot be read in full because it does not fit.
See the attached screenshot.

![screenshot from 2018-08-09 10-54-42](https://user-images.githubusercontent.com/500073/43886055-45dda822-9bc3-11e8-94a2-62614de5522a.png)

**Comment by teejee2008** [comment]
Fixed in latest commit
