### ISSUE TITLE
Timeshift Not Auto UNMOUNTING after scheduled snapshots

### ISSUE THREAD

**Issue by CyberManifest** [teejee2008/timeshift#279]
I have a SD Card that I use to make timeshift snapshots.
Normally I can access this SD Card as a user from Thunar (my file manager) especially after a reboot.
I've noticed though after a bit of time (I'm suspecting due to timeshift's scheduled auto snapshot by the hour) the SD Card is mounted as root and no longer accessible to the user in Thunar.
When I go  into timeshift, it doesn't show any active snapshots being made; so thus it has completed its tasks: (FEATURE REQUEST: Please make an indicator or notifier of when timeshift is performing an action in the background)
If I unmount and remount the device I'm able to access it again as user.
It seems or appears that Timeshift is mounting the device as root for scheduled actions but is NOT UNMOUNTING the device after completion so it can again become accessible to the user / Thunar.
If timeshift is going to auto mount a device as root, please have it unmount the device upon completion of tasks and actions: "I.E. Clean up after itself!" A user shouldn't have to be a timeshift maid.

https://imgur.com/L3M7I5H
https://imgur.com/uzgCJS1

AFTER REBOOT: https://imgur.com/KJAQft7

**Comment by teejee2008** [comment]
I prefer to keep the partition mounted on my system. But an option can be added for this.

**Comment by teejee2008** [comment]
closing duplicate
