### ISSUE TITLE
Dialog box mangled

### ISSUE THREAD

**Issue by srakitnican** [teejee2008/timeshift#28]
I've packaged Timeshift for Fedora, it runs fine mostly, except a few dialog boxes, this one appears when GUI is started without admin access. Any idea why?

![shot-2017-09-19_08-09-57](https://user-images.githubusercontent.com/13233146/30578067-42f7669e-9d12-11e7-8711-4be989368589.png)

**Comment by teejee2008** [comment]
I'll check and let you know

**Comment by Ste74** [comment]
I can confirm also in Manjaro Linux , buld today the last commit from  github ( for include in our repo )  but the gui is the same above

**Comment by teejee2008** [comment]
Fixed in latest commit
