### ISSUE TITLE
"Boot device not selected" when trying to restore a snapshot on a system with full disk encryption

### ISSUE THREAD

**Issue by igor-krupenja** [teejee2008/timeshift#280]
Steps to reproduce:
1. Install Manjaro Linux 17.1.11 in UEFI mode using default settings *except enabling full disk encryption*. This will create three partitions: root, swap and EFI. My `fdisk v-l` output:

```bash
Disk /dev/nvme0n1: 238,5 GiB, 256060514304 bytes, 500118192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 24BD641B-F706-4C3A-BBEA-77A2094BF117

Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1      4097    618497    614401   300M EFI System
/dev/nvme0n1p2    618498 481648510 481030013 229,4G Linux filesystem
/dev/nvme0n1p3 481648511 500103449  18454939   8,8G Linux filesystem


Disk /dev/mapper/luks-cf34ea3e-2eac-4506-88df-299d01ff70be: 229,4 GiB, 246285269504 bytes, 481025917 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/luks-2dbbe0fd-517d-40a4-b6d4-cb0b0f1f8f73: 8,8 GiB, 9446831616 bytes, 18450843 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

My `df -h` output:

```
Filesystem      Size  Used Avail Use% Mounted on
dev             3,9G     0  3,9G   0% /dev
run             3,9G  9,7M  3,9G   1% /run
/dev/dm-0       225G   68G  147G  32% /
tmpfs           3,9G   64M  3,8G   2% /dev/shm
tmpfs           3,9G     0  3,9G   0% /sys/fs/cgroup
tmpfs           3,9G  7,1M  3,9G   1% /tmp
/dev/nvme0n1p1  300M  408K  299M   1% /boot/efi
tmpfs           789M   20K  789M   1% /run/user/120
tmpfs           789M   15M  775M   2% /run/user/1000
```

2. Open Timeshift and configure it to use rsync snapshots saved to the system disk (i.e. nvme0n1p2):

![image](https://user-images.githubusercontent.com/26354715/43990890-b10a677c-9d6a-11e8-84f0-dadd85b5089e.png)

3. Create a snapshot either on-demand or on schedule.
4. Now try to restore the snapshot using the default settings suggested by Timeshift:

![image](https://user-images.githubusercontent.com/26354715/43990918-1c245c2a-9d6b-11e8-8130-d849f9235300.png)

This results in the "Boot device not selected"  error:

![image](https://user-images.githubusercontent.com/26354715/43991009-9c459e5e-9d6c-11e8-8313-229af3a14264.png)

**Comment by teejee2008** [comment]
Seems like an issue with nvme devices

**Comment by Fadelis** [comment]
Is there any news on this issue? I have the same one, also on manjaro with encrypted disk (nvme ssd).

**Comment by tiotrom** [comment]
Any update on this? Still happens in 2019 :D

**Comment by tiotrom** [comment]
We tested with ssd and hdd and in both cases there is this error

**Comment by teejee2008** [comment]
It expects /boot to be on a non-encypted partition. Encrypted boot is not supported.

**Comment by tiotrom** [comment]
Thank you very much for clarification.

**Comment by z4zen** [comment]
I would like to to add my story with this:

The "Boot device not selected" error gave me a big scare when I needed to restore to a previous snapshot. I did not notice big warnings or refusal to work with /boot during setup or taking snapshots, so this check does not seem to warn users before the actual restore attempt?
Unfortunately, my initial restore experiment with Timeshift was successful therefore I never considered that Timeshift may refuse to restore later on. But on the day it mattered suddenly I got the "Boot device not selected" error. /boot never was a non-encrypted partition on that system.

Luckily(?), there is a bug somewhere in the UI or the checks involved. By repeated clicking in the "Select Target Device" dialog and closing any popup "Boot device not selected" error, sometimes Timeshift comes to the opposite conclusion for the same settings and you can progress further. That must have happened in my initial test by accident. So by clicking a lot you can indeed cheat past the /boot check! Then the restore works normally and successfully (as in my initial test run).

I still don't know why this "Boot device not selected" error is in the code. I know for a fact encrypted restore with Timeshift works at least in my case once. For me this error was really unexpected program behavior. It would have made all backups made with Timeshift unusable, if I had not found out that the check does not always return the same result if you try long enough in the UI.


My suggestion would be to make the "Boot device not selected" error dialog skippable, like adding an "Ignore this warning" button and some day even remove the dialog completely.

**Comment by mr-eshua** [comment]
I have recreated the issue, but had a little bit different behavior. The setup is almost the same as issue originator had. NVMe disk is partitioned:
- /dev/nvme0n1p1 - /boot/efi (unencrypted)
- /dev/nvme0n1p2 - / (encrypted, /boot dir is there too)

Steps:
1. Started Timeshift, chose /dev/nvme0n1p2 as a source of snapshots.
2. Created first and only snapshot just after setting up.
3. Tried to restore, using Restore dialog - everything works.
4. Tried to restore again using the same settings and snapshot - got the "/boot encrypted" error. Keep getting it even after clicking many times.
5. Restarted Timeshift app, chose Restore - again everything works and restored, but only for the first time.

Looks more like a bug. The same settings give different behavior, depending on number of attempt.

Using Manjaro 18.0.4 + Timeshift 19.01.

**Comment by pheiduck** [comment]
why you would restore from a snapashot you have restored before? @mr-eshua

**Comment by DDzwiedziu** [comment]
@pheiduck If I may answer: yes, same issue still persists with 20.03. I'm having identical issues after my FS blew up and I'm trying to restore a timeshift backup.

**Comment by rokuoku** [comment]
Same here. Most of the time it works fine, but sometimes I get this error. Restarting Timeshift helps.

**Comment by 55TTKKSS** [comment]
Hy, I had the same problem, and I solved it -for my particular case-, by doing what I posted here:
https://forum.manjaro.org/t/timeshift-error-to-restore-snapshot-on-fully-encrypted-installation/74522
Not very technical stuff, but as a newbie, I hope I can help somebody.

**Comment by thunderbird-1990** [comment]
I ran into and solved this issue today, so I want to provide an explanation of why this happened. This is basically what @teejee2008 said, just slightly more detailed. Hopefully someone will find this useful (and free feel to correct me if the terms I use are inaccurate).

Let's say your main partition is encrypted, but your EFI partition is not.

You will run into this error if your /boot directory is located inside your main partition (note the [differences](https://unix.stackexchange.com/questions/384494/efi-partition-vs-boot-partition) between a EFI and a boot partition). Mostly likely, during the installation of your Linux distribution, you or the installer mounted your EFI partition to /boot/efi and installed a boot loader (e.g., GRUB) accordingly. The files required by your boot loader, however, are inside /boot which is encrypted.

The best way to use Timeshift in this case is to create a separate, unencrypted boot partition. [Here](https://docs.hytrust.com/DataControl/Admin_Guide-4.0/Content/Books/Admin-Guide/Linux-Root-Swap-Drive-Encryption/Creating-Boot-Partition-Ubuntu.htm) is a guide for Ubuntu, but all the commands should also work for other distributions. The only thing is that you probably need to mount your EFI partition after mounting the boot partition before you can install GRUB:

```bash
# make sure that /etc/fstab has the UUID of your boot partition first, see the above link
mount /boot
mkdir /boot/efi 
mount partition_EFI /boot/efi # mounts the EFI partition
# then install GRUB
```
