### ISSUE TITLE
Timeshift ignore my list of includes.

### ISSUE THREAD

**Issue by kaksych** [teejee2008/timeshift#281]
Hi. I used the Timeshift to backup the system and my second disk completely. For this I have allocated a separate HDD. The second disk was mounted as a "/work". Apparently after updating Timeshift to version 18.6.1 the program stopped backing up my working disk. In the list of excludes, the item "/work" appeared by default. I added the /work to the user include list, but the program still does not back it up. Can I somehow edit the default exclude list and remove "/work"? Or maybe there is another way to force the program to back up my second disk? Thank you.

**Comment by teejee2008** [comment]
This application is designed for protecting the operating system. It is not a data backup tool. Use DejaDup or another backup tool for this.
