### ISSUE TITLE
Why is timeshift ignoring SELinux errors on Fedora 28?

### ISSUE THREAD

**Issue by Heliosstyx** [teejee2008/timeshift#285]
In my opinion good designed software should show messages if errors occurs and give users the possibility to react. Why Timeshift does not do that? Why does Timeshift ignore SELinux errors?

**Comment by Heliosstyx** [comment]
The workaround on my Business-notbook HP 8530p is the following:

1. Start a Live-USB-Fedora-KDE session
2. Install Timeshift in this session
3. **Go into a terminal: setenforce permissive**
4. Start Timeshift
5. Select the appropriate snapshot and select "restore"
6. **Do not change any grub option!**
7. After restoring **shutdown** and start your system again. It works fine.

**Comment by Kris33** [comment]
It's a bad solution. 
You should not need to disable selinux. Install setroubleshoot and setools instead and issue `sealert -a /var/log/audit/audit.log` . 
This will give you commands to create a custom selinux policy regarding your issue.
