### ISSUE TITLE
Snapshots not marked for deletion

### ISSUE THREAD

**Issue by gderf** [teejee2008/timeshift#294]
Running Timeshift 18.6+tara on Linux Mint that was recently upgraded to Linux Mint 19 Tara.

When selecting a snapshot, then right clicking on it, then selecting "Mark for Deletion" the result should be that the selected snapshot becomes grayed out. However it remains displayed like the others - not grayed out.

The selected and marked for deletion snapshots do get deleted though.

**Comment by gderf** [comment]
I am running Linux Mint 19 Tara w/ Cinnamon desktop and Eleganse-dark
theme. I tried reverting back to the standard Cinnamon theme but it
makes no difference.

In the attached screenshot, the first snapshot in the list was marked
for deletion.

![selection_003](https://user-images.githubusercontent.com/14347747/44952036-a1c64400-ae42-11e8-81ef-e9ce2a62d35b.jpg)

**Comment by teejee2008** [comment]
It's an issue with the theme. Use a different one.

**Comment by gderf** [comment]
I tried half a dozen of the themes bundled with the distribution.  Same problem with all of them.
   On Sunday, September 2, 2018, 1:16:30 AM EDT, Tony George <notifications@github.com> wrote:  
 
 
It's an issue with the theme. Use a different one.
