### ISSUE TITLE
Computed free space is wrong

### ISSUE THREAD

**Issue by skolarianer** [teejee2008/timeshift#3]
Timeshift 17.2 shows more free space than actually available. In my case it shows 9.4GB available, but the result of `df` is only 3.1GB.

Maybe it’s related to my LUKS system:

```
$ df -h
Dateisystem                 Größe Benutzt Verf. Verw% Eingehängt auf
udev                         1,9G       0  1,9G    0% /dev
tmpfs                        384M     11M  373M    3% /run
/dev/mapper/ubuntu--vg-root  113G    104G  3,1G   98% /
tmpfs                        1,9G    109M  1,8G    6% /dev/shm
tmpfs                        5,0M    8,0K  5,0M    1% /run/lock
tmpfs                        1,9G       0  1,9G    0% /sys/fs/cgroup
/dev/sda2                    237M    125M  100M   56% /boot
/dev/sda1                    511M    3,5M  508M    1% /boot/efi
cgmfs                        100K       0  100K    0% /run/cgmanager/fs
tmpfs                        384M    152K  384M    1% /run/user/1000
```

![image](https://cloud.githubusercontent.com/assets/6286711/25556645/4f0defca-2d00-11e7-81a3-346d5bd13202.png)
![image](https://cloud.githubusercontent.com/assets/6286711/25556652/6472f950-2d00-11e7-82cd-766f1bbe172b.png)

**Comment by teejee2008** [comment]
/dev/mapper/ubuntu--vg-root  113G    104G  3,1G   98% /

Free space is simply calculated as Total - Used space.
113G - 104G = 9 GB

The free space of 3,1G reported by df seems to be incorrect.

**Comment by skolarianer** [comment]
Problem is Timeshift fills up the whole disk although backups should be suspended if available disk space is less than 1GB. I had to free disk space and now have to check carefully if enough space is still available to prevent Timeshift locking my system.

Yes, the results of `df` are strange. I found this: https://askubuntu.com/questions/249387/df-h-used-space-avail-free-space-is-less-than-the-total-size-of-home

**Comment by christophra** [comment]
I have the same issue on Linux Mint, with an ext4 file system as my backup volume. For me the available space reported by Timeshift is 100 GB smaller (on a 2 TB drive) than what is reported anywhere else. Is there maybe a missing conversion from 2^10 to 10^3 somewhere?

**Comment by skolarianer** [comment]
Be aware of reserved disk space:
https://askubuntu.com/a/249415

I assume that Timeshift doesn’t take reserved disk space into account correctly.

In my case it is the other way around. Timeshift reports more usable free disk space than there is actually left. It adds the reserved space to the free space which leads to the problem initially reported.
