### ISSUE TITLE
A cli version or installation instructions for cli only

### ISSUE THREAD

**Issue by petsam** [teejee2008/timeshift#300]
**Is your feature request related to a problem? Please describe.**
I would like to use timeshift without GUI, for an emergency restore function only to save space from extra dependencies like gtk3 and what that brings.

**Describe the solution you'd like**
It would be nice if there was a cli version, that can be installed on a minimal installation, like "timeshift-cli".
As an alternative, some instructions on achieving the same goal with the current package would be enough.

**Describe alternatives you've considered**
I was thinking of creating an AUR package with altered dependencies and installation instructions. I don't know if/how is this possible for Debian based packages, but I suspect it might be possible as well.

Thanks for your awesome utilities!

**Comment by teejee2008** [comment]
Timeshift has dependencies on GTK3 libraries so you must have that installed even if you have not installed a desktop. During installation it will install all dependencies it requires. 

Separating the codebase into 2 separate packages (with and without Gtk dependencies) involves a lot of work.

**Comment by Smugger21** [comment]
So you are saying that you are never going to make a CLI only version of this product for use in servers with no desktop?
