### ISSUE TITLE
Can we compile timeshift without GTK

### ISSUE THREAD

**Issue by Pras01123** [teejee2008/timeshift#319]
I tested the CLI based timeshift on ubuntu and would like to know if we can install just the cli based timeshift which is not dependent of GTK( I have some issue getting GTK up and running on my board)

**Comment by teejee2008** [comment]
It's not currently possible. Console and GUI versions share the same code base,  and the code base has dependencies on GTK functions.

**Comment by amlamarra** [comment]
Hi, I'd like to run timeshift on an Ubuntu Server. Is it possible yet to install without the GTK dependencies?

**Comment by wmutschl** [comment]
you can compile it from source. In src/makefile there is the option to compile app-console only, which has fewer dependencies.

**Comment by amlamarra** [comment]
I did `make app-console` but that ended up requiring all the same dependencies. I kept getting compilation errors and kept installing packages until it finally compiled. Then I just did `apt install timeshift` and I didn't need to install any dependencies for that as I already had them.
