### ISSUE TITLE
Restoring a single file from a Timeshift archive

### ISSUE THREAD

**Issue by Futureknows** [teejee2008/timeshift#320]
Is it possible to restore a single file from a Timeshift Archive? I know my sequence of backup points holds an entire volume backup as I recently started them from scratch.

**Comment by teejee2008** [comment]
Not possible through the UI. You need to copy the file manually using a file manager. Click the "Browse" toolbar button to open the snapshot folder.

**Comment by sl5net** [comment]
where to find a lost file `theFile.txt` using Linux (ubuntu) lost in a user home dicrctory (`~`)?
