### ISSUE TITLE
Separate backup schedules/jobs

### ISSUE THREAD

**Issue by virtualviolet** [teejee2008/timeshift#335]
I would like to request adding the ability to add separate backup schedules/jobs.

This way we could have a job for system and another for user home. At present I am having to use deja-dup for backing up my home which is overly simple and lacks the excellent scheduling offered by timeshift.

**Comment by teejee2008** [comment]
Timeshift is not a data backup utility. It is only meant for protecting system files. Please use Deja-Dup or similar for data backups.
