### ISSUE TITLE
Compress Snapshots Feature

### ISSUE THREAD

**Issue by setsunati** [teejee2008/timeshift#338]
**Is your feature request related to a problem? Please describe.**
Currently Snapshots are uncompressed and take lot of space. Its storing snapshots uncompressed in localhost folder. /timeshift/snapshots/date_time/localhost/

**Describe the solution you'd like**
I think it would be better to automatically compress snapshots to tar.gz when you create snapshots and or schedule to automatically create snapshots. Instead of localhost folder, /timeshift/snapshots/date_time/localhost.tar.gz would be better. Compressing it will save lot of space.

**Comment by teejee2008** [comment]
Compressing everything in tar,gz does not take advantage of hard links. If you create 20 such snapshots the total size of all the compressed snapshots will exceed the total size of hard-linked snapshots.
