### ISSUE TITLE
ZFS support supposedly?

### ISSUE THREAD

**Issue by Leviathan220** [teejee2008/timeshift#347]
**Describe the bug**
zfs devices not showing up for whatever reason

**To Reproduce**
1. Go to 'just open the wizard'
2. Click on 'rsync'
3. No ZFS drive shown

**Expected behavior**
ZFS support

**Screenshots**
![image](https://user-images.githubusercontent.com/18338698/48969991-2cdf5200-efcc-11e8-9b3c-7ee5addf9a71.png)

![image](https://user-images.githubusercontent.com/18338698/48970029-b1ca6b80-efcc-11e8-8aa8-27c962d8d27b.png)

**System:**
 - Linux Distribution Name and Version: Ubuntu 18.10
 - Desktop Ubuntu-Desktop (gnome 3.30.1)
 - Application Version v18.9.1
 - ZFS root device if this matters

**Comment by teejee2008** [comment]
ZFS is not currently supported
