### ISSUE TITLE
Support for Wayland session

### ISSUE THREAD

**Issue by Ste74** [teejee2008/timeshift#35]
Any plain for support also Wayland ? 
Build your last commit in Gnome and with X-org session ( Gnome-Xorg session ) all work fine , in Gnome wayland ( Gnome session ) the gui not work : cannot open display :0

Stefano

**Comment by Ste74** [comment]
At the moment in a wayland session i can run with this command
`xhost +SI:localuser:root && timeshift-launcher`

**Comment by teejee2008** [comment]
Fixed in v17.10

**Comment by fuelflo** [comment]
Hey, i am using Ubuntu 17.10 with wayland and i can launch timeshift-gtk as root user from the command line, but if i try it from the launcher the window doesnt open and there is no request for root pwd. From the Xorg Session however, it works.

**Comment by Ste74** [comment]
Yep seem wayland restrict again the rules to run graphical app . The only way for sure is to use pkexec with polkit rules
