### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by scporse** [teejee2008/timeshift#355]
This is more of a question than an issue as such.

I'm just trying to understand exclusion of directories from backup.

For instance; why do the default exclusions in Timeshift not exclude the entire directory, but only its contents? Eg. /dev/*  instead of just omitting the directory completely with /dev ...

Maybe this is a dumb question, but I really don't get why one would want to include empty directories in general ?

**Comment by scporse** [comment]
Any chance of getting an answer to this question?

**Comment by scporse** [comment]
Just dropping another comment on this issue in the hopes of getting an answer at some point...

**Comment by teejee2008** [comment]
There's not much difference. I prefer to exclude the contents instead of entire directory.

**Comment by GraveDigger1** [comment]
i know this is old but the op has a point if you exclude a directory not only should the contents not be backed up, but also the folder and it's sub folders shouldn't be backed up. that said i have a folder /home/gravedigger/Graves with 9 subfolder that my other drives / partitions are mounted to. when i setup timeshift and run it backs up the contents of the mounted folders just as if all that content is on the os drive when it isn't. how do i actually exclude /home/gravedigger/Graves/, or at least the contents in it's subfolders? thanks
