### ISSUE TITLE
Snapshot deletion makes no sense

### ISSUE THREAD

**Issue by Maaartinus** [teejee2008/timeshift#362]
**Describe the bug**
When I set to keep 5 daily and 5 weekly snapshots, then I want to be able to return to any of the 4 last days when the computer was used. But timeshift deletes all daily backups older than 5 days, so after not using the computer for a few days, there may be no daily backup left (except for the current state). What I described so far is a duplicate of #272, but there's another problem: Once per week two backups are needlessly made, one daily and one weekly backup. That's wasteful as they're pretty much the same. The redundant one mayn't take much space due to hardlinking, but there's still some disk and CPU overhead.

**To Reproduce**
1. Set up 5 daily and 5 weekly snapshots.
2. Use the computer for one week.
3. Observe that there are two backups having the same date.
4. Don't use the computer for another week.
5. Switch it on and wait till a daily backup gets made.
6. Observe that all but the current daily backup are gone.

**Expected behavior**
The boot snapshots are special and the following does not apply to them. Only run a single snapshot per day, even when both the daily, weekly and monthly snapshots are to be scheduled on the same day.

When there are N daily snapshots set up, make sure that the last N snapshots are kept. Similarly, when there are N weekly snapshots, make sure that there's at least one snapshot kept for each of the last N weeks. When this is not possible (as the snapshot wasn't made or was manually deleted or whatever), keep an older snapshot instead. Similarly for monthly backups.

I guess, my algorithm description is not very clear, but I hope you get what I mean. I can provide an exact algorithm when someone cares.

**System:**
- Linux 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- timeshift v18.6

**Comment by teejee2008** [comment]
Older snapshots are deleted if it is older than N days/weeks (as selected in settings window).

The previous UI showed this correctly but the meaning was as lost when the UI was updated:
![image](https://user-images.githubusercontent.com/12488854/50579050-75115000-0e67-11e9-927f-aad0df7293e4.png)

I have added a fix. Older snapshots will not be deleted if count is less than N.
