### ISSUE TITLE
Can I use btrfs with different subvolume labels (not @, @home?)

### ISSUE THREAD

**Issue by nbecker** [teejee2008/timeshift#370]
**Is your feature request related to a problem? Please describe.**

I already have a fedora system where I setup 2 subvolumes named 'root' and 'home'.  It seems timeshift is hardcoded to look for '@' and '@home'?  What do you suggest?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by teejee2008** [comment]
Other layout are not supported
