### ISSUE TITLE
Latest version does not make for Arch related distro's

### ISSUE THREAD

**Issue by bishoptf** [teejee2008/timeshift#375]
Using a Arch related rolling distro, when trying to upgrade Timeshift (aur/timeshift  18.9.1-1 -> 19.01-1) it fails.  Appears not to make if you have the latest version of vala installed which has been upgraded.

ore/Main.vala:64.23-64.37: error: The type name `AppExcludeEntry' could not be found
	public Gee.ArrayList<AppExcludeEntry> exclude_list_apps;
	                     ^^^^^^^^^^^^^^^
Core/Main.vala:528.41-528.55: error: The type name `AppExcludeEntry' could not be found
		exclude_list_apps = new Gee.ArrayList<AppExcludeEntry>();
		                                      ^^^^^^^^^^^^^^^
Gtk/ExcludeAppsBox.vala:102.4-102.18: error: The type name `AppExcludeEntry' could not be found
			AppExcludeEntry entry;
			^^^^^^^^^^^^^^^
Gtk/ExcludeAppsBox.vala:113.4-113.18: error: The type name `AppExcludeEntry' could not be found
			AppExcludeEntry entry;
			^^^^^^^^^^^^^^^
Gtk/ExcludeAppsBox.vala:126.4-126.18: error: The type name `AppExcludeEntry' could not be found
			AppExcludeEntry entry;
			^^^^^^^^^^^^^^^
Gtk/ExcludeAppsBox.vala:150.43-150.57: error: The type name `AppExcludeEntry' could not be found
		var model = new Gtk.ListStore(3, typeof(AppExcludeEntry), typeof(bool), typeof(string));
		                                        ^^^^^^^^^^^^^^^
Compilation failed: 6 error(s), 0 warning(s)
make[1]: *** [makefile:52: app-gtk] Error 1
make: *** [makefile:2: all] Error 2
/usr/bin/makepkg: line 342: logpipe: unbound variable
Error making: timeshift

Appears to make using 0.42.4 but not 0.42.5.

Thanks :)

**Comment by damian01w** [comment]
Same issue here - Its an incompatibility with vala 0.42.5.

**Comment by ndowens** [comment]
Posted a comment on AUR page for timeshift, I have fixed it, or worked around it, by 
sed -i 's:--thread:& Core/AppExcludeEntry.vala:' src/makefile

**Comment by teejee2008** [comment]
Fixed in the latest commit
