### ISSUE TITLE
[Clarification request] Backups are made incremental - according to documentation. What happens if older snapshots are deleted?

### ISSUE THREAD

**Issue by Wikinaut** [teejee2008/timeshift#379]
related: https://github.com/teejee2008/timeshift/issues/175

According to the present documentation, the snapshots are **incremental**.

The documentation and also the wiki pages are silent about what will happen if older snapshots are deleted.

Please can you clarify this?

**Comment by teejee2008** [comment]
Deleting one snapshot does not affect others. Each snapshot is a complete copy. Shared files are hard-linked between snapshots.
