### ISSUE TITLE
No Cron jobs listed even though enabled in TimeShift

### ISSUE THREAD

**Issue by UrbanNinja559** [teejee2008/timeshift#38]
I've enabled daily, hourly and boot backups in TimeShift and it doesnt run the cron job to sync.

Version v17.2

**Comment by UrbanNinja559** [comment]
Forgot to Mention I'm Running Arch Linux

**Comment by RPINerd** [comment]
You closed this without mentioning a fix? Did you get it working or just give up? lol

I'm having the same issue and it looks like others on arch are as well

**Comment by Simply-Sublime** [comment]
I ended up just setting up my own personal rsync jobs and had no need for this program.
