### ISSUE TITLE
"CRITICAL" message when timeshift --list

### ISSUE THREAD

**Issue by akerka2** [teejee2008/timeshift#386]
When I run in terminal "timeshift --list" or "timeshift --list-devices" it works, but I see in output 
CRITICAL **: 12:32:31.893: string_replace: assertion 'self != NULL' failed

1. Run in terminal "timeshift --list"

Expected behavior
Just  regular output without any "Critical"-messages

System:
 - Linux Mint 19.1 Cinnamon
 - Application Version 18.9.1

**Comment by teejee2008** [comment]
timeshift command should be run with "sudo"

**Comment by IlgazC** [comment]
I see this message while doing "auto backup when apt installs/removes/updates". It is the exact same message I guess
** (process:18664): CRITICAL **: 07:04:16.280: gee_abstract_collection_get_size: assertion 'self != NULL' failed
