### ISSUE TITLE
Desktop launcher not working in Wayland

### ISSUE THREAD

**Issue by Ste74** [teejee2008/timeshift#41]
Hi , i have build for Manjaro v17.10 but it not run from desktop launcher (wayland session) .. 
via terminal timeshift-launcher work.. Any idea how trace this ?

**Comment by Ste74** [comment]
Uhmm the command running in background but the gui not open

**Comment by Ste74** [comment]
Only if switch terminal=true i'm able to launch the app ( of course a terminal is open and i can write the password )

**Comment by teejee2008** [comment]
I'll be updating timeshift-gtk to run as normal user so that it can be used from a Wayland session. This will take some time though as the changes required are time-consuming.

**Comment by Ste74** [comment]
If you need a testing ping me ;)

**Comment by Ste74** [comment]
17.11 great :)
