### ISSUE TITLE
Timeshift will only start in "Live USB Mode"

### ISSUE THREAD

**Issue by pnewbery** [teejee2008/timeshift#425]
In a live Linux Mint 19 Tessa system where Timeshift has been running perfectly, Timeshift will now only start in "Live USB Mode (Restore Only)". Backups are no longer being made.
To Reproduce: 
- Start Timeshift.

Expected behaviour: 
- "Timeshift is Active" displayed at bottom of Timeshift GUI window. 

ScreenShot:
- ![Screenshot from 2019-05-20 13-24-49](https://user-images.githubusercontent.com/15089304/58021489-eb56dc00-7b02-11e9-8365-08403a2af617.png)

System: 
- Linux Mint 19.1 (Tessa)
- Desktop: Cinnamon
- Application Version: 18.9.1

Attempts to fix: 
- Purge & Re-install Timeshift. Reconfigure using Wizard.

Other Information: 
- Since the last successful backup, Some RAID member UUIDs have changed. (Faied disks replaced)
- Upgraded Mint from Tara to Tessa. Timeshift works fine on another Installation at Mint Tessa.

**Comment by teejee2008** [comment]
It is not able to find the device that has the root filesystem. So it assumes it is running from a Live session.

What is the output of 'lsblk --fs' and 'df -h'

**Comment by pnewbery** [comment]
Hi there, as requested:

[TimeshiftOPs.txt](https://github.com/teejee2008/timeshift/files/3241099/TimeshiftOPs.txt)

**Comment by pnewbery** [comment]
Any update on this issue??

**Comment by pnewbery** [comment]
The problem persists. Is there any update please?

**Comment by markedphillips** [comment]
I have the same issue on Ubuntu 19.10, any update?

**Comment by yaleksandr89** [comment]
I have the same issue on Ubuntu 19.10, any update?

**Comment by S0litaire** [comment]
This effects me as well.

I'm running a clean Ubuntu 19.10 using the XFS file system. :

lsblk --fs:
`NAME   FSTYPE     LABEL           UUID                                 FSAVAIL FSUSE% MOUNTPOINT
loop0  squashfs                                                              0   100% /snap/gnome-3-28-1804/91
loop1  squashfs                                                              0   100% /snap/core18/1223
loop2  squashfs                                                              0   100% /snap/gnome-calculator/501
loop3  squashfs                                                              0   100% /snap/gnome-logs/81
loop4  squashfs                                                              0   100% /snap/gtk-common-themes/1353
loop5  squashfs                                                              0   100% /snap/gnome-3-28-1804/71
loop6  squashfs                                                              0   100% /snap/core/7917
loop7  squashfs                                                              0   100% /snap/gnome-characters/317
loop8  squashfs                                                              0   100% /snap/gnome-characters/359
loop9  squashfs                                                              0   100% /snap/gnome-calculator/544
loop10 squashfs                                                              0   100% /snap/core18/1265
sda    zfs_member rpool           7687868263639767923                                 
├─sda1 vfat       rpool           6429-4D5B                             329.4M    36% /boot/efi
├─sda2 ext4       rpool           6b73f51f-5b74-4d17-9d1c-057b8907df48     33M    18% /boot/grub
├─sda3 swap       rpool           22edb54a-4f07-41db-8bd6-3588bd253ef6                [SWAP]
├─sda4 zfs_member bpool           14925277991633832545                                
└─sda5 zfs_member rpool           7687868263639767923                                 
sdb                                                                                   
├─sdb1 ntfs       System Reserved 78CEC3AECEC3634C                                    
└─sdb2 ntfs                       9CA0C973A0C95484                                    
sdc    ext4                       a487d31c-a6e2-412e-a0b2-3ca49c060781  702.7G    69% /home/bill/Media
sdd                                                                                   
└─sdd1 ext4       External        95ea76fb-231d-4644-9133-aafca6f8382c    1.1T    64% /media/bill/External
`
df -h : 
`Filesystem                                        Size  Used Avail Use% Mounted on
udev                                              9.7G     0  9.7G   0% /dev
tmpfs                                             2.0G  1.9M  2.0G   1% /run
rpool/ROOT/ubuntu_29euso                          249G  4.0G  245G   2% /
tmpfs                                             9.8G   40M  9.8G   1% /dev/shm
tmpfs                                             5.0M  8.0K  5.0M   1% /run/lock
tmpfs                                             9.8G     0  9.8G   0% /sys/fs/cgroup
bpool/BOOT/ubuntu_29euso                          1.8G  129M  1.7G   8% /boot
/dev/sda1                                         511M  182M  330M  36% /boot/efi
/dev/sda2                                          45M  8.0M   33M  20% /boot/grub
rpool/ROOT/ubuntu_29euso/var/www                  245G  128K  245G   1% /var/www
rpool/ROOT/ubuntu_29euso/var/lib                  250G  4.5G  245G   2% /var/lib
rpool/ROOT/ubuntu_29euso/var/log                  245G   34M  245G   1% /var/log
rpool/ROOT/ubuntu_29euso/srv                      245G  128K  245G   1% /srv
rpool/ROOT/ubuntu_29euso/var/snap                 245G  256K  245G   1% /var/snap
rpool/USERDATA/bill_mduvwe                        292G   47G  245G  16% /home/bill
rpool/ROOT/ubuntu_29euso/usr/local                245G   22M  245G   1% /usr/local
rpool/ROOT/ubuntu_29euso/var/mail                 245G  128K  245G   1% /var/mail
rpool/ROOT/ubuntu_29euso/var/spool                245G  3.0M  245G   1% /var/spool
rpool/USERDATA/root_mduvwe                        245G  256K  245G   1% /root
rpool/ROOT/ubuntu_29euso/var/games                245G  128K  245G   1% /var/games
rpool/ROOT/ubuntu_29euso/var/lib/AccountServices  245G  128K  245G   1% /var/lib/AccountServices
rpool/ROOT/ubuntu_29euso/var/lib/dpkg             245G   41M  245G   1% /var/lib/dpkg
rpool/ROOT/ubuntu_29euso/var/lib/apt              246G   84M  245G   1% /var/lib/apt
/dev/loop1                                         55M   55M     0 100% /snap/core18/1223
/dev/loop0                                        157M  157M     0 100% /snap/gnome-3-28-1804/91
/dev/loop2                                        4.3M  4.3M     0 100% /snap/gnome-calculator/501
rpool/ROOT/ubuntu_29euso/var/lib/NetworkManager   245G  256K  245G   1% /var/lib/NetworkManager
/dev/loop3                                        1.0M  1.0M     0 100% /snap/gnome-logs/81
/dev/loop4                                         45M   45M     0 100% /snap/gtk-common-themes/1353
/dev/loop5                                        150M  150M     0 100% /snap/gnome-3-28-1804/71
/dev/sdc                                          2.7T  1.9T  703G  74% /home/bill/Media
/dev/loop6                                         90M   90M     0 100% /snap/core/7917
/dev/loop7                                         15M   15M     0 100% /snap/gnome-characters/317
/dev/loop8                                         15M   15M     0 100% /snap/gnome-characters/359
/dev/loop9                                        4.3M  4.3M     0 100% /snap/gnome-calculator/544
tmpfs                                             2.0G   64K  2.0G   1% /run/user/1000
/dev/sdd1                                         3.6T  2.3T  1.2T  68% /media/bill/External
/dev/loop10                                        55M   55M     0 100% /snap/core18/1265
`

**Comment by saudia-cmuetc** [comment]
Same for me, also running 19.10, and using ZFS root/boot.  Maybe it's ZFS?

**Comment by pnewbery** [comment]
Hi there, from the above posts you can see that there are at least 3 other people with this same issue, so it is not a one-off. is there any chance that you could devote some resource into finding a solution to this issue? I am happy to provide any other diagnostic output which may be required.

**Comment by pnewbery** [comment]
This seems to be a problem with the latest version of Timeshift and RAID5 and dmraid configurations as per this [Mint Forum post]([url](url)). I downloaded the 64bit version (from the link in the forum post; 32bit is also available) and installed Timeshift 19 in place of 19.1 and Timeshift now functions again. You need to completely remove the program with sudo apt purge timeshift before reinstalling with the Gdebi package installer. You also need to "Blacklist" Timeshift in the Update Manager so that it is not updated to 19.1 again.

**Comment by pnewbery** [comment]
Sorry, this is the [correct link](https://forums.linuxmint.com/viewtopic.php?f=47&t=284258&p=1629349&hilit=timeshift+raid+blacklist#p1629349) to the Mint Forum post:

**Comment by tikizondo94** [comment]
I'm running into this problem with Ubuntu 20.04. I've tried every version back to 18.9.1. Still only starts in live USB mode. ZFS file system. Any ideas?

**Comment by wil2197** [comment]
I'm running into a similar issue here. Ubuntu Mate 20.04. ZFS File System. I'm starting to wonder if Timeshift doesn't play nicely with ZFS.

https://pastebin.com/XSYWd7VR

**Comment by hcarrega** [comment]
same here with same settings ubuntu 20.04 zfs

**Comment by guttermonk** [comment]
Same issue here. Like @teejee2008 suggested, I think it's unable to find the device that has the root filesystem.

I'm running ZFS on Ubuntu 18.04 LTS.

**Comment by fleamour** [comment]
Snap!

ZFS as root using an SD card on ThinkPad X200.

**Comment by JayMoseleyTX** [comment]
I can join in as I am seeing this on a new install of Linux Mint 20 installed on a zfs root system. Output from df, inxi and lsblk attached. I tried purging and re-installing Timeshift from the deb supplied above; the results were the same. The version of Timeshift installed along with my Linux Mint 20 xfce was 20.03.2 ulyana.

[df.txt](https://github.com/teejee2008/timeshift/files/5234981/df.txt)
[inxi.txt](https://github.com/teejee2008/timeshift/files/5234982/inxi.txt)
[lsblk.txt](https://github.com/teejee2008/timeshift/files/5234983/lsblk.txt)

**Comment by SaFi2266** [comment]
Hello, 
According to the above discussion .. it appears that "TimeShift" does not support create snapshot on ubuntu with zfs **or** am I wrong? 
Would you please someone correct me if I am so 
BR

**Comment by JayMoseleyTX** [comment]
I received zero responses to my question posted here in September. I also posted my question on the Linux Mint forum and is relevant to you as Linux Mint is based on Ubuntu. On the Linux Mint forum, I received a single reply stating that TimeShift does not list zfs as a supported file system. So I gave up on installing my new installation on zfs and went back to ext4. Maybe at some future time it will be possible to install the root system on zfs, but I will not attempt it until all the applications I need to use will fully support zfs.

**Comment by S0litaire** [comment]
Think the way Ubuntu implemented XFS/ZFS makes it hard for Timeshift to recognise ZFS partitions. I also gave up using them a while ago.

**Comment by LiterallyJohnny** [comment]
Anybody here have any good Timeshift alternatives? I am getting the same issue.

**Comment by yuriw** [comment]
on ubuntu zfs same problem, any resolution to it ?

**Comment by LiterallyJohnny** [comment]
I don't know of a better solution, but it resolved itself when I
reinstalled the OS.

**Comment by yuriw** [comment]
@LiterallyJohnny 
I can't reinstall the OS.  My goal is to use Timeshift (unfortunately it's not working :( ) to do a snapshot of my ubuntu system running on `zfs` and then replace the disk with `ext4` and restore.

If I do fresh install I don't need Timeshift then.
(may try rsync )

**Comment by yuriw** [comment]
Can Timeshift do snapshot of the remote system ?

**Comment by g33kz4su** [comment]
same issue timeshift stuck on recovery mode can't find sub-volumes on btrfs. It was devastating to see my last resort to save my work fail. I am trying new backup solutions, but this was the best. Looking forward to next release.

**Comment by plasticbomb1986** [comment]
> It is not able to find the device that has the root filesystem. So it assumes it is running from a Live session.
> 
> What is the output of 'lsblk --fs' and 'df -h'

In the application window: 

Live USB mode (Restore only)
Device not found: UUID='8423d8c4-1e86-4e2b-b04b-d306589116d5'

> lsblk --fs
> NAME        FSTYPE FSVER LABEL       UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
> sda                                                                                      
> ├─sda1      vfat   FAT32             E5F0-29EE                               418M    19% /boot
> ├─sda2      ext4   1.0               7cf9064c-9a43-4b2d-8378-f45544227ed7    3.7G    89% /
> └─sda3      ext4   1.0               5bcfca6a-637f-4369-99b7-be1a42976111   52.6G    65% /home
> sdb                                                                                      
> ├─sdb1      ntfs         Recovery    54E65C22E65C06A0                                    
> ├─sdb2      vfat   FAT32             745F-C6B9                                           
> ├─sdb3                                                                                   
> └─sdb4      ntfs         System      ACFE641DFE63DDD8                                    
> sdc                                                                                      
> ├─sdc1      vfat   FAT32             9CB8-6C2C                                           
> ├─sdc2      ext4   1.0               817909e1-ea8e-4325-b081-34d91f24c905                
> └─sdc3      ext4   1.0               f18c3093-528f-43b9-8e00-1ba9638cd691                
> sdd                                                                                      
> └─sdd1      ntfs         6TB         F61AB6A11AB65E75                        2.9G   100% /mnt/6TB
> sde                                                                                      
> └─sde1      ext4   1.0               8423d8c4-1e86-4e2b-b04b-d306589116d5   77.5G    86% /mnt/GamesSSD1TB
> sdf                                                                                      
> └─sdf1      ext4   1.0   GamesSSD2TB 38aa7e82-2410-4eb7-9ad4-2fc74221670b   89.9G    90% /mnt/GamesSSD2TB
> sdg                                                                                      
> └─sdg1      ntfs         Adatok      01D4C73A1CCFFB90                      236.2G    75% /mnt/Adatok
> nvme1n1                                                                                  
> ├─nvme1n1p1 swap   1                 3053cc38-8fe6-4742-9fa0-d39410cc99c4                [SWAP]
> ├─nvme1n1p2 ext4   1.0   M2SSD1TB    bb73675d-09a6-405b-87dd-6b2eff71e98e  414.2G    43% /mnt/M2SSD1TB
> └─nvme1n1p3 ntfs         SCDATA      4A8654D722832523                                    
> nvme0n1                                                                                  
> └─nvme0n1p2 ext4   1.0   M2SSD       8445a670-d7e6-4d74-8f92-9231ef5b13e7  271.1G    38% /mnt/M2SSDEXT4



> df -h
> Filesystem      Size  Used Avail Use% Mounted on
> dev              16G   76K   16G   1% /dev
> run              16G  2.0M   16G   1% /run
> /dev/sda2        59G   52G  3.7G  94% /
> tmpfs            16G  104M   16G   1% /dev/shm
> /dev/nvme1n1p2  802G  347G  415G  46% /mnt/M2SSD1TB
> /dev/nvme0n1p2  469G  177G  272G  40% /mnt/M2SSDEXT4
> /dev/sdf1       1.8T  1.7T   90G  95% /mnt/GamesSSD2TB
> /dev/sde1       916G  792G   78G  92% /mnt/GamesSSD1TB
> /dev/sda3       175G  113G   53G  69% /home
> /dev/sda1       514M   96M  419M  19% /boot
> /dev/sdd1       5.5T  5.5T  2.9G 100% /mnt/6TB
> /dev/sdg1       932G  696G  237G  75% /mnt/Adatok
> tmpfs            16G  5.5M   16G   1% /tmp
> tmpfs           3.2G  104K  3.2G   1% /run/user/1000

System is ArchLinux, Kernel 5.12.5, systemd-boot setup.

**Comment by drlobes** [comment]
Exactly the same problem here as the user above, running Arch, wanted to do a backup before upgrading to kernel 5.12.6. It was working fine before, I didn't do any incriminating changes to my system, have no idea at all why this is happening.

**Comment by pikakolendo02** [comment]
> Exactly the same problem here as the user above, running Arch, wanted to do a backup before upgrading to kernel 5.12.6. It was working fine before, I didn't do any incriminating changes to my system, have no idea at all why this is happening.

I also failed to run it in Arch these days.
```sudo timeshift --list-devices
E: ts: Failed to get partition list.
```

**Comment by tvlpirb** [comment]
I'm experiencing the exact same issue on Arch, it cannot get the partition list. I also have not made any incriminating changes that I can think of.

**Comment by tvlpirb** [comment]
> > Exactly the same problem here as the user above, running Arch, wanted to do a backup before upgrading to kernel 5.12.6. It was working fine before, I didn't do any incriminating changes to my system, have no idea at all why this is happening.
> 
> I also failed to run it in Arch these days.
> 
> ```
> sudo timeshift --list-devices
> E: ts: Failed to get partition list.
> ```

I'm also running this on Arch and experiencing the exact same issue.

**Comment by pikakolendo02** [comment]
https://github.com/teejee2008/timeshift/issues/753#issuecomment-854493305
The patch is here.
