### ISSUE TITLE
Question: why include /var/log by default

### ISSUE THREAD

**Issue by erikfdev** [teejee2008/timeshift#430]
Is there a reason why the contents of /var/log is saved in the snapshots?
What are the arguments against excluding the /var/log? Would the snapshot then become unrecoverable?

On my Linux Mint 19 journald is creating 200MB of logs every day. SO I would like to exclude it.

**Comment by teejee2008** [comment]
/var/log is not critical. You can exclude it by adding an exclude entry. Most people prefer to keep it so it's included by default.
