### ISSUE TITLE
What is the meaning of "unshared" for BTRFS snapshots?

### ISSUE THREAD

**Issue by UnicornsOnLSD** [teejee2008/timeshift#432]
Sorry for cluttering the issues page, but what does "unshared" mean in the BRTFS menu? Also, is there a list of the tags?

Thanks!

**Comment by teejee2008** [comment]
This is the size of data in snapshot that is unique to that snapshot. Deleting the snapshot will free up this space.

You can see available tags by moving the mouse over the Tag column in list
