### ISSUE TITLE
timeshift does not recognize mounted ext3 partition in VeraCrypt encrypted drive

### ISSUE THREAD

**Issue by rdiaz02** [teejee2008/timeshift#434]
**Describe the bug**

timeshift does not recognize mounted ext3 partition in VeraCrypt encrypted drive

***Details***
I haven external disk (the M3_Portable_Seagate in screenshot below) where I have encrypted the first (and only) partition with VeraCrypt. That is decrypted and mounted as ext3 (e.g., in `/media/veracrypt1`).  I can read and write from/to it, and I can use e.g., BackInTime.  But timeshift does not recognize it. Even after scanning, it only shows the disk, not the partition in the disk.

Note: I have encrypted the whole partition (i.e., this is not an encrypted file as a container ---which is another mode of operation of VeraCrypt---, this is a whole partition, much like if I had used LUKS).

**Expected behavior**
Timeshift should show the mounted device (as it does with LUKS-encrypted devices) and allow to use it for snapshots (as shown below, where dm-1 or nvme0n1p1, partitions in an encrypted LUKS, are offered as location for snapshot).

***Output from df***
```  
Filesystem                 Size     Used     Avail   Use%   Mounted on
/dev/mapper/veracrypt1     xyzT    xyz G    xyzT   u%       /media/veracrypt1 
```

***Output from blkid***
```
/dev/mapper/veracrypt1: UUID="xyz"  SEC_TYPE="ext2"   TYPE="ext3"
```

***Screenshot from timeshift***

![timeshift-veracrypt3](https://user-images.githubusercontent.com/1688611/60755890-842fb100-9ff6-11e9-8a4a-4515abf95dcf.png)

**System:**
- Ubuntu 19.04
 - timeshift version: 

**Others**
This issue has been reported in the Linux Mint forums: https://forums.linuxmint.com/viewtopic.php?t=282794
(but no solution has been given)

**Comment by teejee2008** [comment]
VeraCrypt encrypted drives are not supported

**Comment by rdiaz02** [comment]
Thanks for the clarification. That is too bad. Sorry if I missed it in the docs (yes, VeraCrypt is not listed in https://github.com/teejee2008/timeshift#supported-system-configurations, but I thought that did not apply to locations of snapshots).

If I want to use VeraCrypt to store the snapshots, I guess I will need to create the snapshots in the local disk and cp the `/timeshift` directory to the VeraCrypt encrypted drive. To restore (online, offline, or from a Live CD/USB) I'd need then to move the snapshots from the VeraCrypt drive to a supported drive. Is this correct? Any other options?

**Comment by teejee2008** [comment]
Copying the snapshot to another location is not recommended. After copying, the hardlinked files will get duplicated and each snapshot will occupy the full size wasting disk space.

**Comment by rdiaz02** [comment]
OK, thanks. I am out of luck then. (I have to use VeraCrypt, since I need to be able to easily open the encrypted drive in other OSs, for other stuff backed-up in that drive).

**Comment by frademacher** [comment]
Hi everybody,

Sorry for commenting on a closed issue, but maybe my comment is helpful for other users of VeraCrypt, who want to store timeshift backups on external HDDs with an encrypted partition.

While ``timeshift-gtk`` does not recognize external HDDs mounted via VeraCrypt itself, the ``timeshift`` CLI just works as expected. For example, when issuing the command ``sudo timeshift --create --snapshot-device /dev/dm-0`` (with /dev/dm-0 representing the external HDD mounted with VeraCrypt), timeshift stores the backup on the external, encrypted HDD.

In my case it is also possible to use ``timeshift-gtk`` when the UUID of the VeraCrypt-encrypted HDD (determined via ``sudo blkid`` and the result for the ``/dev/mapper/veracrypt1`` entry) is configured as the "backup_device_uuid" in the ``timeshift.json`` config file. However, this "solution" is quite cumbersome when timeshift backups shall be stored on multiple external HDDs with then different UUIDs.

Both CLI and GUI "workarounds" work for me on a Linux Mint 19.3 system with timeshift v19.08, VeraCrypt 1.24-Hotfix1, and an encrypted, external ext4 HDD.

**Comment by rdiaz02** [comment]
Thanks!
