### ISSUE TITLE
[Feature Request] Exclude package caches

### ISSUE THREAD

**Issue by Justinzobel** [teejee2008/timeshift#437]
**Is your feature request related to a problem? Please describe.**
Not in relation to a problem, but to conserve data Timeshift could determine the distribution easily and exclude the apt, eopkg, rpm package caches.

**Describe the solution you'd like**
Include by default package caches in the exclude list.

**Describe alternatives you've considered**
Users can add them manually but most average users wouldn't know where they're kept.

**Additional context**
None.

**Comment by teejee2008** [comment]
Added in the latest commit
