### ISSUE TITLE
Timeshift does not honour the time setting of my locale

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [teejee2008/timeshift#443]
**Describe the bug**
Timeshift displays dates in American format or something like it. For, Timeshift displays dates thusly: year month day-of-month, e.g. 2019-07-22. I use - and my system uses - the British format, whereby the day of month precedes the date (and the year comes last, as indeed I believe it does in the US format). Example: 22-07-2019. That Timeshift does not honour locale makes it confusing for users.

**To Reproduce**
1. Have system locale set to UK.
2. See how Timeshift displays dates.

**Expected behavior**
Timeshift should honour the locale such that, in my case, in dates, the month comes *before* the day.

**Screenshots**

![image](https://user-images.githubusercontent.com/47056543/62000324-227dd680-b0cc-11e9-8c50-4af51a62d465.png)

**System:**
 - Linux Distribution Name and Version: [e.g. Ubuntu 16.04] Mint 19.1
 - Desktop [e.g. MATE, XFCE] Cinnamon
 - Application Version [e.g. v18.8] 19.01

**Comment by teejee2008** [comment]
New option is added to Settings to change the format
