### ISSUE TITLE
BTRFS snapshot fails only on creation

### ISSUE THREAD

**Issue by al2me6** [teejee2008/timeshift#444]
**Describe the bug**
Despite the wizard allowing me to enable BTRFS snapshots on a correctly configured disk, actually attempting to create a snapshot results in the "unsupported subvolume layout" error message.

**To Reproduce**
1. Configure subvolume layout as listed below
2. Enable BTRFS backup with all default options
3. Click create

**Expected behavior**
Creates a new snapshot successfully.

**Screenshots**
Disk layout:
```
$ sudo btrfs sub list /
ID 257 gen 2966 top level 5 path @
ID 258 gen 2966 top level 5 path @home
ID 261 gen 2960 top level 257 path var/lib/portables
ID 262 gen 2960 top level 257 path var/lib/machines
ID 355 gen 920 top level 257 path swap
```
Note that there is a `swap` subvolume mounted under `/swap` for swapfile support.
Debug log: https://pastebin.com/MYV3Ph9G

**System:**
 - Linux Distribution Name and Version: Arch Linux
 - Desktop KDE
 - Application Version v19.1
 - Kernel: 5.2.5

**Comment by teejee2008** [comment]
Post the contents of your /etc/fstab file

**Comment by al2me6** [comment]
@teejee2008 

```
$ cat /etc/fstab
# Static information about the filesystems.
# See fstab(5) for details.

# <file system>                             <dir>           <type>      <options>                       <dump>  <pass>
UUID=B83F-CE4E                              /efi            vfat        defaults,errors=remount-ro      0       2
UUID=4569aace-6770-42a5-ba87-b79763180264   /               btrfs       defaults,noatime,subvol=@       0       0
UUID=4569aace-6770-42a5-ba87-b79763180264   /home           btrfs       defaults,noatime,subvol=@home   0       0
UUID=30EE499BEE495A6C                       /mnt/windows    ntfs        defaults,ro                     0       0
UUID=5545DE5115D264F7                       /mnt/data       ntfs        defaults,windows_names          0       0
/swap/swapfile                              none            swap        defaults,pri=0                  0       0
```

**Comment by al2me6** [comment]
Well, it seems to have somehow fixed itself without me touching anything.

**Comment by CiriousJoker** [comment]
Same issue here and it didn't fix itself
