### ISSUE TITLE
Not possible to merge files into my own repositories

### ISSUE THREAD

**Issue by French77** [teejee2008/timeshift#448]
**Describe the bug**
Not possible to merge files into my own repositories

**To Reproduce**
Compare
compare across forks
3. Conflicting files
debian/changelog
src/Utility/Gtk/DonationWindow.vala

**Expected behavior**
Able to merge
These branches can be automatically merged

**Screenshots**
![Screenshot](https://i.imgur.com/LjnPhcW.png"Screenshot") 

**System:**
 
- Linux Mint Tina 19.2

- Cinnamon

- 4.2.3

**Comment by teejee2008** [comment]
Fix the conflict and merge it. Why open an issue here?

**Comment by French77** [comment]
Oke sorry for open this issue it's solved  by now
