### ISSUE TITLE
Strings missing in (even updated) translation template

### ISSUE THREAD

**Issue by p-bo** [teejee2008/timeshift#451]
In .pot template, there is missing string "Help", which is present in application (see screenshot below)

1. Go to Settings
2. See string Help there
3. Try to find it in timeshift.pot - it isn't there

**Expected behavior**
String Help, which is present in application, is present in translation template, thus translatable.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/12208593/62657763-87a4b800-b967-11e9-824d-5a8747f9ccc4.png)

**System:**
 - distribution independent
 - Desktop [GNOME Shell, LXQt]
 - Application version: 19.01, bug still present in latest source code in git

**Comment by p-bo** [comment]
The same for string "part" in restore dialog:
![obrazek](https://user-images.githubusercontent.com/12208593/62729271-eaf12180-ba1d-11e9-9278-6e523e80f797.png)

**Comment by p-bo** [comment]
Updatint timeshift.pot with makepot script doesn't heped.

**Comment by teejee2008** [comment]
Added "Help" to template and PO files.

"part" is a code returned by **lsblk** command. It cannot be translated here.
