### ISSUE TITLE
devel ppa referenced instead of release one in README.md

### ISSUE THREAD

**Issue by p-bo** [teejee2008/timeshift#454]
In installation instructions for Ubuntu, there is linked devel ppa
https://launchpad.net/~teejee2008/+archive/ubuntu/ppa
But there exists release ppa
https://launchpad.net/~teejee2008/+archive/ubuntu/timeshift
So which one to use to install latest stable, not development version of Timeshift please?

Thanks :)

**Comment by teejee2008** [comment]
Use the following. This PPA has only timeshift. 
https://launchpad.net/~teejee2008/+archive/ubuntu/timeshift

Previous PPA is being maintained temporarily for people who are still using it.
