### ISSUE TITLE
Raspberry Pi Support?

### ISSUE THREAD

**Issue by riahc3** [teejee2008/timeshift#462]
Is Timeshift supported for Raspberry Pi?

**Comment by jdrch** [comment]
No it isn't.

**Comment by riahc3** [comment]
Well, Im asking for a package for Raspberry Pi.

**Comment by teejee2008** [comment]
Timeshift is only for Linux distributions that use GRUB2 bootloader. It will not work with Raspberry Pi and other SBCs which have their own bootloaders.
