### ISSUE TITLE
Add Timeshift as a grub option or as an option within the recovery environment

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [teejee2008/timeshift#471]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to recover my system when it won't boot properly and I have to use a live USB. 

**Describe the solution you'd like**
Running a version of Timeshift from grub or from the recovery environment offered by grub (I mean the nomodeset, sort of safe-mode that gets installed when one installs a kernel) - that would be great.

**Describe alternatives you've considered**
Well at present I have to run a Live USB. At least I can do that and at least Timeshift deals with the non-booted system well (I've booted from USB, but Timeshift doesn't try to restore to that - well, once I've mounted my real disk, anyway).

**Additional context**

Thank you for your work.

**Comment by webshadow** [comment]
i would love to have that feature

**Comment by LinuxOnTheDesktop** [comment]
> [T]he tracker is checked once a year when the app is being updated.

([Source](https://github.com/linuxmint/timeshift).) I made this feature request - and someone seconded it - more than two years ago.

**Comment by teejee2008** [comment]
Sorry, it is outside the scope of this project.

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the response. I will find somewhere in Mint's bug tracker to file the request.
