### ISSUE TITLE
Cannot find .run installers for 19.08.1, no instructions for building from source

### ISSUE THREAD

**Issue by vk5ztv** [teejee2008/timeshift#473]
I want to install timeshift 19.08.1 (latest release) on openSUSE Tumbleweed but there are no links to the .run installers for the latest version, nor can I find instructions on how to build from source. 

Is it possible to install the latest version on anything other than debian-based distro's?

**Comment by teejee2008** [comment]
Support has been dropped for the .run installers.
Please ask the maintainers of your Linux distribution (openSUSE) to package it for your distro.
