### ISSUE TITLE
How does Timeshift handle interrupted backups

### ISSUE THREAD

**Issue by doogie544** [teejee2008/timeshift#484]
What happens if the computer is shut down in the middle of a running snapshot?

Will the snapshot be resumed on the next run of Timeshift, be restarted and replaced or just be a broken snapshot, and if broken how does that affect any future snapshots that try to link to the broken snapshot.

There seems to be no notification that Timeshift is running(no notification icon) so it would very easy to shut down the computer in the middle of a snapshot. There is also the more remote possibility of the system crashing in the middle of the snapshot.

Will Timeshift recover gracefully in either of those instances?
(I did try to search the documentation  for this answer but there seems to be no mention of it)

**Comment by PankajVerma8** [comment]
I've had similar issues.. a couple of times I had to press CTRL+C during a snapshot creation. 
What I've noticed is when creating a new backup manually after the new snapshot is created, Timeshift automatically removes the unfinished backups. 
And the same should be the case for a snapshot that was unfinished when you turned your computer off (even if forcibly by pressing the power button). 
Maybe you haven't noticed till now, but try creating a backup in the terminal, and add --verbose to see all the processes, it will show you the part where it removes the unfinished backups/snapshots.

**Comment by doogie544** [comment]
Thank you.  I assumed that it had some method for handling failed/interrupted backups but as I could find nothing in the docs I wanted to make sure that I didn't have to possibility of having a string of backups in the future based on a broken backup due to a shutdown.

**Comment by tethragon** [comment]
I use GUI timeshift. Since I don't know when a snapshot occurs (there are no notifications), I was wondering what happens if I run a system-update during a running snapshot. How timeshift will be able to tell which files are pre-update and post-update in order to create a working snapshot?

**Comment by GraveDigger1** [comment]
i'm with @tethragon

**Comment by tethragon** [comment]
Linux Mint just offered me the solution!!! There is a new Linux Mint applet called "Timeshift Spy" that notifies the user when a snapshot is being made! Brilliant!!! I don't know if this applet is available to other distros.

![25de350d9af241d04f019be544acf21a9f07d3a5](https://user-images.githubusercontent.com/39238674/80734617-1b32a000-8b18-11ea-85e2-d2c77210a001.jpeg)

**Comment by SecretAgentAgentX** [comment]
> Linux Mint just offered me the solution!!! There is a new Linux Mint applet called "Timeshift Spy" that notifies the user when a snapshot is being made! Brilliant!!! I don't know if this applet is available to other distros.
> 
> ![25de350d9af241d04f019be544acf21a9f07d3a5](https://user-images.githubusercontent.com/39238674/80734617-1b32a000-8b18-11ea-85e2-d2c77210a001.jpeg)

Nice find, maybe someone can port it to AUR for Arch and Arch based distros since the flaw of not being notified of when snapshots are done doesn't seem to be being addressed by the Timeshift dev(s). Next someone needs to come up with a tool to fix the flaw of not being able to schedule snapshots.
