### ISSUE TITLE
Build failing with vala 0.46.1

### ISSUE THREAD

**Issue by skaendo** [teejee2008/timeshift#485]
**Describe the bug**
Build failing with vala 0.46.1

**Entire build log**
cd src; make all
make[1]: Entering directory '/tmp/current/slackrepo.yN70eW/build_timeshift/timeshift-19.08.1/src'
#timeshift-gtk
valac -X -D'GETTEXT_PACKAGE="timeshift"' \
	--Xcc="-lm" --Xcc="-O3" -D VTE_291 -D GTK3_18  \
	Core/*.vala Gtk/*.vala Utility/*.vala Utility/Gtk/*.vala \
	-o timeshift-gtk \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix \
	--pkg gee-0.8 --pkg json-glib-1.0 \
	--pkg gtk+-3.0 --pkg vte-2.91 
Utility/AsyncTask.vala:76.2-76.17: error: Creation method of abstract class cannot be public.
	public AsyncTask(){
	^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
make[1]: *** [makefile:52: app-gtk] Error 1
make[1]: Leaving directory '/tmp/current/slackrepo.yN70eW/build_timeshift/timeshift-19.08.1/src'
make: *** [makefile:2: all] Error 2

**System:**
Slackware64-current
Xfce Desktop
Timeshift-19.08.1

**Comment by rammie** [comment]
Should be fixed now that this PR has landed - https://github.com/teejee2008/timeshift/pull/476

**Comment by skaendo** [comment]
I missed that. Thanks!
