### ISSUE TITLE
Write to directory other than specified when that directory is not available

### ISSUE THREAD

**Issue by PyGeek03** [teejee2008/timeshift#5]
I'm not sure if this is a bug or a feature, but this has been bothering me for a while. I set timeshift up to backup my / directory to a directory on an external hard drive. When the external hard drive is not connected, I expect the schedule snapshot feature to just fail silently, but instead, it creates /timeshift and writes the snapshot to that directory. When I block it from writing to / , it goes and creates /home/Download/timeshift and does the same thing. If this is a feature, I understand that backups are really important, and I understand why the application does that, but I think there should be an opt-in option so that the user can expect what would happen instead of being taken by surprise.

**Comment by teejee2008** [comment]
This is not a feature. If the device is not connected it should exit with an error. It does not attempt to save snapshots to / or any other directory. 

Please provide the log file where it writes to /home/Download. Logs files are stored in /var/logs/timeshift

**Comment by PyGeek03** [comment]
Well it created two snapshots in /home/Download. These are the log files for those two snapshots: https://gist.github.com/PyGeek03/f61c78670a5cd91e08f28a5ccc0d3ea7

**Comment by teejee2008** [comment]
Fixed in v17.10
