### ISSUE TITLE
PPA isn't found

### ISSUE THREAD

**Issue by q2dg** [teejee2008/timeshift#51]
Instructions to install Ubuntu package using add-apt-repository fail

**Comment by teejee2008** [comment]
Please post the exact commands you are running along with output messages.

**Comment by q2dg** [comment]
Oooh, I've done it again and now it just works! (wtf??)
Maybe it was a temporal failure on PPA servers,... I don't know.
In any case, sorry for the inconveniences and thanks for your response.
Cheers
