### ISSUE TITLE
Add ZFS Support

### ISSUE THREAD

**Issue by liberodark** [teejee2008/timeshift#529]
Hi,

Now have ubuntu is adding ZFS that would great to add support for snapshot.

Best Regards

**Comment by ptrk64** [comment]
Anyone working on this?? If so let me know if I can help.

If not I'll try to find some time time to create a branch and start working on ZFS support :)

Cheers,
Peter

**Comment by tethragon** [comment]
Since ZFS has an internal snapshot function, why timeshift developers should work on a request like this? Wouldn't be a waste of time?

**Comment by Vijay5189** [comment]
Ubuntu 20.04 on ZFS root , timeshift running in live mode

**Comment by thebiggestmac** [comment]
Why do you need ZFS support in Timeshift? ZFS has its own snapshots which are much better than Timeshift's ones.

**Comment by mvhecht** [comment]
Because some people want to host the backup of their non-ZFS root drives on a ZFS drive.

**Comment by guttermonk** [comment]
I would like to host the backup of my ZFS root drives on a non-ZFS drive. In other words, periodically and automatically backup my ZFS root system files to my NAS.

**Comment by dmshimself** [comment]
Yes Ihave the same type of rig with the same requirement.  Popping the snapshots out to a ZFS dataset would be very useful

**Comment by zparihar** [comment]
+1 

I'd like to have a ZFS feature inside Timeshift.  Right now I have things setup in a Cron Job, but I'd like to have a GUI tool to do this!

**Comment by TruncatedDinosour** [comment]
+1

should definally be added

**Comment by almereyda** [comment]
Meanwhile, I've heard people have good experiences with `zrepl`.

- https://github.com/zrepl/zrepl

via

- https://github.com/stars/almereyda?q=zfs

**Comment by dmshimself** [comment]
As a sort of workaround, I created a zvol, formatted as ext4 and timeshift picks it up fine and puts snapshots there.

**Comment by teejee2008** [comment]
Rsync snapshots can be saved on a ZFS-formatted disk if your Linux system is installed on a non-ZFS file system.

However, if your system is installed on ZFS then you won't be able to create snapshots. ZFS has a weird disk layout that is not supported.

![image](https://user-images.githubusercontent.com/12488854/134761098-de36dcd9-689a-4fa4-a3c8-51345fef9957.png)
