### ISSUE TITLE
Question: can I safely remove files (e.g. /tmp/*) from snapshot(backup) directory?

### ISSUE THREAD

**Issue by mwoz123** [teejee2008/timeshift#531]
**Describe the question**
I know I can't exclude files/folder from backup. 
But will Timeshift crash on rolback if I'd removed unnecesary (e.g. tmp) files from snapshot/backup directory? 
Will it be successfully restored after such changes? 

**TLDR:**
Q: Can I safely remove files/folders from backup directory?

**To Reproduce**
Steps to reproduce the question:
1. Create backup of current system ( this should store backup in ` /mnt/timeshift/backup//timeshift-btrfs/snapshots`)
2. Go to backup folder (`/mnt/timeshift/backup/timeshift-btrfs/snapshots/<time-of-snapshot>`) 
3. Remove some least improtant files e.g.: `/tmp/chromium-browser-caches/*`
4. Will I be able to succesfully restore such modifed backup or will it crash? 

**System:**
 - Linux Distribution Name and Version: ubuntu 18.04 lts
 - Desktop: gnomeshell
 - Application Version: 19.08

**Comment by teejee2008** [comment]
Yes, you can delete files from the snapshot
