### ISSUE TITLE
Support S3 Backups

### ISSUE THREAD

**Issue by datumbox** [teejee2008/timeshift#54]
Are there any plans for supporting S3 backups? Deja Dup, the default backup solution for Ubuntu, has recently [announced](https://wiki.gnome.org/Apps/DejaDup/Clouds) that they deprecated the support of many cloud providers (the S3 option is still supported but hidden for the time being). I think this opens the possibility for Timeshift to attact more ex-Dejadup users.

**Comment by teejee2008** [comment]
Timeshift snapshots use hard-links which is not supported by cloud storage file systems. Hence there is no way to move the snapshots to cloud storage. You can copy the snapshots folders manually, but the hard-links will break and snapshots will take up a huge amount of space. There's no workaround for this.
