### ISSUE TITLE
Settings dialog deletes existing backups without confimation

### ISSUE THREAD

**Issue by pvojnisek** [teejee2008/timeshift#541]
**Describe the bug**
If you already have backups the settings dialog can easily deletes them accidentaly.

**To Reproduce**
1. Already have some backups (in RSYNC)
2. Click on Settings
3. Change Snapshot type (any direction between RSYNC and BTRFS)
4. Close the dialog (not with OK)
5. All your previous backups have gone.

**Expected behavior**
Cancelling possibility would be recommended

**System:**
 - Linux Distribution Name and Version: [Mint 19.3]
 - Desktop [Cinnamon 4.4]
 - Application Version [e.g. v19.08]

System:    Host: peter-Inspiron-N5110 Kernel: 4.15.0-72-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.4.6 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Portable System: Dell product: Inspiron N5110 v: N/A serial: <filter> 
           Mobo: Dell model: 0HVRTT v: A06 serial: <filter> BIOS: Dell v: A06 date: 05/26/2011 
Battery:   ID-1: BAT0 charge: 48.8 Wh condition: 48.3/48.8 Wh (99%) model: DELL 7XFJJA2 status: Full 
CPU:       Topology: Quad Core model: Intel Core i7-2630QM bits: 64 type: MT MCP arch: Sandy Bridge rev: 7 L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31928 
           Speed: 950 MHz min/max: 800/2900 MHz Core speeds (MHz): 1: 800 2: 797 3: 798 4: 798 5: 798 6: 814 7: 798 8: 798 
Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics vendor: Dell driver: i915 v: kernel 
           bus ID: 00:02.0 
           Device-2: NVIDIA GF108M [GeForce GT 525M] vendor: Dell driver: nouveau v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.19.6 driver: modesetting,nouveau unloaded: fbdev,vesa resolution: 1366x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel Sandybridge Mobile v: 3.3 Mesa 19.0.8 direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Device-2: NVIDIA GF108 High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k4.15.0-72-generic 
Network:   Device-1: Realtek RTL810xE PCI Express Fast Ethernet vendor: Dell driver: r8169 v: 2.3LK-NAPI port: d000 
           bus ID: 05:00.0 
           IF: enp5s0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros AR9285 Wireless Network Adapter vendor: Dell driver: ath9k v: kernel port: d000 
           bus ID: 09:00.0 
           IF: wlp9s0 state: up mac: <filter> 
           Device-3: Atheros AR3011 Bluetooth type: USB driver: btusb bus ID: 1-1.4:8 
           IF-ID-1: docker0 state: up speed: N/A duplex: N/A mac: <filter> 
           IF-ID-2: vethbd7e9c5 state: up speed: 10000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 1.04 TiB used: 242.59 GiB (22.8%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB 
           ID-2: /dev/sdb vendor: Samsung model: HM641JI size: 596.17 GiB 
Partition: ID-1: / size: 349.02 GiB used: 153.92 GiB (44.1%) fs: ext4 dev: /dev/sda4 
           ID-2: swap-1 size: 7.63 GiB used: 424.0 MiB (5.4%) fs: swap dev: /dev/sda3 
Sensors:   System Temperatures: cpu: 58.0 C mobo: N/A gpu: nouveau temp: 54 C 
           Fan Speeds (RPM): cpu: 0 
Info:      Processes: 366 Uptime: 1h 37m Memory: 7.70 GiB used: 3.56 GiB (46.3%) Init: systemd runlevel: 5 Compilers: 
           gcc: 7.4.0 Shell: bash v: 4.4.20 inxi: 3.0.32

**Comment by Maaartinus** [comment]
I think, they're not deleted, just the location changes and they therefore don't get listed. I'm not sure, as without BTRFS I can't *really* test it. Note that deleting backups takes a pretty long time (at least when RSYNC is selected).

**Comment by teejee2008** [comment]
Snapshots are **not** deleted when you select BTRFS or RSYNC from settings. 

If you switch back to BTRFS or RSYNC and select the same snapshot device again, the main window will display the snapshots.
