### ISSUE TITLE
Cant choose snapshot type BTRFS on / btrfs and /home ext4 on Kali Linux

### ISSUE THREAD

**Issue by oldman20** [teejee2008/timeshift#547]
ops, my root system is BTRFS, but /home is ext4, so want to using timeshift, i must reinstall all system to BTRFS: / and /home? tired hic
but homepage https://github.com/teejee2008/timeshift say
BTRFS volumes must have an Ubuntu-type layout with @ and @home subvolumes. Other layouts are not supported. Systems having the @ subvolume and having /home on a non-BTRFS partition are also supported.
why i cant using timeshift snapshot with BTRFS mode, it's say:
BTRFS Tools Not Found
The 'btrfs' commands is not available on your system. Install the 'btrfs-tools' package and try again.
Then i try install btrfs-tools and got error:
$ sudo apt install btrfs-tools
[sudo] password for chuctran: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package btrfs-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'btrfs-tools' has no installation candidate
![Screenshot from 2020-01-27 20-55-33](https://user-images.githubusercontent.com/39668756/73180193-6919bf80-4147-11ea-8f7e-40e7b6af52fb.png)

**Comment by teejee2008** [comment]
**btrfs-tools** is now **btrfs-progs** in newer releases of Ubuntu. Install **btrfs-progs**

**Comment by oldman20** [comment]
> **btrfs-tools** is now **btrfs-progs** in newer releases of Ubuntu. Install **btrfs-progs**

thanks, i installed it! But still problem in question above, please explain more clearly, sir?
