### ISSUE TITLE
bootable ?

### ISSUE THREAD

**Issue by aiamuzz** [teejee2008/timeshift#55]
Hi,

I had briefly tried superduper on my hackintosh, liked the idea of backing up of the entire system partition and the best part being the backed up partition being bootable. Is the same function possible with timeshift ? I would certainly like to backup my entire system partition and yet have it bootable. makes life so much easier by booting into the backed up partition and restoring it to the original system partition.

Any possibility of you accommodating such a feature(bootable backup partition) in your software ?

PS : i know i can currently backup the entire partition through gparted. A superduper like functionality on our Linux machines would be great.

thanks.

**Comment by aiamuzz** [comment]
Hi,

"Docker & Containers - Docker and containerized systems are not supported. Running Timeshift on such systems will have unpredictable results. "

does this mean timeshift currently will not work as expected on Deepin OS ?
deepin OS has docker.

thanks.

**Comment by teejee2008** [comment]
It's not supported. You may run into issues.

**Comment by aiamuzz** [comment]
thanks ... uninstalled ...
