### ISSUE TITLE
Timeshift mistakenly deletes snapshots of the other OS-es on multi-boot system

### ISSUE THREAD

**Issue by MXarko** [teejee2008/timeshift#552]
I have three Debian-based systems installed on the same HDD, sharing the same swap partition, every has its own separate home and root partition: Mint, Debian and MX. I consider MX the main one, so I assigned the greatest home partition to it. And I configured Timeshift in every of the OS-es to use MX's home partition for saving snapshots, daily, and to keep three of them (per OS).

I would expect that Timeshift in every OS, when it's running, maintains the snapshots in the way to add a new one when the time is and to delete the fourth oldest of that OS, and not to touch snapshots of the other OS-es.

But I find that Timeshift from every system deletes snapshots of the other ones, probably counting all of them together and saving only set amount of them all taken together. So, for example, if I run every of those OS-es long enough, thus allowing Timeshift in every of them to make snapshots, and for the next three days I run only one and the same OS, it day by day deletes old snapshots not only its own but of the other two as well, so in the end there will be only snapshots of that OS remaining, until I start other OS-es again.

I consider that a critical bug.

**Comment by teejee2008** [comment]
This is the normal bahaviour. Timeshift is not designed to store snapshots of multiple systems on the same backup partition.
