### ISSUE TITLE
How to disable timeshift checks at boot?

### ISSUE THREAD

**Issue by Hukuta** [teejee2008/timeshift#554]
I'm using timeshift on linux mint, have enabled scheduled daily snapshots, but i want to configure manually when timeshift should check snapshots. I found that snapshots works without my user logged-in. And i don't see any cronjobs for root or other users.  
How i can disable timeshift startup at boot? to move this into my cronjobs or user login event.

**Comment by teejee2008** [comment]
Script is located in /etc/cron.d/timeshift-hourly
This runs as root every hour. To configure manually, disable the automatic snapshots in Timeshift.
