### ISSUE TITLE
The GUI does not detect btrfs-inside-LVM layout

### ISSUE THREAD

**Issue by wmutschl** [teejee2008/timeshift#585]
**Note:** This application is provided "as-is" without support or warranty. If you need help with issues, consider [making a donation](https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&item_name=Timeshift+Donation) to support the development.

**Describe the bug**
I have installed POP!_OS manually and created
- a LUKS partition with a volume group and a logical volume containing my root with BTRFS
- I have then created two subvolumes @ and @home and moved the files accordingly
- Now when I run timeshift, it does not detect my BTRFS filesystem, even though it is there and I have the Ubuntu layout (see attached screenshots with the layout and error). Also note that /mnt/timeshift/backup is correctly pointing to the subvolid=5 of my system.

**Expected behavior**
I would like to be able to use timeshift on this system.

**Screenshots**
![btrfs-bug](https://user-images.githubusercontent.com/36013296/79560653-3f1dcc80-80a8-11ea-8f2b-a79fd25fc0ab.png)

**System:**
 - Linux Distribution Name and Version: POP!_OS 19.10

**Comment by wmutschl** [comment]
Actually, it works for some reason anyways ... I click on my drive (which I know has btrfs) and set up the settings, and I am able to run timeshift from the GUI just fine. So might be a bug in the first page of the settings.
Here are some gifs:
![settings](https://user-images.githubusercontent.com/36013296/79722427-56e19480-82e4-11ea-8ed4-9e6d61944e16.gif)

![runs](https://user-images.githubusercontent.com/36013296/79722446-5e08a280-82e4-11ea-868b-5c9418ec1376.gif)

**Comment by metal450** [comment]
I can confirm this behavior. When first setting up Timeshift I thought it wasn't going to work on my system - until I realized I could just ignore the error message, & it creates/sees btrfs snapshots just fine.
