### ISSUE TITLE
Not enough disk space (<141.4TB)

### ISSUE THREAD

**Issue by jonathan-realman** [teejee2008/timeshift#589]
**Note:** This application is provided "as-is" without support or warranty. If you need help with issues, consider [making a donation](https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&item_name=Timeshift+Donation) to support the development.

**Describe the bug**
When I try to take a Snapshot or set the application up I get a message that the space need would be above 140TB dispite that being more than 50 time the space on my machine
sda      8:0    0  59.6G  0 disk
├─sda1   8:1    0   477M  0 part /boot
└─sda2   8:2    0  59.2G  0 part /
sdb      8:16   0 931.5G  0 disk
└─sdb1   8:17   0 931.5G  0 part /home/jonathan/.local (excluded in the snapshot)
sdc      8:32   0 931.5G  0 disk
└─sdc1   8:33   0 931.5G  0 part /run/timeshift/backup
sdd      8:48   0 116.5G  0 disk
├─sdd1   8:49   0   100G  0 part /home
└─sdd2   8:50   0  16.5G  0 part [SWAP]

**Screenshots**
![2020-04-21_08-59-40_screenshot](https://user-images.githubusercontent.com/43113264/79837231-64188500-83b1-11ea-9e0a-49a3ccd88146.png)
[Warning] Deleted invalid lock
App config loaded: /etc/timeshift.json

(timeshift-gtk:25411): GLib-GIO-CRITICAL **: 09:18:38.838: g_file_get_path: assertion 'G_IS_FILE (file)' failed

** (timeshift-gtk:25411): CRITICAL **: 09:18:38.838: tee_jee_file_system_path_combine: assertion 'path1 != NULL' failed

** (timeshift-gtk:25411): CRITICAL **: 09:18:38.838: tee_jee_file_system_dir_exists: assertion 'dir_path != NULL' failed

/dev/sdc1 is mounted at: /run/timeshift/backup, options: rw,relatime

**System:**
 - Linux Distribution Name and Version: Arch Linux Rolling
 - Desktop MATE+i3
 - Application Version v20.03

**Comment by Lampwick** [comment]
I have the same issue. Also on Arch with timeshift 20.03

**Comment by jonathan-realman** [comment]
> I have the same issue. Also on Arch with timeshift 20.03

with exactly the same amount of stroge?

**Comment by Lampwick** [comment]
sda1 - 1.0TB - Timeshift destination
sda2 - 3.0TB - (Not to be backed up)
sdb1 - 21GB - /var
sdb2 - 3.0TB - /home (Not to be backed up)
sdc1 - 536MB - /boot
sdc2 - 512GB - /

I get the same, "Not enough disk space (<141.4TB)", message.

**Comment by nnleaf** [comment]
I have the same issue. I tried deleting a bunch of files to make room, reduced my drive to just 30gb with a 200gb drive for backup, but it still gives me the 'Not enough disk space (<140.8 TB)' error. 

I'm on Arch Linux and there was a recent update with Timeshift, so I'm guessing it has something to do with that.

**Comment by Flygrounder** [comment]
Same here with timeshift 20.03 on Arch. Tried even excluding` /**` , but nothing has changed.

**Comment by mannp** [comment]
Getting the same on arch. Swapped to a larger disk but have the same issue. Also getting this on the new 1tb drive. All was working great until the latest update.

> 
> Synching files with rsync...
> **193.57**% complete (00:00:00 remaining)

**Comment by Flygrounder** [comment]
I have noticed, that I also have #588 issue as well. I have a hypothesis, that it is related to this issue. If timeshift has problems with filters maybe it does not see default filters like /run/* /dev/* etc. It can lead to an infinite recursion, which cause such a huge estimated backup size. 
@jonathan-realman @Lampwick @nnleaf @mannp do you have this issue as well?

**Comment by nnleaf** [comment]
Hey everyone, I think I found the problem.

It seems most people with problems are running Arch, and I saw a post [here](https://www.reddit.com/r/archlinux/comments/gaefzl/watch_out_for_backup_issues_with_dhcpcd_90/) about a dhcpcd's >9.0 update. It seems to mount some system directories in `/var/lib/dhcpcd/` so excluding that folder might be the solution!

I've excluded it from Timeshift and the error dissappears, it also allows me to create a snapshot and it seems to be running without any odd errors like #591  or #590 . I will update in the morning, as I'm creating a fresh backup and it will take a few hours. 

As it does exclude the dhcpcd folder, I'm not sure if there is anything important there that I would need if I needed to do a system restore, would the better solution be to downgrade dhcpcd to 8.x until a more official solution is found?

**Comment by Lampwick** [comment]
I can confirm excluding /var/lib/dhcpd/ fixed it for me too.
Not sure if the folder is necessary for system restore though.

**Comment by johncparr** [comment]
I have found that by disabling and stopping dhcpcd I could get timeshift working again. I then installed networkmanager and switched over to it for networking and I seem to have a permanent workaround/fix

**Comment by nnleaf** [comment]
Wanted to give an update. Excluding the folder worked, but I simply removed dhcpcd and used networkmanager itself. I guess with dhcpcd's changes made to 9.0, Timeshift will have to exclude that folder by default or give out a warning. 

Thanks for everyone's help, glad to be using Timeshift again - I even made a pacman hook to run a snapshot before updates if anyone wants to [check it out](https://github.com/nnleaf/timeshift-hook) because timeshift is such a great tool.

**Comment by UltraBlackLinux** [comment]
Same issue here - 140,8 TB....

**Comment by UltraBlackLinux** [comment]
Same issue here - 140,8 TB.... 
But fixed! Thank you nnleaf!

**Comment by JimDeadlock** [comment]
It's not a fix, it's a workaround. Just saying.

**Comment by gardotd426** [comment]
Yeah I also have this issue on vanilla Arch, what's weird is that it doesn't occur on Manjaro. And I run Unstable Branch of Manjaro, and the dhcpcd package versions are the same. So it's not something that dhcpcd did. Though, Manjaro actually provides a repo prebuilt package in the official repos, instead of only an AUR package, so maybe they patched it, like they've patched Pacman to allow database files larger than 25MB.

**Comment by NavySaint** [comment]
Can anyone confirm that a full system restore works properly even after excluding the aforementioned folder?

**Comment by gardotd426** [comment]
Yes.

**Comment by teejee2008** [comment]
"/var/lib/dhcpd/" has been added to list of default filters

**Comment by biohazard13** [comment]
bug still present, fortunately i found this thread

**Comment by Alzg3852** [comment]
unfortunately, problem is still not solved even after filtering out  '/var/lib/dhcpd'.

**Comment by shmu26** [comment]
I started having this issue on Ubuntu 21.10
I excluded
```
/var/lib/dhcpcd/**
/mnt/**
```
but it didn't help
