### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by alcalpcr** [teejee2008/timeshift#592]
When is it available for Ubuntu 20.04?

    apt-add-repository -y ppa:teejee2008/ppa
    apt install timeshift
    E: The repository "http://ppa.launchpad.net/teejee2008/ppa/ubuntu focal Release" does not have a Release file.

Thanks in advance

**Comment by diversen** [comment]
I don't know if you are looking for a special version, but I did not have to add a ppa repo. I could just do a:

sudo aptitude install timeshift

**Comment by alcalpcr** [comment]
thanks
