### ISSUE TITLE
Closedown problems 

### ISSUE THREAD

**Issue by R7914T** [teejee2008/timeshift#61]
I tried to follow some instructions about changing my Gnome 16.04 system. I changed my mind and used Timeshift to restore to a stable system. That worked except I can not get gnome to power off as it reboots at the end of the power off procedure instead of turning the power off. This was not a problem I had prior to the restore and so  I suspect the problem arose because of the way TS has restored the system. All I did was restore the incremental backup that was most close to the time of the changes I had wrongly made to the system.

Is  there anything I can do about restoring my computer's  ability to close down via power off.

**Comment by teejee2008** [comment]
Timeshift replaces all system files with files from snapshot. It is likely that the shutdown issue was present when the snapshot was created. Try restoring an even earlier snapshot which does not have the issue.
