### ISSUE TITLE
No Boot Backups | Ubuntu

### ISSUE THREAD

**Issue by UltraBlackLinux** [teejee2008/timeshift#613]
**Describe the bug**
Even though the checkbox is checked, Ubuntu wont create a boot backup. I also noticed, there is no Timeshift service - should there be one? (Sry Im new to Ubuntu - using Arch all time)

**To Reproduce**
1. Have Ubuntu
2. Select Boot Backups
3. Reboot.

**Expected behavior**
Do a Backup

**System:**
 - Linux Distribution Ubuntu 18.4.4 LTS
 - Desktop Gnome
 - Application Version 20.03

**Comment by wmutschl** [comment]
Hi,
Timeshift runs as a hourly cron service, see /etc/cron.d/hourly.

Regarding backup of boot, are you using rsync or btrfs? Either way some more information on your partition layout would help to get grasp the root of your problem.

**Comment by UltraBlackLinux** [comment]
Sorry I forgot - rsync. 
Ubuntu on ext4 SSD
Backs up to ext4 HDD

**Comment by UltraBlackLinux** [comment]
Hm it seem to have fixed, nvm..
