### ISSUE TITLE
Comment option in GUI

### ISSUE THREAD

**Issue by D33M0N** [teejee2008/timeshift#621]
I would love to be able to add comments when creating manual snapshot and not go into CLI to do it.
Even better, if I could add or modify comment on already existing snapshot.

**Comment by jeffkowalke** [comment]
I came here to post the same request.  This would be super helpful!

**Comment by teejee2008** [comment]
You can click and type comments in the Comments column of GUI

**Comment by D33M0N** [comment]
Really? Obviously the UI isn't intuitive enough to even realize it's an option.
I did try this before by right clicking (to open some kind of menu to edit the comment), which obviously didn't work. Never even though left click would work.
