### ISSUE TITLE
Add option to include complete /home

### ISSUE THREAD

**Issue by Bleuzen** [teejee2008/timeshift#65]
Hi, it would be nice, if there would be an option that includes all users homes // excludes nothing in /home.
So that we can add a new user and it's home will get backuped.

**Comment by Bleuzen** [comment]
@teejee2008 Hey :D

**Comment by teejee2008** [comment]
New user's home directory are excluded by default. You need to include their home directory explicitly from the Users tab in Settings.

Problem with including home directory by default is that it will also be restored when you restore a snapshot. The user will end up losing data without being aware of it. For this reason the home directory needs to be explicitly included by the user.

**Comment by Bleuzen** [comment]
@teejee2008 
This would be ok for me. I need full system backups, with everything, including all users data!
You could make a new option for this, but it should not be default, but at least an option.

(Anyway, wouldn't it be possible with rsync to restore the backup while leaving already existing files?)

**Comment by changchichung** [comment]
I have same issue here.  I want to reset the client`s environment as I delivery to customer, include the home directory. but now there`s no option to backup /home , hope there will be an option to do so.
