### ISSUE TITLE
Wrong perzentage values

### ISSUE THREAD

**Issue by LeSnake04** [teejee2008/timeshift#654]
The percentage calculated from timeshift in is completely wrong on my system. This also happens on another pc with the same OS

**Expected behavior**
Show correct values

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47243761/95330419-d66e1a80-08a8-11eb-8035-ee96d055aa56.png)

**System:**
 - Linux Distribution Name and Version: [e.g. Ubuntu 16.04] EndeavourOS (Arch based)
 - Desktop [e.g. MATE, XFCE] XFCE
 - Application Version [e.g. v18.8] 20.03

**Comment by teejee2008** [comment]
It is not possible to show an accurate percentage without slowing down the snapshot creation. The size will have to be re-estimated before taking the snapshot which will take a few minutes.

The percentage that is displayed is just an estimate based on the size of previous snapshot. The new snapshot is almost twice the size of the previous one, hence the percentage is above 200%.
