### ISSUE TITLE
Timeshift 20.03-1 freezes my laptop except my cursor when I try to run it.

### ISSUE THREAD

**Issue by Mattiperson** [teejee2008/timeshift#656]
**Bug:**
When I try to run the Timeshift app my entire system freezes except my cursor.

**To Reproduce:**
1. Launch with Rofi, Dmenu or anything like that.

**Expected behavior:**
For the app to open normally.

**Screenshots:**
Can't take screenshots since everything freezes.

**System:**
 - Arch Linux 2020.10.01
 - Qtile
 - 20.03-1

**Comment by prophet6250** [comment]
I tried running it with rofi, it worked as expected for me. I really think this is more of a Qtile issue, don't you think?

**Comment by Mattiperson** [comment]
> I tried running it with rofi, it worked as expected for me. I really think this is more of a Qtile issue, don't you think?

Yeah it might be. If it is sorry if I wasted anyone's time. Didn't really expect replies on this ancient thing.

**Comment by prophet6250** [comment]
> > I tried running it with rofi, it worked as expected for me. I really think this is more of a Qtile issue, don't you think?
> 
> Yeah it might be. If it is sorry if I wasted anyone's time. Didn't really expect replies on this ancient thing.

so, would you care to close this issue if its solved?
