### ISSUE TITLE
Enhancement suggestion - compression

### ISSUE THREAD

**Issue by carlbeech** [teejee2008/timeshift#66]
Hi

Is it possible to use compressed copies of the snapshot files, rather than simply copying full-size files? So that the files in the snapshot directory retain all the same attributes as the original, but are for example zipped?

Admittedly, on binary files it may not make a huge difference, but there's a significant number of text files in a linux system and they would benefit from holding the zipped version...

Hope that helps..

Cheers

Carl.

**Comment by teejee2008** [comment]
Adding compression will introduce additional complexity. For example, you won't be able to copy files from the backup location without using Timeshift or other tools to decompress the files. With the current design, backups can be browsed with any file manager, and files and folders can be copied from snapshots without any additional steps.

To save space, you can save the backups to a partition with ext4 or btrfs filesystem. These filesystems can compress files transparently without affecting performance.

[https://btrfs.wiki.kernel.org/index.php/Compression](https://btrfs.wiki.kernel.org/index.php/Compression
)
