### ISSUE TITLE
timeshift runs deprecated gvfs-trash utility

### ISSUE THREAD

**Issue by melizasw** [teejee2008/timeshift#661]
[Debian bug #969773](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969773)

gvfs-trash was superseded by gio in 2015 and removed from upstream GNOME
in 2018. It is currently still available in the gvfs-bin package as a
Debian-specific addition, but we want to remove it before Debian 11.

The best way to send files to the trash is to use an appropriate platform
API, such as GLib's g_file_trash() or g_file_trash_async(). timeshift
is written in Vala, a language specifically designed for GLib-based
libraries, so there is really no reason to be using an external
command-line utility for this.

**Comment by melizasw** [comment]
Added pull request to change from gvfs-trash to trash() from gio-2.0

**Comment by teejee2008** [comment]
This function was not being used and has been removed

**Comment by teejee2008** [comment]
A lot of unused code has been removed in recent commits
