### ISSUE TITLE
timeshift makes dangerous shell-injection-based calls to external commands

### ISSUE THREAD

**Issue by melizasw** [teejee2008/timeshift#662]
[Debian bug #969774](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969774)

timeshift seems to make frequent use of this pattern:

			string cmd = "realpath '%s'".printf(escape_single_quote(filePath2));
			Process.spawn_command_line_sync(cmd, out output);

This is both dangerous and inefficient. It's dangerous because if
escape_single_quote() is not implemented correctly, or is not called every
time an external command is used, then this tool will be susceptible to
shell-injection attacks. It's inefficient because every time a command is
run like this, it is run via a new instance of the sh(1) shell.

Where a function can be implemented by calling platform APIs, please do
that. For example, canonicalize_file_name() in glibc does the equivalent of
calling realpath(1) without needing any external processes at all.

Where an external command is absolutely necessary (for example to call
out to rsync), please use APIs based on an array of command-line arguments,
for example GLib.SubprocessLauncher.spawnv() or GLib.Process.spawn_sync().

**Comment by teejee2008** [comment]
This particular function was not being used and has been removed.

These functions do not operate on user-supplied data. This pattern is no different than a Python script that calls os.system() to execute a command, or a shell script that executes a system command. GLib functions are already used wherever possible, except in some cases where it is used for convenience, or where a system command is better suited for the task.

Please submit a PR for any specific cases that you wish to replace with a platform API call.
