### ISSUE TITLE
Bug 1: Filter

### ISSUE THREAD

**Issue by Golddouble** [teejee2008/timeshift#666]
**Describe the bug**
When editing in filter tab, you will not find the new entries in the summary list after.

**To Reproduce**
1. start timeshift
2. select "settings"
3. go to the tab "filter"
4. press the "add" button
5. type in something like "/home/user/Kubily/"
6. check the "+" option for this new entry
7. press the summary button
-> You will not find the new entry in the summary list.
Workaround:
8. close the window
9. select "settings"
10. go to the tab "filter"
11. press the summary button
-> It's now in the summary

**Expected behavior**
My expectation is, that the new entry is in the summary list after step 7.

**System:**
 - Linux Distribution Name and Version: MX Linux 19.2 (Debian 10 based)
 - Desktop: XFCE
 - Application Version: 19.01

Edit:
What a pity. I have just seen that my report was 7 hours late, because 7 hours ago a new release came out.  :-(

**Comment by teejee2008** [comment]
Fixed in the latest commit

**Comment by Golddouble** [comment]
Thank you.
