### ISSUE TITLE
aborted snapshots: is it secure just to delete the folder?

### ISSUE THREAD

**Issue by Golddouble** [teejee2008/timeshift#667]
RSYNC mode: When we abort a running snapshot before it is complete, then we have not entry in the snapshot list in the GUI. But we can find a folder in "/timeshift/snapshots/2020-XX-XX_XXXX" of this aborted snapshot. Is it secure just to delete this folder? Or would we broke anything this way?

Thank you.

**Comment by teejee2008** [comment]
It can be deleted.

**Comment by Golddouble** [comment]
Thank you. 
Does this only work as long as I have not made a valid snapshot after the abort? Or does it still work if I have already made 2 valid snapshots after that? Isn't it then too late, to delete the folder with the aborted backup?
