### ISSUE TITLE
Aparent storage leak on interrupted snapshots

### ISSUE THREAD

**Issue by ricab** [teejee2008/timeshift#67]
I interrupted the first snapshot I tried to create, because I had forgotten something; then I was able to create 2 snapshots normally and the GUI only lists those. But a folder still exists for the first interrupted snapshot in /timeshift/snapshots, using ~500MB in this case.

**Comment by teejee2008** [comment]
Incomplete snapshots get deleted when the hourly job runs

**Comment by ricab** [comment]
Sorry for the late reply. Scheduled jobs are optional. If one uses on-demand snapshots only, the leaked storage is apparently not recovered. I would say that is an issue. Up to you to choose what to do, but IMO the ideal would be to have some cancellation (and perhaps failure) hook to clean-up.
