### ISSUE TITLE
Filters are not saved in GUI

### ISSUE THREAD

**Issue by Lastique** [teejee2008/timeshift#691]
**Describe the bug**

The Timeshift GUI does not save filters added by user.

**To Reproduce**

1. Open the settings window.
2. Go to the Filters tab.
3. Add a filter: click Add, type a filter (e.g. "/home/*/.ccache"), click Ok.
4. Click Ok to close the settings window.
5. Open the settings window again and go to the Filters tab. The created filter is not present in the list.

This reproduces with different filters, inside /home and outside, inclusive or exclusive.

**Expected behavior**

The created filters should be saved and applied during operation.

**System:**

 - Kubuntu 20.10
 - KDE
 - Timeshift 20.03+ds-2

**Comment by Golddouble** [comment]
Should be solved with the latest version:
https://github.com/teejee2008/timeshift/releases/tag/v20.11.1
https://github.com/teejee2008/timeshift/issues/666
https://github.com/teejee2008/timeshift/issues/668

**Comment by Lastique** [comment]
I see, thanks.
