### ISSUE TITLE
timeshift is re-enabling btrfs quota? btrfs snapshot delete causes processes doing IO to hang for 1-5 minutes

### ISSUE THREAD

**Issue by ptandler** [teejee2008/timeshift#697]
I must admit, I'm not 100% sure, so this is somehow more a question than a bug report:
(Is there a support forum for timeshift where these questions would fit better?)

As I haven't looked into the sources yet:
- does timeshift (re-)enable btrfs quota? (maybe when checking for snapshots to delete)
- when are snapshot deletes scheduled? Can this be tweaked? e.g. just delete them once a day if on btrfs?

Background:

I use timeshift on a btrfs partition since about 6 month. I sometime experience that some processes (My current hypothesis is: all that do some disc IO) hang from time to time for 1 to 5 minutes. That's annoying.

I've been hunting this for a while now and found that btrfs-transaction seems to be causing it. The btrfs-transaction process has very high CPU for 1-5 minutes and all processes resume as soon as btrfs-transaction terminates.

Today, I talked to one of the btrfs developers and he pointed me at the btrfs snapshop delete operations: "I do daily snapshots.  I have machines where a **snapshot delete can take a full hour**"

So today I changed the timeshift settings and disabled hourly snapshots. I'll see if this fixes this issue.

And a quote about btrfs quota: "oh I forgot about quota.  That's probably where all your CPU is going" and "(IIRC it has to rebuild the quota data from scratch in that case?) **quota is not on my "btrfs features that work"** list"

To conclude:

- if timeshift is enabling quota on btrfs I think this should be avoided until btrfs quota is more robust
- timeshift should have an improved scheduling of snapshot deletes on btrfs

**Comment by ptandler** [comment]
I just had a first look at the source. Seems like SnapshotRepo.vala > auto_remove() is a good place to start looking ...
Who calls this when?

How can I configure timeshift to write more of the log_msg() stuff to syslog (or somewhere else)?

**Comment by twoktwok** [comment]
I too have experienced serious slow-downs with btrfs-quota enabled; [see Issue #680](https://github.com/teejee2008/timeshift/issues/680).
Disabling quota system-wide helped get rid of this freezing but sadly shows some other weird behavior (described in the link).

As a workaround I run a .service at shutdown that deletes any "leftover" (defective) snapshots. With hourly snapshots you're probably better off with a hook or a cronjob.

For reference, here's a one-liner that removes any directory in the snapshot path that doesn't contain a @-folder.
`for dir in /run/timeshift/backup/timeshift-btrfs/snapshots/*/ ; do (cd $dir && [ ! -d './@' ] && rm -rf $dir); done`

---

_does timeshift (re-)enable btrfs quota?_

It seems so. That's why I disabled it for the system 
`sudo btrfs quota disable /`

**Comment by ptandler** [comment]
I just found the place: in[Main.vala:3850](https://github.com/teejee2008/timeshift/blob/master/src/Core/Main.vala) there is `ok = enable_subvolume_quotas();` executed. There seems to be an option`btrfs_use_qgroup` to disable this.

**Comment by ptandler** [comment]
well, I should read first before I write ;-)

> I too have experienced serious slow-downs with btrfs-quota enabled; [see Issue #680](https://github.com/teejee2008/timeshift/issues/680).
> Disabling quota system-wide helped get rid of this freezing but sadly shows some other weird behavior (described in the link).
That's really reads like what I am experiencing.

However, it seems to work fine for most users, I guess. There seem to be some circumstances when btrfs quota and snapshop delete doesn't work well (yet).

> As a workaround I run a .service at shutdown that deletes any "leftover" (defective) snapshots. With hourly snapshots you're probably better off with a hook or a cronjob.
> 
> For reference, here's a one-liner that removes any directory in the snapshot path that doesn't contain a @-folder.
> `for dir in /run/timeshift/backup/timeshift-btrfs/snapshots/*/ ; do (cd $dir && [ ! -d './@' ] && rm -rf $dir); done`

so this fixes the broken delete and removes the dirs with only info.json left?

> _does timeshift (re-)enable btrfs quota?_
> 
> It seems so. That's why I disabled it for the system
> `sudo btrfs quota disable /`

Now I also found the option in the settings dialog ... ;-) And disabled it.

I would really like to understand why @teejee2008 has marked the quota group option as recommended. Especially, as quotas are not a stable btrfs feature yet.

**Comment by szszoke** [comment]
I'm having a similar issue with my system freezing during snapshot creation. I also have quotas enabled.

**Comment by zilexa** [comment]
Why does Timeshift not have `quotas` disabled by default? 
That would completely solve all issues related to it. Users can enable it themselves (which would still allow Timeshift to delete older snapshots that were created without quotas). By disabling it by default, [this situation](https://github.com/teejee2008/timeshift/issues/680) also cannot happen.

**Comment by teejee2008** [comment]
Removed quotas in latest commit
