### ISSUE TITLE
Allow a label - eg. pre-cuda 11 install drivers.

### ISSUE THREAD

**Issue by johndpope** [teejee2008/timeshift#698]
**Note:** This application is provided "as-is" without support or warranty. If you need changes or additional features in the application, please download the source code, make the changes, test it properly, and then submit a pull request. The changes will be reviewed and merged in the next update.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
just a label.

**Describe alternatives you've considered**
using the timeline - but I'm doing so many changes - it's like a git change log. need to be able to revert to specific commit.

**Comment by johndpope** [comment]
Actually sort of works already / but when the screen is shown for create / would be nice to be able to enter comment at that point.

**Comment by teejee2008** [comment]
You can double-click in the Comments column in GUI and add a comment.

**Comment by johndpope** [comment]
but that's after the fact.
