### ISSUE TITLE
Confusing footnote

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#70]
![Timeshift](https://raw.githubusercontent.com/teejee2008/timeshift/master/images/settings_schedule.png)

The footnote says _* Scheduled task runs once every hour_, no matter if you choose Daily, Weekly, etc.

If I choose _Daily_, shouldn't it say _once a day_, etc?

Or how does that work?

Also it's possible to check more than one task. What happens, when I choose all of them?

Can you clarify this?

Also it would be great, if it would say the exact time, e.g.
_The scheduled task runs once every hour (10:00, 11:00,12:00)_, 

Or something like that:
_Next scheduled task runs at 09:25._

Something less confusing.

**Comment by teejee2008** [comment]
The message is correct - it runs once every hour. There's a single hourly job that creates new snapshots and deletes snapshots that are marked for deletion.

Timeshift is designed for home users who use their systems for few hours daily. The hourly job ensures that daily, weekly snapshots get created whenever the user is using the system.

**Comment by NikoKrause** [comment]
Ah ok.
