### ISSUE TITLE
Timeshift refuses to backup /snap/

### ISSUE THREAD

**Issue by OmarShawky1** [teejee2008/timeshift#701]
**Describe the bug**
I cannot backup /snap/*** no matter what i do. unlike any folder, when i add snap and include it in the backup, when i recheck the settings i find it always excluded from the backup.

**To Reproduce**
1. Go to go to settings
2. Go to filters
3. Add folders
4. select /snap/
5. select "+"
6. press OK
7. repeat 1, 2 and you will find it excluded from the backup.

**Expected behavior**
I expect it to backup /snap folder

**Screenshots**
![image](https://user-images.githubusercontent.com/51538094/103437880-610aaf80-4c35-11eb-8a90-c37f369c0da9.png)

**System:**
 - Linux Distribution Name and Version: Elementary OS Hera 5.1.7
 - Desktop Pantheon
 - Application Version [e.g. v19.08]

**Comment by teejee2008** [comment]
It is excluded on purpose. Closing this issue.

**Comment by OmarShawky1** [comment]
but how to include it if wanted?

**Comment by teejee2008** [comment]
`/snap` is a read-only mount. Actual snap files are kept in the `/var/lib/snapd/` directory.
