### ISSUE TITLE
Support refind

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [teejee2008/timeshift#702]
**Note:** This application is provided "as-is" without support or warranty. If you need changes or additional features in the application, please download the source code, make the changes, test it properly, and then submit a pull request. The changes will be reviewed and merged in the next update.

**Is your feature request related to a problem? Please describe.**
Refind is much more modern looking bootloader than grub. Example

![refind dreary theme](https://raw.githubusercontent.com/dheishman/refind-dreary/master/highres/screenshot.jpg)

It would be great to use it and get the same benefits from timeshift that grub users do.

**Describe the solution you'd like**
It would be great to have an option to use refind

**Describe alternatives you've considered**
N/a

**Additional context**

**Comment by amyipdev** [comment]
Bumping this - as a rEFInd user, this is very important. I'd be willing to contribute to Timeshift to help get this supported - where do I start?

**Comment by teejee2008** [comment]
Have you tried restoring on a system that uses Refind? Refind does not require any special support. Just un-select the "Reinstall bootloader" option when restoring a snapshot.

**Comment by Th3Whit3Wolf** [comment]
You are right. My apologies, This [garuda linux forum conversation](https://forum.garudalinux.org/t/initial-thoughts-on-garuda/3114) is what made me create this issue. But it appears the post has been edited since I last read it and the issue is actually with [timeshift-autosnap](https://gitlab.com/gobonja/timeshift-autosnap). Sorry again!
