### ISSUE TITLE
Timeshift SVG icon

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#71]
First: Which of the timeshift icons is the current one? There are several in your repo, with a different `T`

Second: Do you have a SVG version of your Timeshift icon? So we can create easily new ones for Mint-X and Mint-Y. (I want to add it to the Editors' Picks in mintinstall, but we need proper icons for Mint-X and Mint-Y icon themes).

Third: If you don't have an SVG version, can you tell which font the `T` is from?

**Comment by NikoKrause** [comment]
Ok I found the font:
MathJax Fracture Font

**Comment by teejee2008** [comment]
There are XCF icons in the `/icons` folder. You can open them in GIMP and export as SVG.

/icons/timeshift_2_black_bold.xcf is currently the main icon.

**Comment by NikoKrause** [comment]
@teejee2008 
Converting from xcf to svg doesn't look good.
I created one with Inkscape instead. Can you check, if you like it (Colors, size, etc.)

[timeshift_black_bold.svg.zip](https://github.com/teejee2008/timeshift/files/1484596/timeshift_black_bold.svg.zip)

**Comment by teejee2008** [comment]
Looks great. Thanks!

**Comment by NikoKrause** [comment]
@teejee2008 
I created Timeshift SVG icons for Mint-X and Mint-Y themes.

The Mint-Y theme looks like this (no border since Mint-Y icons don't have any borders):
![timeshift_black_bold](https://user-images.githubusercontent.com/8415124/32991074-2d150536-cd35-11e7-82c6-44eaa9645001.png)

For Mint-X I have two variants, one with border and one without (clem likes the one without the borders, I like the one with the border). Also I have one with gray instead of black:
![timeshift_dark](https://user-images.githubusercontent.com/8415124/32991102-b71374ac-cd35-11e7-87b9-5ac26857ce42.png)
![timeshift_darker](https://user-images.githubusercontent.com/8415124/32991110-d00c6d92-cd35-11e7-8bab-70d0fd11ffd5.png)
![timeshift](https://user-images.githubusercontent.com/8415124/32991112-d2630c0e-cd35-11e7-9600-c947254826eb.png)

Which one do you like? Also are the colors ok? Was not sure about the background color, because it needs a gradient, i.e. two background colors (a bright one and one a little bit darker)

**Comment by teejee2008** [comment]
For Mint-X, I like the third one (without the border). Between the 2 icons with border, I like the black one more than the gray. The colors are perfect.

**Comment by NikoKrause** [comment]
Timeshift has been added to Editors' Picks in mintinstall.

Feel free to use the round SVG icon in your repo.
The current one looks a bit blurry.
