### ISSUE TITLE
[Question] Possible to redirect Timeshift backup to a SSHFS share on nas?

### ISSUE THREAD

**Issue by MostHated** [teejee2008/timeshift#716]
Hey there,
    I was just wondering if there were any known issues in taking the Timeshift folder and then in fstab mounting that folder to an sshfs share? I attempted to do this, then went to run a snapshot and it looks like the snapshot ran according to Timeshift, but nothing in the Timeshift folder updated, but it looks like /run/timeshift/backup was populated with files. Does this mean I should also mount that folder to the NAS, or are things just not working properly due to attempting to do this in the first place?

This is on Pop_OS 20.10
Timeshift v20.03

Thanks,
-MH

**Comment by teejee2008** [comment]
It is not possible to save the snapshots to NAS. It's a technical limitation. Even if you do manage to save it somehow, various things will be broken when you try to restore it.
