### ISSUE TITLE
backup dir changed after docker is installed

### ISSUE THREAD

**Issue by giswqs** [teejee2008/timeshift#72]
After installing docker (on elementary OS 0.4.1 Loki), timeshift switches to using directory '**/var/lib/docker/overlay2/timeshift/snapshots/'** for keeping snapshots, instead of normal '/timeshift/' (and doesn't see old snapshots anymore). 

I found a similar issue reported here <https://bugs.launchpad.net/timeshift/+bug/1652975>.

Any help will be appreciated.

**Comment by teejee2008** [comment]
Docker is not supported. Its mentioned in the Supported Systems section in
the Readme.

https://github.com/teejee2008/timeshift

**Comment by terohuomo** [comment]
Timeshift does not have to be used in a Docker container, but **installing Docker on the same system as Timeshift** relocates Timeshift's snapshot folder, which leads to confusion as all your snapshot history seems to go missing.

I believe this ticket is miscommunicated and thus incorrectly closed and should be reopened.

**Comment by fullofcaffeine** [comment]
+1, big WTF moment. Does anyone have any workarounds for this?

**Comment by darkladder** [comment]
Weird...  I had the problem w/ Ubuntu 16.04, but wiped w/ Xubuntu 16.04 and don't have this issue at present.

Not that I would think that the Ubuntu flavor might have something to do w/ it, but the only other thing I know for sure is I had Timeshift installed before I installed Docker.

**Comment by JanisE** [comment]
I seem to have a similar problem with LXD (Linux Containers). Maybe it's worth mentioning this, too.
