### ISSUE TITLE
[Question] What is the /run/timeshift/backup folder (Ubuntu 20.04)?

### ISSUE THREAD

**Issue by WrichikBasu** [teejee2008/timeshift#724]
This is basically a question rather than an issue. If you enable Discussions for this repo in the future, this can be moved there.

I installed the software on my Ubuntu 20.04 machine and selected rsync. I have not created any snapshot yet. However, under the GNOME system monitor, I found a new directory listed:

![image](https://user-images.githubusercontent.com/56736644/110198676-37127b00-7e7a-11eb-96ab-3adb3b21cfc5.png)

As you can see, the `/run/timeshift/backup` folder has the same size as `/`. I guess that this is not just a copy-paste of `/` because the free space currently on the hard disk is the same as that before I installed timeshift. Interestingly, if I add a dummy file to my home folder, that file appears under `/run/timeshift/backup/home/<user-name>/dummy.txt`, and deleting the latter also deletes the former.

It seems that some script is working underneath such that even if I uninstall timeshift, this folder remains there, and new files that I add elsewhere are also found here.

Is this folder actually a hard link?

**Comment by LeDilam** [comment]
I have the same question.
It looks like in /run there is an independent copy of all timeshift snapshots.
It doesn't seem to be just a link.

**Comment by LeDilam** [comment]
The main question remains: **Why does this copy exist ?**
It seems to take a lot of space for nothing.

**Comment by WrichikBasu** [comment]
> It doesn't seem to be just a link.

Yes, I have seen that — once you create a snapshot, it can be found in that folder too.

I noted something more: even if I delete all the snapshots and then uninstall timeshift (using `apt purge`), that folder remains there, and changes made anywhere in the PC are reflected in that folder.

> It seems to take a lot of space for nothing.

Are you sure this folder takes up space? I am sure that before installing timeshift, I had 590 GB of free space on my hard disk. As per Ubuntu, this folder takes up 320 GB on my disk, but even then, the free space is still the same.

Deleting anything in that folder deletes the original files too. I tested this out with a dummy file. So, don't delete it with `sudo rm -rf`, otherwise you will end up deleting your system.

**Comment by LeDilam** [comment]
If I open /run/timeshift, the backup folder inside it indicate a lot of space.
But if I look the size of the /run/timeshift folder, it indicate no space.

I think /run may be like /tmp but more stable (can't be deleted at every time) and probably used to store files in RAM.

**Comment by WrichikBasu** [comment]
Before asking this question here, I had asked it in [another forum](https://www.physicsforums.com/threads/can-i-safely-delete-run-timeshift-backup-in-ubuntu-20-04.1000515/). It [turned out](https://www.physicsforums.com/threads/can-i-safely-delete-run-timeshift-backup-in-ubuntu-20-04.1000515/post-6467152) that this folder is basically a duplicate mount of the filesystem. That is why it does not take up any space.

With that, I will close this issue since my curiosity has been satisfied.
