### ISSUE TITLE
Timeshift not running backup automatically

### ISSUE THREAD

**Issue by rdonnelly2** [teejee2008/timeshift#731]
Message: Hi, I have timeshift installed, schedule is daily backup with keep 5 snapshot. I am using Kubuntu 20.10. Timeshift has yet to run an automatic backup in 5 days. It shows up in the Cron.d folder, so I am not sure why it is not backing up?

**Comment by vinid223** [comment]
Same issue for me, timeshift never runs automatically. I've selected all possible snapshot level, but even after a couple of hours, reboot, etc. no backup at all except for the ones I created myself.

**Comment by RanTrycl** [comment]
I'm having a similar problem. No problems even once with TS on 18.x or 19.x but now on 20.1, it doesn't want to run by itself. Also, I think it refuses to run outright ever, from cron, if the schedule is Weekly. I seem to be having slightly better luck with Daily. This is TS version 20.11.1.

**Comment by rdonnelly2** [comment]
I closed the program a week ago, I was going to do an on demand backup, now I find it is working made a snapshot daily. Case closed for me.

**Comment by rdonnelly2** [comment]
Closed
