### ISSUE TITLE
timeshift requires which

### ISSUE THREAD

**Issue by SamLukeYes** [teejee2008/timeshift#736]
**Describe the bug**
When `which` is missing, timeshift asks the user to install `rsync`, `blkid`, `df`, `mount`, `umount`, `fuser`, `crontab`, `cp`, `rm`, `touch`, `ln` and `sync`, but not `which`.

**To Reproduce**
1. Make an archiso with [this commit](https://github.com/SamLukeYes/archiso-surface/tree/b7d8379cb4a7d0b5ff008f61859a553d3d70dfd4)
2. Boot from the archiso
3. Run `timeshift-gtk` in Terminal

*Once https://github.com/archlinuxcn/repo/issues/2167 is fixed, this issue would no longer be reproducible with the method above. Building `timeshift` from AUR and then remove `which` should reproduce this.*

**Expected behavior**
If `timeshift` is packaged properly, `timeshift-gtk` should be launched without issue. However, due to https://github.com/archlinuxcn/repo/issues/2167, the dependency `which` is missing. Then timeshift should ask user to install `which`.

**Screenshots**
![image](https://user-images.githubusercontent.com/12882091/112868106-4342ce80-90ee-11eb-9013-11951caf308c.png)

**System:**
 - Arch Linux
 - GNOME
 - v20.11.1+3+g08d0e59-3 (from [archlinuxcn] repo)

**Comment by LotteCzy** [comment]
hello. I've got this problem on manjaro.What shoud i do about it?

**Comment by SamLukeYes** [comment]
> hello. I've got this problem on manjaro.What shoud i do about it?

If you're sure it is `which` that is missing, then `sudo pacman -S which` would solve the problem.

**Comment by LotteCzy** [comment]
> > hello. I've got this problem on manjaro.What shoud i do about it?
> 
> If you're sure it is `which` that is missing, then `sudo pacman -S which` would solve the problem.

thanks！
