### ISSUE TITLE
[Feature request] Adding notes to snapshot?

### ISSUE THREAD

**Issue by peteruithoven** [teejee2008/timeshift#74]
This might be rare, but I'd like to add notes to some snapshots. For example situations like: 
- Pre kernel upgrade
- Post kernel upgrade
- Pre bios update 
- Pre firmware update
- Pre grub change

**Comment by teejee2008** [comment]
You can double-click on the comments/description column and enter comments

**Comment by peteruithoven** [comment]
OMG, I don't know how I missed that. Quite obvious.
