### ISSUE TITLE
After Update timeshift starts in usb rescue mode only

### ISSUE THREAD

**Issue by bebop210** [teejee2008/timeshift#753]
This is affecting two different arch Linux installations on two separate but spec similar PCs..  
One is arch Linux / partition ext4 saving on a separate home partition that is xfs.. has created and restored correctly for 2 years until last update. The other arch install is a single 1TB btrfs partition.  Same update have made the timeshifts unable to see the partitions timeshift utilized prior. If I boot up a Manjaro gnome iso the timeshift installed on it can find the prior snapshots with no problem..

**Comment by texstar** [comment]
It can't find anything now.

timeshift --check
E: ts: Failed to get partition list.
E: Snapshots cannot be created in Live CD mode

I'm not in LiveCD mode. The only thing I can think of is util-linux was updated recently to 2.37 that may have some effect on timeshift.

**Comment by tbschommer** [comment]
I checked the UUID Timeshift complained about not finding, but using the blkid command the device's UUID is listed correctly.

**Comment by texstar** [comment]
I backed down util-linux to 2.36.2 and timeshift will now show the partitions again but it is still locked in restore only mode.

**Comment by phush0** [comment]
Same here on Arch

**Comment by eumario** [comment]
Also having this issue on Garuda Linux, which is blocking me from updating packages on my system, since it's trying to do a snapshot before upgrading.

**Comment by asjur** [comment]
Same issue here. EndeavourOS.

**Comment by eumario** [comment]
Just to show the errors that occur:

Updating a package on Garuda through pacman -U:
```
╭─eumario@inosuke in repo: obs-studio-browser on  master [?] took 2s
[🔴] × sudo pacman -U obs-studio-browser-27.0.0-6-x86_64.pkg.tar.zst
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) obs-studio-browser-27.0.0-6

Total Installed Size:  220.94 MiB
Net Upgrade Size:       16.38 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                           [-------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                         [-------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                              [-------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                        [-------------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                      [-------------------------------------------------------------------------] 100%
:: Running pre-transaction hooks...
(1/1) Creating Timeshift snapshot before upgrade...
E: ts: Failed to get partition list.
E: System disk not found!
Unable to run timeshift-autosnap! Please close Timeshift and try again. Script will now exit...
error: command failed to execute correctly
error: failed to commit transaction (failed to run transaction hooks)
Errors occurred, no packages were upgraded.
```

Block ID Output:
```
╭─eumario@inosuke in ~ took 4ms
╰─λ blkid
/dev/loop1: TYPE="squashfs"
/dev/nvme0n1p2: UUID="116647d6-b9cf-4b5f-81c8-255cebf33bfc" UUID_SUB="c6ba60ee-4f5a-4cee-b9e5-a66175be2c4f" BLOCK_SIZE="4096" TYPE="btrfs" PARTUUID="49fd9456-68a3-354b-ae7c-ed910d0cbe02"
/dev/zram3: UUID="b23d0478-8b0e-483a-882c-4ab0cae1f813" TYPE="swap"
/dev/sdb2: LABEL="1TB_Data_Internal" BLOCK_SIZE="512" UUID="9A0C51B20C5189E1" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="39f4b9eb-86f9-4811-8c2a-743c4afabbb4"
/dev/zram1: UUID="0dba6a6e-856b-4ce8-9072-600a103d0b9f" TYPE="swap"
/dev/loop4: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/loop0: TYPE="squashfs"
/dev/zram2: UUID="4bedfab8-50aa-40ea-9ca3-c9ce915fe1f5" TYPE="swap"
/dev/sda4: LABEL="Win_10_SSD" BLOCK_SIZE="512" UUID="E09AFBB39AFB83F6" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="617d2c95-0ef4-4a29-ab3d-83182a115d6f"
/dev/sda2: UUID="04ED-0E57" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="9aa20e6e-31ef-410d-938d-ffa3d044735c"
/dev/sda1: LABEL="Recovery" BLOCK_SIZE="512" UUID="AEFEE907FEE8C923" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="bdd92aaa-2031-48fd-949d-a993bc420d20"
/dev/zram0: UUID="898b4530-578a-478a-be6e-02558ea24633" TYPE="swap"
/dev/loop3: TYPE="squashfs"
```
BTRFS Subvolume list of Root Directory:
```
╭─eumario@inosuke in ~ took 48ms
╰─λ sudo btrfs subvolume list /
[sudo] password for eumario:            
ID 256 gen 88752 top level 5 path @
ID 257 gen 88752 top level 5 path @home
ID 258 gen 88749 top level 5 path @root
ID 259 gen 52890 top level 5 path @srv
ID 260 gen 88752 top level 5 path @cache
ID 261 gen 88752 top level 5 path @log
ID 262 gen 88729 top level 5 path @tmp
ID 477 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-05-30_14-07-33/@
ID 480 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-05-30_14-17-11/@
ID 504 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-06-01_20-00-01/@
ID 505 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-06-02_20-00-01/@
ID 506 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-06-03_20-00-01/@
ID 529 gen 88656 top level 5 path timeshift-btrfs/snapshots/2021-06-04_01-32-20/@
```

Linux Kernel Version:
```
╭─eumario@inosuke in ~ took 3s
╰─λ uname -a
Linux inosuke 5.12.9-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 03 Jun 2021 11:36:07 +0000 x86_64 GNU/Linux
```

**Comment by phush0** [comment]
you can downgrade util-linux and util-linux-libs or remove timeshift-autosnap ....

**Comment by eumario** [comment]
@phush0 Thanks, that worked for me.  Going to update the Garuda Linux site.  Also, if someone comes along here to see, there's a solution to un-installing timeshift-autosnap.  Issue the command: 
```
sudo SKIP_AUTOSNAP=1 pacman -Syu
```

Saves from having to unisntall Auto-Snap, and re-install it. ;-)

**Comment by kdmurthy** [comment]
The fix is actually simple in the code. the output format of `lsblk` changed - "MAJ:MIN" is output as "MAJ_MIN" in the new util-linux.

```
diff --git a/src/Utility/Device.vala b/src/Utility/Device.vala
index 18f09de..b276055 100755
--- a/src/Utility/Device.vala
+++ b/src/Utility/Device.vala
@@ -428,10 +428,10 @@ public class Device : GLib.Object{
 
 			try{
 				if (lsblk_is_ancient){
-					rex = new Regex("""NAME="(.*)" KNAME="(.*)" LABEL="(.*)" UUID="(.*)" TYPE="(.*)" FSTYPE="(.*)" SIZE="(.*)" MOUNTPOINT="(.*)" MODEL="(.*)" RO="([0-9]+)" RM="([0-9]+)" MAJ:MIN="([0-9:]+)"""");
+					rex = new Regex("""NAME="(.*)" KNAME="(.*)" LABEL="(.*)" UUID="(.*)" TYPE="(.*)" FSTYPE="(.*)" SIZE="(.*)" MOUNTPOINT="(.*)" MODEL="(.*)" RO="([0-9]+)" RM="([0-9]+)" MAJ[_:]MIN="([0-9:]+)"""");
 				}
 				else{
-					rex = new Regex("""NAME="(.*)" KNAME="(.*)" LABEL="(.*)" UUID="(.*)" TYPE="(.*)" FSTYPE="(.*)" SIZE="(.*)" MOUNTPOINT="(.*)" MODEL="(.*)" RO="([0-9]+)" HOTPLUG="([0-9]+)" MAJ:MIN="([0-9:]+)" PARTLABEL="(.*)" PARTUUID="(.*)" PKNAME="(.*)" VENDOR="(.*)" SERIAL="(.*)" REV="(.*)"""");
+					rex = new Regex("""NAME="(.*)" KNAME="(.*)" LABEL="(.*)" UUID="(.*)" TYPE="(.*)" FSTYPE="(.*)" SIZE="(.*)" MOUNTPOINT="(.*)" MODEL="(.*)" RO="([0-9]+)" HOTPLUG="([0-9]+)" MAJ[_:]MIN="([0-9:]+)" PARTLABEL="(.*)" PARTUUID="(.*)" PKNAME="(.*)" VENDOR="(.*)" SERIAL="(.*)" REV="(.*)"""");
 				}
 
 				if (rex.match (line, 0, out match)){

```

With this change timeshift should work again.

**Comment by phush0** [comment]
works like a charm

**Comment by texstar** [comment]
The patch also works for us. Everybody happy again.

**Comment by kdmurthy** [comment]
Patch landed up in AUR :)

**Comment by eumario** [comment]
Can confirm this patch works perfectly, and as @kdmurthy has stated, it is in the AUR, so everyone who ran into this issue, will now be able to fix it on Arch based distros.

**Comment by NoteFox** [comment]
thanks for the fix ~

**Comment by obswwf** [comment]
patches are not working for me. Timeshift is still in USB mode

**Comment by obswwf** [comment]
Nevermind. Timeshift was installed from a repo that isn't the aur for some reason. Reinstalling from AUR solved the problem.

**Comment by bebop210** [comment]
All fixed for me sorry for the delay but closing now… thank you

**Comment by KairuiLiu** [comment]
> Patch landed up in AUR :)

Hi, I meet the same question, and I reinstall the software it still occur;
On the aur the, timeshift version is 20.11.1+4+gd437358-1
but I run `yay -S timeshift`, it shows last version is timeshift-20.11.1+3+g08d0e59-4

----

the error says UUID="XXX" not find
I see the file `/etc/timeshift/timeshift.json`, the uuid is same to the uuid shows on `fdisk -l`...

**Comment by obswwf** [comment]
> > Patch landed up in AUR :)
> 
> Hi, I meet the same question, and I reinstall the software it still occur;
> On the AUR, the timeshift version is 20.11.1+4+gd437358-1
> but I run `yay -S timeshift`, it shows last version is timeshift-20.11.1+3+g08d0e59-4
> 
> the error says UUID="XXX" not find
> I see the file `/etc/timeshift/timeshift.json`, the uuid is same to the uuid shows on `fdisk -l`...

try `yay -S timeshift --aur`

**Comment by KairuiLiu** [comment]
> > > Patch landed up in AUR :)
> > 
> > 
> > Hi, I meet the same question, and I reinstall the software it still occur;
> > On the AUR, the timeshift version is 20.11.1+4+gd437358-1
> > but I run `yay -S timeshift`, it shows last version is timeshift-20.11.1+3+g08d0e59-4
> > the error says UUID="XXX" not find
> > I see the file `/etc/timeshift/timeshift.json`, the uuid is same to the uuid shows on `fdisk -l`...
> 
> try `yay -S timeshift --aur`

Thanks a lot, it worked!!

**Comment by alexeightsix** [comment]
I was able to fix it after upgrading the package from the AUR, thanks everyone!

**Comment by tralph3** [comment]
`timeshift-bin` from the AUR still has the same issue.

**Comment by Luryy** [comment]
> `timeshift-bin` from the AUR still has the same issue.

Here too
