### ISSUE TITLE
Timeshift and util-linux

### ISSUE THREAD

**Issue by robson-66** [teejee2008/timeshift#755]
I don't know if this is the fault of `util-linux`, but `timeshift` under version `util-linux 2.37-1` has become useless because disk partitions are not detected.

**Comment by pikakolendo02** [comment]
see the patch here https://github.com/teejee2008/timeshift/issues/753#issuecomment-854493305

**Comment by robson-66** [comment]
@pikakolendo02 Thanks, this patch solved the problem.
