### ISSUE TITLE
Backup to remote drive?

### ISSUE THREAD

**Issue by eloo** [teejee2008/timeshift#76]
Hi,
i just tried to use your backup tool but i didn't find an option to use a remote drive (e.g. NFS) to use as storage path.
Is this currently not supported? Or did i miss something?

Thanks for your help!

**Comment by teejee2008** [comment]
Not supported. Remote filesystems do not support hard-links.

**Comment by eloo** [comment]
okay.. but whats the proper way to backup a system with only one drive now?

**Comment by Nestak2** [comment]
@eloo I am having the same issue. Have you found an alternative to timeshift that does this job?

**Comment by eloo** [comment]
@Nestak2 no :(

**Comment by gibnix** [comment]
> Not supported. Remote filesystems do not support hard-links.

Look at rsnapshot. Uses rsync via ssh and supports hardlinks on remote fs.
