### ISSUE TITLE
linux boot menu timeshift

### ISSUE THREAD

**Issue by Pantyhose-X** [teejee2008/timeshift#774]
**Is your feature request related to a problem? Please describe.**
As a newbie to Linux, the system is often broken by me, and the desktop cannot be accessed. The desktop environment has been destroyed the most
**Describe the solution you'd like**
So I want timeshift to run in the boot menu
start menu adds timeshift system backup and recovery functions
![](https://forum.manjaro.org/uploads/default/original/2X/0/0af86cbab7621a9c66c13a89e7bfd3a441e4f13e.png)

**Comment by tjallingran** [comment]
There's a third-party solution for this. See https://github.com/Antynea/grub-btrfs

**Comment by XRaTiX** [comment]
The link above only works if you are using BTRFS,if you are using Manjaro I susspose you are using EXT4,in that case you can make a iso booteable from the grub menu,I did this to recover in case my Manjaro mess up

https://forum.manjaro.org/t/howto-booting-manjaro-iso-directly-with-grub/15892

**Comment by acid-bong** [comment]
@XRaTiX Manjaro does offer btrfs formatting. Although OP should've specified if their root partition is btrfs or not
