### ISSUE TITLE
Timeshift not getting partition list

### ISSUE THREAD

**Issue by Nicholas-Baron** [teejee2008/timeshift#778]
**Describe the bug**
When running `sudo timeshift-gtk` or `sudo timeshift`, the error "E: ts: failed to get partition list" is printed from [Main.vala, line 3347](https://github.com/teejee2008/timeshift/blob/efed1177e3951e333ad3f30a86612b39b6a27ce3/src/Core/Main.vala#L3347). However, I know that my `sdb1` partition has backups on it.

**To Reproduce**
1. Run `sudo timeshift-gtk` or `sudo timeshift --list`
2. See error 
3. See no backups listed

**Expected behavior**
The list of backups stored on `/dev/sdb1`

**Screenshots**
Output of `cat /etc/timeshift/timeshift.json`: 
```json
{
  "backup_device_uuid" : "f2011da3-e2a0-4a04-bb34-4636a57eb516",
  "parent_device_uuid" : "",
  "do_first_run" : "false",
  "btrfs_mode" : "false",
  "include_btrfs_home_for_backup" : "false",
  "include_btrfs_home_for_restore" : "false",
  "stop_cron_emails" : "true",
  "btrfs_use_qgroup" : "true",
  "schedule_monthly" : "false",
  "schedule_weekly" : "false",
  "schedule_daily" : "false",
  "schedule_hourly" : "false",
  "schedule_boot" : "false",
  "count_monthly" : "2",
  "count_weekly" : "2",
  "count_daily" : "3",
  "count_hourly" : "6",
  "count_boot" : "5",
  "snapshot_size" : "74800303408",
  "snapshot_count" : "618287",
  "date_format" : "%Y-%m-%d %H:%M:%S",
  "exclude" : [
    "+ /home/nick/.**"
  ],
  "exclude-apps" : []
}
```

Output of `lsblk -o NAME,UUID,MOUNTPOINTS`:
```
NAME   UUID                                 MOUNTPOINTS
sda
|-sda1 96DD-8BBF                            /boot
|-sda2 7a875ebc-317e-4d00-8918-7ded671f9fc7 [SWAP]
|-sda3 f80e6e19-cf55-4e33-94ad-53ed3f684b22 /
`-sda4 eb5bf35b-05bc-4a9b-96a5-af557610e814 /home
sdb
|-sdb1 f2011da3-e2a0-4a04-bb34-4636a57eb516
|-sdb2 4d5dc2fe-6c70-433e-aba7-b5ab6cfc1156 /mnt/steam_extra
|-sdb3 bc153696-cc9b-4a68-9ed4-19f68057e5a0 /mnt/extra
`-sdb4 fd7a2f64-8dc5-41d9-a0e5-19597ce25045
```

**System:**
 - Linux Distribution Name and Version: Archlinux
 - Desktop: Herbstluft
 - Application Version: v20.11.1 (from the AUR package `timeshift-bin`)

**Comment by tralph3** [comment]
This is issue #759, it has already been fixed, but the `timeshift-bin` package uses the latest release of timeshift, which has been done before this patch. You can wait for a new release, which is hopefully soon, or use the `timeshift` package, which gets compiled from source.

**Comment by Nicholas-Baron** [comment]
@tralph3 I was able to get `timeshift` building from the AUR. A week after the next release, I will check if the bin version is updated.

**Comment by Henriquelay** [comment]
`timeshift-bin` AUR package still not updated. Compiling from `timeshift` packaged worked fine aswell.

**Comment by tralph3** [comment]
`timeshift-bin` will continue to not work as long as the developers of the project don't provide a pre-compiled binary. You can see on the releases that there's no binary, only the source code. `timeshift-bin` depends on this.
