### ISSUE TITLE
could not find a distribution template for Raspbian/buster

### ISSUE THREAD

**Issue by IshtarIS** [teejee2008/timeshift#784]
**Describe the bug**
New install of Buster onto Raspberry Pi Zero W.   Following instructions at https://github.com/teejee2008/timeshift/wiki/Installation but on sudo add-apt-repository -y ppa:teejee2008/ppa line an error occurs:
could not find a distribution template for Raspbian/buster

I am not sure if this is related to the PPA being only for x86 and x84 (i.e not for arm) or an issue woth the PPA or an issue with add-apt-repository

**To Reproduce**
clean Buster install on Raspberry Pi
Sudo apt update
sudo apt upgrade
sudo apt install software-properties-common
sudo add-apt-repository -y ppa:teejee2008/ppa

Error:
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

**Expected behavior**
should have completed adding PPA to allow next commands:'
sudo apt-get update
sudo apt-get install timeshift

**Screenshots**
error provided above

**System:**
Pi Zero W
Raspian Buster

**Comment by Noexpert** [comment]
Timeshift is included in Buster:
https://packages.debian.org/buster/timeshift

Try to clean uninstall the version you have and then simply `sudo apt install timeshift`

**Comment by IshtarIS** [comment]
Thank you for the quick response.   I did a clean install and there is no longer an issue
