### ISSUE TITLE
Timeshift will only start in "Live USB Mode " on update to libsmartcols1

### ISSUE THREAD

**Issue by pjnsmb** [teejee2008/timeshift#785]
Running debian sid the latest update to the util-linux package brings a successful update to the following packages :    
  util-linux bsdextrautils bsdutils eject fdisk libblkid1 libfdisk1 libmount1  libuuid1 mount rfkill util-linux    
These update from  2.36.1-8 to  2.37.2-1 without a problem .

As soon as I  update libsmartcols1 from 2.36.1-8 to 2.37.2-1 when I run Timeshift it starts with -
Live USB mode (Restore only) Device not found UUID: xxxx 

Apt changelog for libsmartcols1 shows :

util-linux (2.37.2-1) unstable; urgency=medium

  [ Chris Hofstaedtler ]
  * Update to upstream version 2.37.2, rebase patches
    * Skip lsns/ioctl_ns test if unshare fails
    * Stop installing fdformat, following upstream
    * Follow upstream rename of getopt examples
    * libblkid1: update symbols
    * libmount1: update symbols
    * Install new uclampset binary
  * Depend on asciidoctor for man pages.
    We should figure out how to skip asciidoctor for stage1 builds, as it is
    not strictly necessary except for some edge cases.
  * d/copyright: remove non-existing files (Closes: #987942)
  * d/rules: fix space/tab confusion in stage1 part
  * Disable GPL3+ parts in hwclock (Closes: #987944)
  * Explicitly conflict with libedit-dev, causes build failures
  * Install linux32, linux64 manpages as upstream intended (section 8)
  * Remove relations that are fulfilled in at least buster
  * Bump Standards-Version to 4.6.0

  [ Matthias Klose ]
   allow building without the udebs.
Tag all *-udeb packages with the !noudeb build-profile to
    allow building without the udebs.

  [ Andreas Henriksson ]
  * bsdextrautils: Make shlibs:Depends regular Depends
    As described in the bug report, bsdextrautils is a normal
    package (not Essential: yes), so doesn't need to Pre-Depend
    on libraries. Thanks to Sven Joachim for a keen eye to catch
    this detail. (Closes: #982557)

 -- Chris Hofstaedtler <zeha@debian.org>  Fri, 20 Aug 2021 09:31:11 +0000

Siduction  Mate on debian sid unstable
Timeshift  v.20.11.1

Is this a problem with a bug in libsmartcols1 or is an update to Timeshift required please ?

thanks and regards

pjnsmb

**Comment by fethomm** [comment]
Same here (also current Debian Sid). Timed snapshots stopped on August 19th. When trying to do a manual snapshot, I get this:
![timeshift](https://user-images.githubusercontent.com/15143037/130663320-1ee8a5c6-7fb8-4250-9686-2111291557d1.png)

**Comment by pjnsmb** [comment]
Mysteriously my daily and weekly syncs are being completed automatically again for the last few days.
Anyone else finding this too before I close this ?

**Comment by fethomm** [comment]
Yep, works again.
