### ISSUE TITLE
Documentation: make it clear whether backups are compressed

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/timeshift#81]
I think it would be a good idea to make it clear whether or not backed-up files are compressed. For, users will want to know how much disk space is used. That backups are unencrypted (yes?) might also be mentioned.

(Rcync, which is the snapshot method I am using, has the ability to use compression, I believe - but it does not necessarily use it.)

**Comment by teejee2008** [comment]
I'll add it to the Readme file.

Rsync snapshots have no compression and no encryption.

Rsync's *-z* option is for compressing the data *during* the transfer from
source to destination. It doesn't compress files that are written to the
destination directory.

Btrfs snapshots can be compressed by using the proper mount options. This
is something that the user has to do manually and is not managed by
Timeshift.

**Comment by CottonEaster** [comment]
Thanks. That makes thinks clear to me, but my point, mostly, was that those facts should be conveyed within the application or at least somewhere prominent on this site.

Relatedly - and I'd like to know this and, again, it might be good to make the information widely visible - in what folder are the backups stored? I know one gets to choose which _drive_ ones uses . . EDIT: ah, found it. It's `/home/timeshift`.

**Comment by teejee2008** [comment]
The snapshot location is /timeshift on the root of selected device. So if your selected device is mounted at /home then snapshots will be saved to /home/timeshift

**Comment by teejee2008** [comment]
Message was added to the Snapshot Location window
