### ISSUE TITLE
Timeshift stuck in USB Recovery only mode and latest source won't build

### ISSUE THREAD

**Issue by Dan-Essin** [teejee2008/timeshift#831]
On Fedora 35
I was counting of Timeshift as part of my backup strategy but When I install it (from the dnf repo) it  opens in USB Recovery Mode. Obviously never prompts for backup location and won't backup anything.

Tried building from latest source timeshift-21.09.1
Build fails
------------
➜  timeshift-21.09.1 make
cd src; make all
make[1]: Entering directory '/root/Downloads/timeshift-21.09.1/src'
Package vte-2.91 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.91.pc'
to the PKG_CONFIG_PATH environment variable
Package 'vte-2.91', required by 'virtual:world', not found
/bin/bash: line 1: test: -lt: unary operator expected
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'virtual:world', not found
/bin/bash: line 1: test: -gt: unary operator expected
#timeshift-gtk
valac -X -D'GETTEXT_PACKAGE="timeshift"' \
	--Xcc="-lm" --Xcc="-O3" -D VTE_291   \
	Core/*.vala Gtk/*.vala Utility/*.vala Utility/Gtk/*.vala \
	-o timeshift-gtk \
	--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix \
	--pkg gee-0.8 --pkg json-glib-1.0 --pkg gio-2.0 \
	--pkg gtk+-3.0 --pkg vte-2.91 
error: Package `gee-0.8' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `vte-2.91' not found in specified Vala Atimeshift-21.09.1PI directories or GObject-Introspection GIR directories
Compilation failed: 2 error(s), 0 warning(s)
make[1]: *** [makefile:53: app-gtk] Error 1
make[1]: Leaving directory '/root/Downloads/timeshift-21.09.1/src'
make: *** [makefile:2: all] Error 2
------timeshift-21.09.1
gee can't be installed by dnf - it is unrecognized. Implies it is part of vala (whatever that is)

vala anad vte are apparently obsolete as far as timeshift is concerned but I can't find any obvious way to update them.timeshift-21.09.1

Package vala-0.54.3-1.fc35.x86_64 is already installed.
ackage vte-0.28.2-35.fc35.x86_64 is already installed.

Why would you make the build depend on modules that are not generally and readily available?

I have removed and reinstalled it several times with the same results. 
Why is it stuck in USB Mode?
Why isn't there a setting option to specify the timeshift device?
Why isn't there a way in settings to force it out of USB mode?

**Comment by openprojectrizal** [comment]
You could use latest Timeshift for Fedora 35 here

https://copr.fedorainfracloud.org/coprs/oprizal/timeshift-upstream/

Or if you want to build it yourself from the sources on Fedora please refer to this article:

http://localhost:4000/linux/2021/10/21/timeshift-on-fedora-35-beta.html

**Comment by teejee2008** [comment]
@Dan-Essin 
The version in Fedora 35 repository is very outdated. 

@oprizal 
Thanks for packaging it for Fedora
