### ISSUE TITLE
No .RUN installer available

### ISSUE THREAD

**Issue by array-in-a-matrix** [teejee2008/timeshift#833]
**Describe the bug**
I wanted to install timeshift however I am not in a debian based system and the [wiki](https://github.com/teejee2008/timeshift/wiki/Installation#other-linux-distributions) says to run the .RUN from the [releases](https://github.com/teejee2008/timeshift/releases/tag/v21.09.1) page. The problem is there is no installer there (even for debian-based systems).

**Expected behavior**
Finding an installer for the latest version.

**Screenshots**
![SS_11 11 2021_12:00:54](https://user-images.githubusercontent.com/78233840/141338517-82161a75-0f09-4f30-b111-4320e1013c82.png)
![SS_11 11 2021_11:59:29](https://user-images.githubusercontent.com/78233840/141338305-8d96e894-19fe-4526-8420-a20cd9e9335d.png)

**System:**
 - Linux Distribution Name and Version: [e.g. Ubuntu 16.04]
 Arch Linux
 - Desktop [e.g. MATE, XFCE]
 KDE + i3
 - Application Version [e.g. v18.8]
 v21.09.1

**Comment by teejee2008** [comment]
.Run installers are no longer provided. Wiki has been updated.
