### ISSUE TITLE
Timeshift treats links to other folders as actual folders instead of links

### ISSUE THREAD

**Issue by thatLeaflet** [teejee2008/timeshift#837]
**Describe the bug**
While trying to prevent Timeshift from backing up Steam games, I told Timeshift to not backup /home/homename/.steam/steam/steamapps/common. Upon making a backup, this folder was added in the snapshot regardless. I believe this is because Steam actually stores its files in '/home/homename/.local/share/Steam', but creates a link to this folder in the home directory called ".steam".

**To Reproduce**
1. Open 'Timeshift'
2. Click on 'Settings'
3. Go to the 'Filters' tab
4. Click 'Add Folders'
5. Select the directory '/home/homename/.steam/steam/steamapps/common'
6. Begin snapshot

**Expected behavior**
Timeshift would recognize that the '/home/homename/.steam/steam/steamapps/common' contained links to folders and actually referred to '/home/homename/.local/share/Steam/steamapps/common'.

**System:**
 - Linux Distribution Name and Version: Arch Linux
 - Desktop: Gnome
 - Application Version: v21.09.1

**Comment by teejee2008** [comment]
This is the expected behavior. Links are saved as links by rsync. You need to exclude the actual paths.
