### ISSUE TITLE
Disk abuse Mint 18.3 Mate

### ISSUE THREAD

**Issue by muvol2** [teejee2008/timeshift#84]
I just upgraded to Mint 18.3 Mate and was excited to see Timeshift installed.  

However, when I started timeshift (with defaults) it spent the next two days writing 1.5 TB to my data disk.  So, obviously, I would like to interrupt the current snapshot and try to create more sane settings.  But timeshift keeps restarting the original snapshot, while providing no discernible way to modify or fix the problem.  

So here's the question.  Where the hell is the "off" switch.  Google doesn't know.  And your GUI provides no way to find this.  

WTF!

**Comment by teejee2008** [comment]
Unselect all snaphot levels from Settings. This will turn off the scheduled task.

Do you have any devices mounted outside of /mnt and /media? If so then add it to the exclude list.
