### ISSUE TITLE
Is it possible to clone the system using backup of timeshift

### ISSUE THREAD

**Issue by Stephen2252Ro** [teejee2008/timeshift#841]
This is a free application that is provided "as-is" without support or warranty. It is updated once a year due to a lack of time, developers, and funds. You can support this project by making a donation with [PayPal](
https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&amount=10&item_name=Timeshift%20Donation)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Thanks for your great software. I am using linux. I am wondering if it is possible to clone my current system to another PC using backup of timeshift. I will set the same PC name and account name, and even the same password.

**Comment by teejee2008** [comment]
Sorry, it is not supported. But feel free to experiment. It should work in simple cases where the entire system is on one partition.
