### ISSUE TITLE
Timeshift run from command line gives 300% sync 

### ISSUE THREAD

**Issue by darth-crunchus** [teejee2008/timeshift#842]
**Describe the bug**
Running timeshift from the command line to create a snapshot results in timeshift syncing files to 300.00%

**To Reproduce**
1. Open terminal
2. run sudo timeshift --create (with or without options) (also occurs with '--check' option if past snapshot time, but that's a --create operation, too.
3. snapshot creation happens, but does not stop at 100.00%.  It continues beyond 200.00% and stops at around 300.00%

**Expected behavior**
Expected sync to complete at 100.00%

**Screenshots**
https://paste.pics/1cfa86fbdcdad21d4f44ccd3b7815d12

**System:**
 - Pop! OS 21.04
 - Cosmic Desktop
 - Timeshift 21.09.1

**Comment by teejee2008** [comment]
It is not possible to estimate the total number of files before the sync is complete. The number of files in one snapshot is used for estimating the size of the next snapshot. Progress beyond 100% indicates that there are more files than the last snapshot.

**Comment by LinuxOnTheDesktop** [comment]
'Progress beyond 100% indicates that there are more files than the last snapshot': if the _UI_ does not impart that information to the user then, as this bug report shows, then confusion will result!

**Comment by darth-crunchus** [comment]
Obviously I was supposed to know that,  despite it being the first time I
had ever used the software.
