### ISSUE TITLE
After installing WeChat, the name of the distribution is displayed incorrectly。

### ISSUE THREAD

**Issue by EGQM** [teejee2008/timeshift#857]
my system is ubuntu。After installing WeChat, the name of the distribution become “Kylin V10” 。
![image](https://user-images.githubusercontent.com/18476511/151310531-1825551a-b3e5-4c3e-a483-61bf257f122e.png)

**Comment by TheyCallMeTojo** [comment]
> my system is ubuntu。After installing WeChat, the name of the distribution become “Kylin V10” 

This is certainly a WeChat issue, not a TimeShift issue.

**Comment by EGQM** [comment]
but the output of neofetch and screenfecth are right。
![image](https://user-images.githubusercontent.com/18476511/152632667-b3efe320-baee-4d13-905b-d4bb39464ef1.png)

**Comment by TheyCallMeTojo** [comment]
> but the output of neofetch and screenfecth are right.

TimeShift gets information from '/etc/lsb-release'.  What information does 'lsb-release -a' provide?
Distro name and version is also stored in '/etc/issue'.  'cat /etc/issue' what information is there?
From what I remember, NeoFetch get's it's information from 'uname'. 'uname -a' what information is there?

**Comment by EGQM** [comment]
@TheyCallMeTojo
`cat /etc/lsb-release`
ouptut:
```
DISTRIB_ID=Kylin
DISTRIB_RELEASE=V10
DISTRIB_CODENAME=kylin
DISTRIB_DESCRIPTION="Kylin V10 SP1"
DISTRIB_KYLIN_RELEASE=V10
DISTRIB_VERSION_TYPE=enterprise
DISTRIB_VERSION_MODE=normal
```

`lsb_release -a`
ouptut:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

`cat /etc/issue`
output:
```
Ubuntu 21.10 \n \l

```

`uname -a`
output:
```
Linux lu-sz 5.15.7-051507-generic #202112080459 SMP Wed Dec 8 10:35:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

`cat /etc/os-release`
output:
```
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```

`cat /usr/lib/os-release`
output:
```
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```

It seems that WeChat changed the content of /etc/lsb-release。

**Comment by TheyCallMeTojo** [comment]
At this point you can just edit the file and add replace with the information from  'os-release'.

**Comment by EGQM** [comment]
@TheyCallMeTojo
Thank you very much!
^_^
