### ISSUE TITLE
Crash to login prompt

### ISSUE THREAD

**Issue by CottonEaster** [teejee2008/timeshift#86]
I opened TimeShift, pressed the 'create' button, and then pressed the 'cancel' button. Result: suddenly I am back at the lock screen/Cinnamon logon prompt.

I could not find anything obviously relevant in my system log.

Linux Mint 18.3 x64 Cinnamon.
Timeshift 17.11

**Comment by teejee2008** [comment]
Check if the libxapp package is up-to-date. Install any updates for both libxapp and Timeshift from the Mint repos.

**Comment by CottonEaster** [comment]
I do not think any updates to those packages were available. Certainly none are now.

libxapp1 - version 1.0.4+sylvia
timeshift - version 17.11.2

I'll try the problematic procedure again and see if the same occurs as before.

**Comment by teejee2008** [comment]
Closing this one
