### ISSUE TITLE
Disabling qgroups makes Timeshift misbehave (snapshots not deleted on first try)

### ISSUE THREAD

**Issue by ShrirajHegde** [teejee2008/timeshift#865]
**Describe the bug**
Enabling qgroups freezes the system during scheduled snapshots. After Disabling qgroups, Timeshift still runs `btrfs qgroups destroy` which errors out.

**To Reproduce**
1. Go to 'Settings->Users'
2. Disable 'enable qgroups'
3.  run `btrfs quota disable mount-point`
4. Restart timeshift
5. Try to delete a snapshot, Error message:

```
Destroying qgroup: 0/333
E: Failed to destroy qgroup: '0/333'
E: Failed to remove snapshot: 2022-02-13_00-13-34
------------------------------------------------------------------------------

E: ERROR: can't list qgroups: quotas not enabled

E: btrfs returned an error: 256
E: Failed to query subvolume quota
```

**Expected behavior**
When btrfs qgroup is disabled and enable qgroup is disabled in timeshift, do not run any `btrfs qgroup` command. Also, it would be great to have the error output in the window.

>do not run any `btrfs qgroup` command

Or

Additionally, a warning about system freeze during snapshot would be useful here
![image](https://user-images.githubusercontent.com/66936172/153771451-c0501681-f130-405f-a2e6-fa0b2fe88eea.png)

**Screenshots**
<img src=https://user-images.githubusercontent.com/66936172/153771086-c8eef4d1-b169-4e5e-bed9-90b7ab0fb1dc.png width="300">

**System:**
 - Fedora 35 (With @ and @home subvolumes)
 - Desktop : Gnome
 - Application Version : 29.09.1

Also, can someone tell me what is the exact purpose of `btrfs qgroup destroy` when timeshift doesn't use `btrfs qgroup create`?

**Comment by l0rdg3x** [comment]
Same as https://github.com/teejee2008/timeshift/issues/680

**Comment by GenocideStomper** [comment]
Did the commit https://github.com/teejee2008/timeshift/commit/4b1af6df9c3b69e0d72e58e3e58278e2817f2867 disable or enable qgroup functionality permenently, along with hiding the option?
