### ISSUE TITLE
Timeshift GUI won't start on Wayland

### ISSUE THREAD

**Issue by marrobHD** [teejee2008/timeshift#887]
**Describe the bug**
I cant run timeshift gui with timeshift-launcher.

**To Reproduce**
1. Go to 'terminal'
2. Enter 'timeshift-launcher'
3. Enter user password
4. Error message

**Expected behavior**
Application should start as expected

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29308361/163425618-818ed146-3635-4c1c-b01b-8d6e482e5d54.png)

**System:**
 - Linux Distribution Name and Version: [Arch Linux, up to date]
 - WM [Sway]
 - Application Version [v21.09.1]

**Comment by thunderbirdtr** [comment]
You need policykit agent in order to run it

For example : https://www.reddit.com/r/swaywm/comments/9sb2di/polkit_authorisation_for_gui_apps/

If you have policykit then timeshift can make request to auth and able to open up in UI as well.

**Comment by marrobHD** [comment]
Policyagent is running in the background and it opens a popup to ask for permission. I guess it's not the problem.

**Comment by marrobHD** [comment]
Run timeshift-gtk with sudo preserve environment and it will open:
> `sudo -E timeshift-gtk`
> _Originally posted by @Llamach in https://github.com/teejee2008/timeshift/issues/190#issuecomment-1166281619_
