### ISSUE TITLE
I lost my data! Really!

### ISSUE THREAD

**Issue by tuganetworks** [teejee2008/timeshift#89]
One problem in Timeshift is fatal!

I have 5 backups (all without "Home")
Yestarday i selected the options about backup Home and Hidden Files & Pasts
After i recovery one backup (without "Home"!)

Result:
Timeshift delected all files of my Home! (very sad!)
And Recovery only Root, /

(Is there a program to recover lost files for Linux? Please help me!)

**Comment by teejee2008** [comment]
Once a folder has been excluded it remains excluded during restore, even if you change the settings and include it in future backups. This ensures that files do not get deleted on restore as in your case. 

Send me the exclude.list file from the snapshot directory. It will be under /timeshift/snapshots/<snapshot-that-was-restored>

**Comment by teejee2008** [comment]
Closing this one. v18.1.1 includes some additional safeguards to ensure this does not happen. Please share the exclude.list file if you still have it.
