### ISSUE TITLE
incompatibility with latest rsync 3.2.4

### ISSUE THREAD

**Issue by clusterx** [teejee2008/timeshift#891]
Details:
https://bbs.archlinux.org/viewtopic.php?pid=2032506#p2032506

temporary solution - downgrade rsync to version 3.2.3-4
pacman -U https://archive.archlinux.org/packages/r/rsync/rsync-3.2.3-4-x86_64.pkg.tar.zst

**Comment by manfred3000** [comment]
I haven't encountered any issues so far running `timeshift` on a fully updated arch system, so far. What error messages does `rsync` give? Have you reported the issue there, as well?

**Comment by MightyTree** [comment]
Got the same issue, there is barely anything besides "E: rsync returned an error", even with --debug and --verbose flags, as mentioned in the archlinux forum post. Downgrading rsync works for now. And timeshift deletes the fill rsync-log along with the folder once it finishes. Any idea how to retain that?

**Comment by Falav** [comment]
Thanks @clusterx, I was struggling finding a solution. Downgrading rsync indeed made Timeshift work again.
I use Manjaro, on Unstable branch, so closest to Arch packages versions.

**Comment by begin-theadventure** [comment]
Woah, I tried to do so many things and wondered why it didn't work..
sudo downgrade rsync, add rsync to IgnorePkg? [y/N] y and rebooted just in case.
Thanks.

**Comment by moritz-john** [comment]
Downgrading rsync to version `3.2.3-4` also fixed the issue for me.
Now I am able to create and see snapshots in the Timeshift GUI again.

**Comment by miicat** [comment]
Timeshift GUI didn't work, but it worked on terminal with `rsync` `3.2.4-1`  
Downgrading to `3.2.3-4` fixed the GUI

**Comment by JoonasPitk** [comment]
For me, the GUI works by creating the snapshot folder, but it is not listed.
CLI is also borked, where the folder I just made with the GUI isn't recognised. Also, if I try to create a snapshot through terminal, it fails and deletes my manual snapshot as well...

**Comment by Reno-Sifana** [comment]
> Thanks @clusterx, I was struggling finding a solution. Downgrading rsync indeed made Timeshift work again. I use Manjaro, on Unstable branch, so closest to Arch packages versions.

I also experienced it a few days ago. Timeshift suddenly creates a snapshot every hour. But I see in timeshift GUI No snapshot list as usual. Checking with the "systemctl status cronie" command shows that it failed to create a new snapshot. Finally I tried uninstalling timeshift. The intention was to reclaim free space in the /run/timeshift/ folder, I tried the command sudo rm -rf /run/timeshift/, but it showed an error device is busy and my linux couldn't be used. I finally immediately reinstalled my linux

**Comment by Reno-Sifana** [comment]
> Downgrading `rsync` to version `3.2.3-4` also fixed the issue for me. Now I am able to create and see snapshots in the `timeshift GUI` again.

I tried in terminal and GUI Finally it works. 
![Screenshot_2022-05-02_08-23-22](https://user-images.githubusercontent.com/68702583/166176105-02d2b782-7589-423c-9815-0a71bcb26d33.png)
![Screenshot_2022-05-02_08-16-38](https://user-images.githubusercontent.com/68702583/166176112-913fc723-f560-43e2-bae6-335b02d0ab4f.png)
 But in the update notification there is Rsync 3.2.4.1

**Comment by Reno-Sifana** [comment]
> Details: https://bbs.archlinux.org/viewtopic.php?pid=2032506#p2032506
> 
> temporary solution - downgrade rsync to version 3.2.3-4 pacman -U https://archive.archlinux.org/packages/r/rsync/rsync-3.2.3-4-x86_64.pkg.tar.zst

Why don't you try reporting the bug here https://github.com/WayneD/rsync/issues?q=is%3Aissue

> Details: https://bbs.archlinux.org/viewtopic.php?pid=2032506#p2032506
> 
> temporary solution - downgrade rsync to version 3.2.3-4 pacman -U https://archive.archlinux.org/packages/r/rsync/rsync-3.2.3-4-x86_64.pkg.tar.zst

Why don't you try reporting the bug here https://github.com/WayneD/rsync/issues?q=is%3Aissue

**Comment by sarmong** [comment]
@Reno-Sifana this version of rsync works fine on it's own, but not with Timeshify

**Comment by jonathonf** [comment]
Has anyone actually tried rebuilding the package against the latest `rsync`, as with any other AUR package that "breaks" after an update?

**Comment by sarmong** [comment]
@jonathonf yes. Didn't fix it

**Comment by clusterx** [comment]
the new rsync version was released due to **security critical vulnerabilities** so downgrading is not a permanent solution!

Rsync version 3.2.4 has been released. Another typical release with both bug fixes and some enhancements. It also contains a security fix for the bundled zlib 1.2.8, which may or may not be used in your particular build configuration.
https://rsync.samba.org/

**Comment by JoonasPitk** [comment]
My downgraded rsync does work with the zlib 1.2.12.

**Comment by clusterx** [comment]
> My downgraded rsync does work with the zlib 1.2.12. Of course situation shouldn't be permanent, unless Timeshift starts shipping its own fork of rsync.

basically means, it's not compatible with the official rsysnc version

**Comment by MartinX3** [comment]
20 days without an reaction.
Time to search for an alternative solution.

What's about borg backup?
https://github.com/borgbackup/borg

It's more used than timeshift and well maintained.

**Comment by Reno-Sifana** [comment]
Hmm. I'm curious, Why in some Linux distributions Timeshift is pre-installed. For example in Linux Mint.

**Comment by MartinX3** [comment]
> Hmm. I'm curious, Why in some Linux distributions Timeshift is pre-installed. For example in Linux Mint.

It's an old decision in the past.
Maybe it was a good choice then.
And changing standard stuff in a distribution is nothing which happens fast.

Also the newest rsync version in ubuntu is `3.2.3` in Ubuntu [kinetic](https://packages.ubuntu.com/kinetic/rsync)
Linux Mint 20.3 uses 20.04 with rsync `3.1.3` and Ubuntu 22.04 uses rsync `3.2.3`.

They will throw Timeshift away after they update rsync.

**Comment by Moonbase59** [comment]
Same bug here: Manjaro stable 21.2.6, rsync 3.2.4-1, Timeshift 21.09.1-3.

This issue should be addressed with high priority, since many users, and especially newbies, have learned and been trained to use Timeshift for safe backups.

**Comment by Nydoehar** [comment]
> 20 days without an reaction. Time to search for an alternative solution.
> 
> What's about borg backup? https://github.com/borgbackup/borg It also has a GUI app if you dislike the terminal.
> 
> It's more used than timeshift and well maintained.

I was thinking the same. Is it borg as easy to use as Timeshift?

**Comment by MartinX3** [comment]
> I was thinking the same. Is it borg as easy to use as Timeshift?

In my opinion yes

- https://borgbackup.readthedocs.io/en/stable/quickstart.html
- https://wiki.ubuntuusers.de/BorgBackup/
- GUI's
  - https://vorta.borgbase.com/
  - https://gitlab.gnome.org/World/pika-backup

**Comment by Nydoehar** [comment]
> > I was thinking the same. Is it borg as easy to use as Timeshift?
> 
> In my opinion yes
> 
>     * https://borgbackup.readthedocs.io/en/stable/quickstart.html
> 
>     * https://wiki.ubuntuusers.de/BorgBackup/
> 
>     * GUI's
>       
>       * https://vorta.borgbase.com/
>       * https://gitlab.gnome.org/World/pika-backup

Thank you!!! Gonna check it out. 
I started to use Timeshift a little more than one month ago, and it already fail me...

**Comment by moritz-john** [comment]
> I was thinking the same. Is it borg as easy to use as Timeshift?

I'd argue that the two tools were build for completely different purposes: snapshots vs backups.

I use Timeshift to try out new settings, software or configs and if it does not work or something breaks I can easily go back to a working system version.

On the other hand I'd use something like Borg to backup important files in case my HDD breaks.

From the Timeshift description: 
_Timeshift [...] is designed to protect only system files and settings. User files such as documents, pictures and music are excluded._

**Comment by Nydoehar** [comment]
> > I was thinking the same. Is it borg as easy to use as Timeshift?
> 
> I'd argue that the two tools were build for completely different purposes:
> 
> I use Timeshift to try out new settings, software or configs and if it does not work or something breaks I can easily go back to a working system version.
> 
> On the other hand I'd use something like Borg to backup important files in case my HDD breaks.
> 
> From the Timeshift description: _Timeshift [...] is designed to protect only system files and settings. User files such as documents, pictures and music are excluded._

I see. I liked Timeshift a lot for the two weeks it worked for me, but since it not working properly for now I gonna check out alternatives.

**Comment by MartinX3** [comment]
> From the Timeshift description: 
> _Timeshift [...] is designed to protect only system files and settings. User files such as documents, pictures and music are excluded._

Timeshift does snapshots and also backups the user.

The files are in the backups and the backups are either btrfs or hardlink snapshots via rsync.
(See ext4 hardlinks).

Borg backup also backup files and "snapshot" them like Timeshift, but doesn't depend on rsync.
Plus it compresses and encrypt you backups and client network network architecture, if you don't want to run it on the same computer.

**Comment by cziss** [comment]
Hi, same problem here, on both computers with Manjaro. Downgrade rsync solution is not nice.

**Comment by Nydoehar** [comment]
> Hi, same problem here, on both computers with Manjaro. Downgrade rsync solution is not nice.

Yes, it isn't. Check out Borg Backup, it seems a good alternative.

**Comment by cziss** [comment]
> 

Thank you for the advice. But I'm not really sure if Borg Backup is really alternative. I just want to "save" my system and when something goes wrong to easily restore it. Well, I think that I'll wait some time if it'll be solved.

**Comment by ratcashdev** [comment]
PR submitted.

**Comment by yochananmarqos** [comment]
@ratcashdev Is it really that simple? No wonder I wasn't affected as I'm already using UTF-8.

I've implemented your PR with 21.09.1-4 in the Manjaro community repo and the AUR.

**Comment by HowWof** [comment]
> PR submitted.
It is possible to have timeshift version in flatpack because then theoretically we could still keep obsolete versions to run timeshift and it would not be bad because dependencies would not affect the system and they would be in a container?

**Comment by ratcashdev** [comment]
> @ratcashdev Is it really that simple? No wonder I wasn't affected as I'm already using UTF-8.
> 
> I've implemented your PR with 21.09.1-4 in the Manjaro community repo and the AUR.

Package updated on my laptop and working nicely. Thanks for this quick repo update on Manjaro (my favorite OS)! Much obliged!

**Comment by cziss** [comment]
thank you, it works fine now :+1:

**Comment by MartinX3** [comment]
@clusterx the PR is not merged. So the issue is still existing for everyone without this AUR package but with rsync 3.2.4.

**Comment by dandreossi** [comment]
A workaround could be run `env LC_ALL=C.UTF-8 timeshift ` or `env LC_ALL=C.UTF-8 timeshift-gtk` (if someone need GUI)

**Comment by marko19914** [comment]
Hello! Same issue on Fedora 36. Downgrade and versionlocking solved the issue for now.

**Comment by emereld** [comment]
Yes, same issue with **Fedora 36**. Workaround as described above fixes the issue for now:

```
# add rsync version lock
sudo dnf install rsync.x86_64-3.2.3-14.fc36
sudo dnf install python3-dnf-plugin-versionlock-4.2.1-1.fc36.noarch
sudo dnf versionlock add rsync-3.2.3-14.fc36.x86_64

# remove rsync version lock
sudo dnf versionlock delete rsync-3.2.3-14.fc36.x86_64
```

**Comment by JoonasPitk** [comment]
Fedora hasn't moved to the maintained fork?
https://github.com/linuxmint/timeshift

**Comment by emereld** [comment]
Seems like Fedora/RedHat has not switched yet, yes

21.09.x is their last version. 
https://koji.fedoraproject.org/koji/packageinfo?packageID=26246
