### ISSUE TITLE
Save Backup on NFS Share?

### ISSUE THREAD

**Issue by bender2305** [teejee2008/timeshift#90]
Hi,

I was just wondering if it is possible to save the Backup on a NFS share, mounted through /etc/fstab? I would like to save the Backup on a network location but unfortunately although the folders are mounted I can not select them as backup location in timeshift (only local drives are available).

Any help would be appreciated!

**Comment by teejee2008** [comment]
Only local drives are supported

**Comment by OdinVex** [comment]
@teejee2008 Any particular reason? I'm interested in Timeshift backups over network with the possibility of restoring partition layout and UUIDs (etc) for full restoration and I'm not sure how I might tackle such a task if Timeshift only supports local disk-drives.
