### ISSUE TITLE
JSON data must be UTF-8 encoded

### ISSUE THREAD

**Issue by zayats1** [teejee2008/timeshift#906]
**Describe the bug**
JSON data must be UTF-8 encoded
https://pastebin.com/RwVYtrGY

**To Reproduce**
1) Install timeshift-autosnap
https://gitlab.com/gobonja/timeshift-autosnap

2) upgrade system

**Expected behavior**
Creating new snapshot without much text

**Screenshots**
see logs

**System:**
 - Linux Distribution Name and Version: [Endavour OS Roling]
 - Desktop [KDE Plasma 5.24.5]
 - Application Version [latest]

**Comment by dandreossi** [comment]
A workaround could be run ```env LC_ALL=C.UTF-8 timeshift``` or ```env LC_ALL=C.UTF-8 timeshift-gtk```
