### ISSUE TITLE
Write Tags out

### ISSUE THREAD

**Issue by NikoKrause** [teejee2008/timeshift#92]
The tags are abbreviated with `O` for `On Demand` etc.
It's described in the Tooltip, what those abbreviations mean, but the tooltip is localized and the abbreviations are not (see German timeshift):
![screenshot-window-2017-12-08-235118](https://user-images.githubusercontent.com/8415124/33788483-d3f7abc8-dc72-11e7-9835-bf9c23b51213.png)

I'll suggest to not abbreviate. There's enough place in the Tag column to write "Boot, Hourly" etc.

**Comment by teejee2008** [comment]
A snapshot can have multiple tags. Multiple tags will not fit in the column.

**Comment by NikoKrause** [comment]
Can we translate the tags?

**Comment by NikoKrause** [comment]
@to-ba

Any ideas?

**Comment by to-ba** [comment]
Make the tags in this column translatable would be great. :-)
Using tags or the complete word is a design decision.

But first the tags should be the same – column and tooltip.

**Comment by teejee2008** [comment]
Fixed in the latest commit. Now only the descriptions are marked for translation in tooltip.
The tags themselves (O,B,H,D,W,M) are hard-coded into application logic and cannot be translated.

**Comment by MartinX3** [comment]
I searched for the meaning of tags in the whole internet, until I saw this issue and see, that I need to put my mouse on the cryptic letters to see a hint with the meaning of them.

But, this hint doesn't occur if I hover the selected entry or the column headline.
