### ISSUE TITLE
What for is stalemount reported

### ISSUE THREAD

**Issue by GaVenga** [teejee2008/timeshift#921]
System:  Manjaro Gnome unstable
Timeshift: 22.06.1-1

Message, may be no bug:
 -  Found stale mount for device '/dev/sdc1' at path '/run/timeshift/13222/backup' Unmounted successfully
- Terminal, "sudo timeshift --list"
- When: every time I do the command; even if I do it two times in sequence in the same shell.
- the path "/run/timeshift/...."  does not exist. 
Question:
Why. Whats wrong with the tigers?

**Comment by teejee2008** [comment]
Timeshift now mounts devices to a temporary folder and unmounts the folder after use. Sometimes the temporary folder cannot be unmounted since the device is still busy. It will be unmounted in the next run. This message can be ignored.

**Comment by GaVenga** [comment]
Thank You!
