### ISSUE TITLE
Why using a random numeric folder inside /run/timeshift for mounting the snapshots directory?

### ISSUE THREAD

**Issue by LorenzoBettini** [teejee2008/timeshift#922]
**Describe the bug**
I'm using Timeshift v22.06.2 with BTRFS in Arch Linux. Timeshift mounts the snapshots directory **each time** in a different subfolder of `/run/timeshift`. Why is that? This breaks other tools like `grub-btrfs` because it cannot be configured once and for all (everytime the mount point changes, see also https://aur.archlinux.org/packages/timeshift#comment-871556).

**To Reproduce**
1. Install timeshift in Arch using AUR
2. Launch timeshift and see the random created directory in `/run/timeshift/<randomnumber1>`
3. Close timshift; Launch timeshift again and see another random created directory in `/run/timeshift/<randomnumber2>`

**Expected behavior**
I would expect timeshift to always use the same directory for mounting (I'm sure that was happing before)

**System:**
 - Linux Distribution Name and Version: Arch
 - Desktop GNOME
 - Application Version 22.06.2

**Comment by LorenzoBettini** [comment]
@Zesko where `UUID=3ccce400-6cf3-4d91-99a0-d5228a8fe2d3` has to be replaced with the same UUID of the disk physical partition, hasn't it?

**Comment by LorenzoBettini** [comment]
@Zesko thanks!
But is it documented anywhere?

**Comment by Zesko** [comment]
> But is it documented anywhere?

I am not a developer of Timeshift, just issue reporter and also supporter.
But I found the same solution from Manjaro forum:
https://forum.manjaro.org/t/grub-doesnt-list-my-manual-btrfs-timeshift-snapshots-anymore/113618

**Comment by teejee2008** [comment]
Timeshift now mounts devices to a temporary folder and unmounts the folder after use. It will not use any existing mount points. The number in the path is the PID of the Timeshift process.

**Comment by Mc-Pain** [comment]
> The number in the path is the PID of the Timeshift process.

Does not answer **why** path contains the PID.
Neither d7ba851 nor issues mentioned in commit message describes why PID appears in the path

**Comment by teejee2008** [comment]
To make the path unique

**Comment by Mc-Pain** [comment]
> To make the path unique

Am I right about why path **should** be unique?
https://github.com/linuxmint/timeshift/issues/22#issuecomment-1217737375

If not, please describe why since it's neither documented nor obvious

**Comment by teejee2008** [comment]
That's correct. The path will be unique for each instance of timeshift and any mounted devices can be safely unmounted.
