### ISSUE TITLE
archive repo and redirect too linuxmint repo

### ISSUE THREAD

**Issue by fugbixer** [teejee2008/timeshift#929]
Since this repo is no longer actively maintained, thanks for the time it was, please merge with [linuxmint repo of timeshift](https://github.com/linuxmint/timeshift) so that upstreams and issues can be handled more obvious. 

Please archive this repository and make a huge obvious redirect to https://github.com/linuxmint/timeshift

**Comment by teejee2008** [comment]
Sorry. No plans to close this repo. There's already a message redirecting to the Linux Mint fork. The version of Timeshift in this repo will continue to be available for those who need it.

**Comment by fugbixer** [comment]
@teejee2008  it still will be available when you archive the repo, just no one can create issues anymore and when its not actively maintained i guess it makes sense or do you disagree? i might be wrong about this

**Comment by teejee2008** [comment]
It doesn't make sense to me. How do I commit changes to this repo if it's archived?
