### ISSUE TITLE
How is snapshot time determined and can it be modified?

### ISSUE THREAD

**Issue by oblongau** [teejee2008/timeshift#94]
I see the “Schedule” item in Settings, which lets you select the Snapshot Levels. There is nothing there for what time of day the snapshots are taken. I know that in my case a snapshot is taken daily at 13:00 (only “Daily*” is selected, “Keep 3”). But how do I change that time of day?

**Comment by teejee2008** [comment]
See #64. Please search for existing items before opening new one.
