### ISSUE TITLE
Can't use drives larger than 2 TB

### ISSUE THREAD

**Issue by kdickerson** [teejee2008/timeshift#95]
I have 2 machines running the OS off SSDs with spinning disk storage.  One of them has a 3TB HDD.  The other has 2x2TB drives and 2x4TB drives.  I can select the 2TB drives for Timeshift to use, but cannot select the 3TB drive or the 4TB drives.

In the Settings -> Location UI it shows the disks with an entry like this:
Disk: "HGST HDN724030AL ATA"
Type: ext4
Size: 3 TB
Free: 
(The entry under "Free" is blank, an empty string)

When I click on the drive, at the bottom of the UI on red background it says "Selected device does not have Linux Partition"

**Comment by teejee2008** [comment]
Will be fixed in next update

**Comment by teejee2008** [comment]
I don't have a 3 TB disk for testing. Could you post the output of following commands for the 3 TB and 4 TB drives?

`lsblk --fs`
`df -T -B1`

**Comment by kdickerson** [comment]
3 TB drive:
```bash
kyle@silver-bullet ~ $ lsblk --fs /dev/sdb
NAME FSTYPE LABEL        UUID                                 MOUNTPOINT
sdb  ext4   General 3 TB e90eb9e4-318b-46d0-b913-ffb004995ed0 /mnt/General

kyle@silver-bullet ~ $ df -T -B1 /dev/sdb
Filesystem     Type     1B-blocks          Used    Available Use% Mounted on
/dev/sdb       ext4 2953373728768 2042674782208 760652521472  73% /mnt/General
```

4 TB drives:
```bash
kyle@silver-nuc ~ $ lsblk --fs /dev/sdd /dev/sde
NAME FSTYPE LABEL MOUNTPOINT
sdd               /mnt/General
sde               /mnt/4TB_Storage

kyle@silver-nuc ~ $ df -T -B1 /dev/sdd /dev/sde
Filesystem     Type     1B-blocks          Used     Available Use% Mounted on
/dev/sdd       ext4 3937873526784 2145333010432 1592484388864  58% /mnt/General
/dev/sde       ext4 3937873526784 2435191463936 1302625935360  66% /mnt/4TB_Storage
```

No idea why lsblk doesn't show FSTYPE or LABEL for on the `silver-nuc` system.  It doesn't show it for any of the drives, not just the 4 TB ones.  Must just be a version difference.  `silver-bullet` is running Mint 18.3 with `lsblk --version` `lsblk from util-linux 2.27.1` , `silver-nuc` is running Mint 17.3, `lsblk` doesn't respond to the `--version` flag.

**Comment by teejee2008** [comment]
Looks like these drives were directly formatted with ext4 without creating partitions. I'll add support for this. Mint 17 is based on Ubuntu 14.04. If the FSTYPE is empty these drives won't show up in the snapshot list.

**Comment by kdickerson** [comment]
I didn't realize it was possible to not have a partition on the disk.  I
wonder how I managed to set them up that way.

**Comment by teejee2008** [comment]
Added support in v18.1
