### ISSUE TITLE
Setup to include partition labels

### ISSUE THREAD

**Issue by ewangi** [teejee2008/timeshift#97]
May I suggest that the “Select Snapshot Location” window in Timeshift setup should include partition and/or filesystem labels to ease choice of partition (particularly important where the user has many different partitions set up). This should be a golden rule of thumb for any screen that allows you to choose between partitions.

**Comment by Barlafuss** [comment]
I fully share ewangi suggestion.
I say more, the fact you cannot choose the folder/directory is a big limitation for a so smart project. Storage devices are so big now, that you could have on the same device, in different directories, timeshift backup of different systems. This would apply to me ...

**Comment by teejee2008** [comment]
Added in v18.1. Name and Label will be displayed in device list.

**Comment by Barlafuss** [comment]
Thanks for the enhancement

**Comment by ewangi** [comment]
Many thanks indeed.
