### ISSUE TITLE
Timeshift 17.11 won't open on Xubuntu 16.04.3

### ISSUE THREAD

**Issue by upekshapriya** [teejee2008/timeshift#98]
I get a dialog box that asks me to give superuser permissions when I try to open Timeshift. It works fine with 17.10

![image](https://user-images.githubusercontent.com/438647/34004120-f478e9f4-e0ee-11e7-88ff-708d4a98ac68.png)

And when I put in the user password, nothing happens.

Any ideas what is going wrong?

**Comment by teejee2008** [comment]
That's normal. You need to give superuser permission to start Timeshift.

**Comment by upekshapriya** [comment]
I am using it on a headless server so I'm using VNC to see the desktop and I'm not sure how I can logout and login to an Xorg session as it starts up on boot.

In 17.10 it is working fine (on a similar server) and I get the normal dialog:

![screen sharing picture 15 december 2017 at 09 18 09 gmt](https://user-images.githubusercontent.com/438647/34035650-97acbc3c-e17a-11e7-8bfa-cee3ea1112aa.png)

It appears that the only difference between 17.10 and 17.11 regards Wayland is 

`Prefer pkexec for starting timeshift in Wayland session`

I am guessing this is causing the issue for my set up.

**Comment by teejee2008** [comment]
17.10 uses gksu for starting timeshift-gtk.
Try running 'gksu timeshift-gtk'

**Comment by teejee2008** [comment]
Gksu is deprecated and will soon be removed from Linux distributions in the future. Hence the switch to pkexec.
The actual issue is with Wayland which doesn't allow GUI applications to run as root. There is another issue open for this. #35
